windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.104.129.219/tcp/1211/p2p/12D3KooWBANL6JKg7uZZoYCvqUfKr7RCJ9QeisDjHXJgYEuf4f2N",
        "/ip4/172.104.129.219/udp/1211/quic-v1/p2p/12D3KooWBANL6JKg7uZZoYCvqUfKr7RCJ9QeisDjHXJgYEuf4f2N",
        "/ip6/2a01:7e01::f03c:94ff:fe22:2888/tcp/1211/p2p/12D3KooWBANL6JKg7uZZoYCvqUfKr7RCJ9QeisDjHXJgYEuf4f2N",
        "/ip6/2a01:7e01::f03c:94ff:fe22:2888/udp/1211/quic-v1/p2p/12D3KooWBANL6JKg7uZZoYCvqUfKr7RCJ9QeisDjHXJgYEuf4f2N",
        "/ip4/45.33.30.89/udp/1211/quic-v1/p2p/12D3KooWLfvD8KmKBc4T7XP6TNsCVMtg7Bqm1aCazkv4K8eEUJw8",
        "/ip6/2600:3c00::f03c:94ff:fe22:2253/tcp/1211/p2p/12D3KooWLfvD8KmKBc4T7XP6TNsCVMtg7Bqm1aCazkv4K8eEUJw8",
        "/ip6/2600:3c00::f03c:94ff:fe22:2253/udp/1211/quic-v1/p2p/12D3KooWLfvD8KmKBc4T7XP6TNsCVMtg7Bqm1aCazkv4K8eEUJw8",
        "/ip4/45.33.30.89/tcp/1211/p2p/12D3KooWLfvD8KmKBc4T7XP6TNsCVMtg7Bqm1aCazkv4K8eEUJw8",
        "/ip4/45.56.122.237/tcp/1211/p2p/12D3KooWFVntTUxhoVmRjFdN3heb3p72VphMwVutpeFWj74vaPdp",
        "/ip4/45.56.122.237/udp/1211/quic-v1/p2p/12D3KooWFVntTUxhoVmRjFdN3heb3p72VphMwVutpeFWj74vaPdp",
        "/ip6/2600:3c00::f03c:94ff:fe22:2810/tcp/1211/p2p/12D3KooWFVntTUxhoVmRjFdN3heb3p72VphMwVutpeFWj74vaPdp",
        "/ip6/2600:3c00::f03c:94ff:fe22:2810/udp/1211/quic-v1/p2p/12D3KooWFVntTUxhoVmRjFdN3heb3p72VphMwVutpeFWj74vaPdp",
        "/ip6/2400:8907::f03c:94ff:fe22:223b/udp/1211/quic-v1/p2p/12D3KooWKtv1xYDr6KZ5fxTuoDsZbtTx7mLZWGCPbJw4SdK2TCph",
        "/ip4/139.144.99.245/tcp/1211/p2p/12D3KooWKtv1xYDr6KZ5fxTuoDsZbtTx7mLZWGCPbJw4SdK2TCph",
        "/ip4/139.144.99.245/udp/1211/quic-v1/p2p/12D3KooWKtv1xYDr6KZ5fxTuoDsZbtTx7mLZWGCPbJw4SdK2TCph",
        "/ip6/2400:8907::f03c:94ff:fe22:223b/tcp/1211/p2p/12D3KooWKtv1xYDr6KZ5fxTuoDsZbtTx7mLZWGCPbJw4SdK2TCph",
        "/ip6/2a01:7e01::f03c:94ff:fe22:289a/udp/1211/quic-v1/p2p/12D3KooWJPr8MNGsZFqb2wLTPQpm1FCjyDT9YHqPgxvE5VZeSeek",
        "/ip4/139.162.188.148/tcp/1211/p2p/12D3KooWJPr8MNGsZFqb2wLTPQpm1FCjyDT9YHqPgxvE5VZeSeek",
        "/ip4/139.162.188.148/udp/1211/quic-v1/p2p/12D3KooWJPr8MNGsZFqb2wLTPQpm1FCjyDT9YHqPgxvE5VZeSeek",
        "/ip6/2a01:7e01::f03c:94ff:fe22:289a/tcp/1211/p2p/12D3KooWJPr8MNGsZFqb2wLTPQpm1FCjyDT9YHqPgxvE5VZeSeek",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securachainDataPath: ".securachainData/"
blockRegistryPath: "blockRegistry.json"
fileRegistryPath: "fileRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB