windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.25.107/tcp/1211/p2p/12D3KooWRZjuEt5HTpMPJrfx6u9xWkyi1xuiCoaZnPicN1G1gfYd",
        "/ip4/172.105.25.107/udp/1211/quic-v1/p2p/12D3KooWRZjuEt5HTpMPJrfx6u9xWkyi1xuiCoaZnPicN1G1gfYd",
        "/ip6/2600:3c04::f03c:94ff:fe0b:d1aa/tcp/1211/p2p/12D3KooWRZjuEt5HTpMPJrfx6u9xWkyi1xuiCoaZnPicN1G1gfYd",
        "/ip6/2600:3c04::f03c:94ff:fe0b:d1aa/udp/1211/quic-v1/p2p/12D3KooWRZjuEt5HTpMPJrfx6u9xWkyi1xuiCoaZnPicN1G1gfYd",
        "/ip4/172.233.59.219/tcp/1211/p2p/12D3KooWK1U2hmYjBsXzeYpxfHgKZD7YDgdGMS32wkgsagFm3UnV",
        "/ip4/172.233.59.219/udp/1211/quic-v1/p2p/12D3KooWK1U2hmYjBsXzeYpxfHgKZD7YDgdGMS32wkgsagFm3UnV",
        "/ip6/2600:3c0e::f03c:94ff:fe0b:d159/tcp/1211/p2p/12D3KooWK1U2hmYjBsXzeYpxfHgKZD7YDgdGMS32wkgsagFm3UnV",
        "/ip6/2600:3c0e::f03c:94ff:fe0b:d159/udp/1211/quic-v1/p2p/12D3KooWK1U2hmYjBsXzeYpxfHgKZD7YDgdGMS32wkgsagFm3UnV",
        "/ip6/2600:3c08::f03c:94ff:fe0b:d11c/tcp/1211/p2p/12D3KooWKQS98dPCZzH8vBpgb4oNmqgWdSEP9tEJ7aKyaRMEYhmT",
        "/ip6/2600:3c08::f03c:94ff:fe0b:d11c/udp/1211/quic-v1/p2p/12D3KooWKQS98dPCZzH8vBpgb4oNmqgWdSEP9tEJ7aKyaRMEYhmT",
        "/ip4/172.235.21.184/tcp/1211/p2p/12D3KooWKQS98dPCZzH8vBpgb4oNmqgWdSEP9tEJ7aKyaRMEYhmT",
        "/ip4/172.235.21.184/udp/1211/quic-v1/p2p/12D3KooWKQS98dPCZzH8vBpgb4oNmqgWdSEP9tEJ7aKyaRMEYhmT",
        "/ip4/213.52.130.29/tcp/1211/p2p/12D3KooWJXFABk3g5cNS8TmgWhybm2SFG9EHCWyrkXpPPCx7SYkp",
        "/ip4/213.52.130.29/udp/1211/quic-v1/p2p/12D3KooWJXFABk3g5cNS8TmgWhybm2SFG9EHCWyrkXpPPCx7SYkp",
        "/ip6/2a01:7e00::f03c:94ff:fe0b:d10e/tcp/1211/p2p/12D3KooWJXFABk3g5cNS8TmgWhybm2SFG9EHCWyrkXpPPCx7SYkp",
        "/ip6/2a01:7e00::f03c:94ff:fe0b:d10e/udp/1211/quic-v1/p2p/12D3KooWJXFABk3g5cNS8TmgWhybm2SFG9EHCWyrkXpPPCx7SYkp",
        "/ip6/2600:3c03::f03c:94ff:fe0b:d1e6/udp/1211/quic-v1/p2p/12D3KooWLGFewebrCgcRau2d9mxdUnqKeVU5b6S1tjB8VxmCCAkf",
        "/ip4/45.33.65.231/tcp/1211/p2p/12D3KooWLGFewebrCgcRau2d9mxdUnqKeVU5b6S1tjB8VxmCCAkf",
        "/ip4/45.33.65.231/udp/1211/quic-v1/p2p/12D3KooWLGFewebrCgcRau2d9mxdUnqKeVU5b6S1tjB8VxmCCAkf",
        "/ip6/2600:3c03::f03c:94ff:fe0b:d1e6/tcp/1211/p2p/12D3KooWLGFewebrCgcRau2d9mxdUnqKeVU5b6S1tjB8VxmCCAkf",
        "/ip4/172.105.25.115/tcp/1211/p2p/12D3KooWEr22Wju9zGR9QUge6NoTYvc94MsCzMXEdbfrbRuHVZSj",
        "/ip4/172.105.25.115/udp/1211/quic-v1/p2p/12D3KooWEr22Wju9zGR9QUge6NoTYvc94MsCzMXEdbfrbRuHVZSj",
        "/ip6/2600:3c04::f03c:94ff:fe0b:d10d/tcp/1211/p2p/12D3KooWEr22Wju9zGR9QUge6NoTYvc94MsCzMXEdbfrbRuHVZSj",
        "/ip6/2600:3c04::f03c:94ff:fe0b:d10d/udp/1211/quic-v1/p2p/12D3KooWEr22Wju9zGR9QUge6NoTYvc94MsCzMXEdbfrbRuHVZSj",
        "/ip4/139.162.46.215/tcp/1211/p2p/12D3KooWKDjbHC6cUZFgUZKtpR1Cq3MDy9uZAS4CVkRvcxWwVvLB",
        "/ip4/139.162.46.215/udp/1211/quic-v1/p2p/12D3KooWKDjbHC6cUZFgUZKtpR1Cq3MDy9uZAS4CVkRvcxWwVvLB",
        "/ip6/2400:8901::f03c:94ff:fe0b:d1ae/tcp/1211/p2p/12D3KooWKDjbHC6cUZFgUZKtpR1Cq3MDy9uZAS4CVkRvcxWwVvLB",
        "/ip6/2400:8901::f03c:94ff:fe0b:d1ae/udp/1211/quic-v1/p2p/12D3KooWKDjbHC6cUZFgUZKtpR1Cq3MDy9uZAS4CVkRvcxWwVvLB",
        "/ip4/172.233.28.90/tcp/1211/p2p/12D3KooWRy7ppyfdRuhYLFXGu6iQW49kfWS9cVKQUKiTyod5ixRt",
        "/ip4/172.233.28.90/udp/1211/quic-v1/p2p/12D3KooWRy7ppyfdRuhYLFXGu6iQW49kfWS9cVKQUKiTyod5ixRt",
        "/ip6/2600:3c0d::f03c:94ff:fe0b:d1e5/tcp/1211/p2p/12D3KooWRy7ppyfdRuhYLFXGu6iQW49kfWS9cVKQUKiTyod5ixRt",
        "/ip6/2600:3c0d::f03c:94ff:fe0b:d1e5/udp/1211/quic-v1/p2p/12D3KooWRy7ppyfdRuhYLFXGu6iQW49kfWS9cVKQUKiTyod5ixRt",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB