windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.104.133.139/udp/1211/quic-v1/p2p/12D3KooWA6WkZkRojve7Cpvv7EHQ9N6se2XQMFkjZCdTwzTKa38s",
        "/ip6/2a01:7e01::f03c:94ff:fe30:2f45/tcp/1211/p2p/12D3KooWA6WkZkRojve7Cpvv7EHQ9N6se2XQMFkjZCdTwzTKa38s",
        "/ip6/2a01:7e01::f03c:94ff:fe30:2f45/udp/1211/quic-v1/p2p/12D3KooWA6WkZkRojve7Cpvv7EHQ9N6se2XQMFkjZCdTwzTKa38s",
        "/ip4/172.104.133.139/tcp/1211/p2p/12D3KooWA6WkZkRojve7Cpvv7EHQ9N6se2XQMFkjZCdTwzTKa38s",
        "/ip4/172.233.43.189/tcp/1211/p2p/12D3KooWSJnsGZjSXTwf7D1QHCjLt4ABDjdXQ6NHq859ehcBz9NB",
        "/ip4/172.233.43.189/udp/1211/quic-v1/p2p/12D3KooWSJnsGZjSXTwf7D1QHCjLt4ABDjdXQ6NHq859ehcBz9NB",
        "/ip6/2600:3c0e::f03c:94ff:fe30:3e80/tcp/1211/p2p/12D3KooWSJnsGZjSXTwf7D1QHCjLt4ABDjdXQ6NHq859ehcBz9NB",
        "/ip6/2600:3c0e::f03c:94ff:fe30:3e80/udp/1211/quic-v1/p2p/12D3KooWSJnsGZjSXTwf7D1QHCjLt4ABDjdXQ6NHq859ehcBz9NB",
        "/ip4/172.232.97.88/udp/1211/quic-v1/p2p/12D3KooWHaDBBpUgGvBgtQctGPbjTUM8fSiBsPWiKgUUDp2KAyws",
        "/ip6/2600:3c08::f03c:94ff:fe30:2f4b/tcp/1211/p2p/12D3KooWHaDBBpUgGvBgtQctGPbjTUM8fSiBsPWiKgUUDp2KAyws",
        "/ip6/2600:3c08::f03c:94ff:fe30:2f4b/udp/1211/quic-v1/p2p/12D3KooWHaDBBpUgGvBgtQctGPbjTUM8fSiBsPWiKgUUDp2KAyws",
        "/ip4/172.232.97.88/tcp/1211/p2p/12D3KooWHaDBBpUgGvBgtQctGPbjTUM8fSiBsPWiKgUUDp2KAyws",
        "/ip6/2600:3c03::f03c:94ff:fe30:3ed3/udp/1211/quic-v1/p2p/12D3KooWNxksaXmQjbCqKTK2M8sbXdjnMaKQX2AsE78K33akhMGL",
        "/ip4/96.126.108.170/tcp/1211/p2p/12D3KooWNxksaXmQjbCqKTK2M8sbXdjnMaKQX2AsE78K33akhMGL",
        "/ip4/96.126.108.170/udp/1211/quic-v1/p2p/12D3KooWNxksaXmQjbCqKTK2M8sbXdjnMaKQX2AsE78K33akhMGL",
        "/ip6/2600:3c03::f03c:94ff:fe30:3ed3/tcp/1211/p2p/12D3KooWNxksaXmQjbCqKTK2M8sbXdjnMaKQX2AsE78K33akhMGL",
        "/ip6/2600:3c04::f03c:94ff:fe30:f3db/tcp/1211/p2p/12D3KooWDwwb7HZGQEqynutCt1ukC8n4o7gJqTYaq5feS9g9qMCg",
        "/ip6/2600:3c04::f03c:94ff:fe30:f3db/udp/1211/quic-v1/p2p/12D3KooWDwwb7HZGQEqynutCt1ukC8n4o7gJqTYaq5feS9g9qMCg",
        "/ip4/192.53.122.85/tcp/1211/p2p/12D3KooWDwwb7HZGQEqynutCt1ukC8n4o7gJqTYaq5feS9g9qMCg",
        "/ip4/192.53.122.85/udp/1211/quic-v1/p2p/12D3KooWDwwb7HZGQEqynutCt1ukC8n4o7gJqTYaq5feS9g9qMCg",
        "/ip4/170.187.248.16/tcp/1211/p2p/12D3KooWBHtFMQ2ZSgFtqJS9TRKdeRgmfopuFzFo2R8C3WmfdrfW",
        "/ip4/170.187.248.16/udp/1211/quic-v1/p2p/12D3KooWBHtFMQ2ZSgFtqJS9TRKdeRgmfopuFzFo2R8C3WmfdrfW",
        "/ip6/2400:8904::f03c:94ff:fe30:2f91/tcp/1211/p2p/12D3KooWBHtFMQ2ZSgFtqJS9TRKdeRgmfopuFzFo2R8C3WmfdrfW",
        "/ip6/2400:8904::f03c:94ff:fe30:2f91/udp/1211/quic-v1/p2p/12D3KooWBHtFMQ2ZSgFtqJS9TRKdeRgmfopuFzFo2R8C3WmfdrfW",
        "/ip6/2400:8904::f03c:94ff:fe30:3e94/tcp/1211/p2p/12D3KooWLyBHsuPu6orMs5Wh4KjRE3monuLYQSzzjoe13dAzbEV9",
        "/ip6/2400:8904::f03c:94ff:fe30:3e94/udp/1211/quic-v1/p2p/12D3KooWLyBHsuPu6orMs5Wh4KjRE3monuLYQSzzjoe13dAzbEV9",
        "/ip4/139.144.4.131/tcp/1211/p2p/12D3KooWLyBHsuPu6orMs5Wh4KjRE3monuLYQSzzjoe13dAzbEV9",
        "/ip4/139.144.4.131/udp/1211/quic-v1/p2p/12D3KooWLyBHsuPu6orMs5Wh4KjRE3monuLYQSzzjoe13dAzbEV9",
        "/ip4/178.79.143.35/tcp/1211/p2p/12D3KooWCAxnB1FCY7W49njSm24ygc9afv5PNLEYTwSjJ7GsMzME",
        "/ip4/178.79.143.35/udp/1211/quic-v1/p2p/12D3KooWCAxnB1FCY7W49njSm24ygc9afv5PNLEYTwSjJ7GsMzME",
        "/ip6/2a01:7e00::f03c:94ff:fe30:285a/tcp/1211/p2p/12D3KooWCAxnB1FCY7W49njSm24ygc9afv5PNLEYTwSjJ7GsMzME",
        "/ip6/2a01:7e00::f03c:94ff:fe30:285a/udp/1211/quic-v1/p2p/12D3KooWCAxnB1FCY7W49njSm24ygc9afv5PNLEYTwSjJ7GsMzME",
        "/ip4/172.232.193.193/tcp/1211/p2p/12D3KooWJLZkjzAx4vJ2qxv4V8hxfjUMHjwymNrTHsLjFXY4H7SR",
        "/ip4/172.232.193.193/udp/1211/quic-v1/p2p/12D3KooWJLZkjzAx4vJ2qxv4V8hxfjUMHjwymNrTHsLjFXY4H7SR",
        "/ip6/2600:3c0b::f03c:94ff:fe30:284c/tcp/1211/p2p/12D3KooWJLZkjzAx4vJ2qxv4V8hxfjUMHjwymNrTHsLjFXY4H7SR",
        "/ip6/2600:3c0b::f03c:94ff:fe30:284c/udp/1211/quic-v1/p2p/12D3KooWJLZkjzAx4vJ2qxv4V8hxfjUMHjwymNrTHsLjFXY4H7SR",
        "/ip4/172.105.255.133/tcp/1211/p2p/12D3KooWDyYTqYYdVvjErgvwbFEZRNg7EdGAc9yQky39d5vUACTb",
        "/ip4/172.105.255.133/udp/1211/quic-v1/p2p/12D3KooWDyYTqYYdVvjErgvwbFEZRNg7EdGAc9yQky39d5vUACTb",
        "/ip6/2400:8907::f03c:94ff:fe30:a650/tcp/1211/p2p/12D3KooWDyYTqYYdVvjErgvwbFEZRNg7EdGAc9yQky39d5vUACTb",
        "/ip6/2400:8907::f03c:94ff:fe30:a650/udp/1211/quic-v1/p2p/12D3KooWDyYTqYYdVvjErgvwbFEZRNg7EdGAc9yQky39d5vUACTb",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB