windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.233.59.219/tcp/1211/p2p/12D3KooWAuu2R5HB5fLxmenhqxDSdKDv1GqzML3RGsVhszR6qu3L",
        "/ip4/172.233.59.219/udp/1211/quic-v1/p2p/12D3KooWAuu2R5HB5fLxmenhqxDSdKDv1GqzML3RGsVhszR6qu3L",
        "/ip6/2600:3c0e::f03c:94ff:fe7d:6029/tcp/1211/p2p/12D3KooWAuu2R5HB5fLxmenhqxDSdKDv1GqzML3RGsVhszR6qu3L",
        "/ip6/2600:3c0e::f03c:94ff:fe7d:6029/udp/1211/quic-v1/p2p/12D3KooWAuu2R5HB5fLxmenhqxDSdKDv1GqzML3RGsVhszR6qu3L",
        "/ip4/192.53.121.124/tcp/1211/p2p/12D3KooWAV6uSjUWgVSaKhZ3g7oNL2iYcrqZY33Jh5mg1ASYWLkt",
        "/ip4/192.53.121.124/udp/1211/quic-v1/p2p/12D3KooWAV6uSjUWgVSaKhZ3g7oNL2iYcrqZY33Jh5mg1ASYWLkt",
        "/ip6/2600:3c04::f03c:94ff:fe7d:60db/tcp/1211/p2p/12D3KooWAV6uSjUWgVSaKhZ3g7oNL2iYcrqZY33Jh5mg1ASYWLkt",
        "/ip6/2600:3c04::f03c:94ff:fe7d:60db/udp/1211/quic-v1/p2p/12D3KooWAV6uSjUWgVSaKhZ3g7oNL2iYcrqZY33Jh5mg1ASYWLkt",
        "/ip6/2600:3c0d::f03c:94ff:fe7d:6074/udp/1211/quic-v1/p2p/12D3KooWHCwpHvH4cbHcQJSrcnVvcNQYKFUommSLwgQvyNKkh4zC",
        "/ip4/172.233.14.75/tcp/1211/p2p/12D3KooWHCwpHvH4cbHcQJSrcnVvcNQYKFUommSLwgQvyNKkh4zC",
        "/ip4/172.233.14.75/udp/1211/quic-v1/p2p/12D3KooWHCwpHvH4cbHcQJSrcnVvcNQYKFUommSLwgQvyNKkh4zC",
        "/ip6/2600:3c0d::f03c:94ff:fe7d:6074/tcp/1211/p2p/12D3KooWHCwpHvH4cbHcQJSrcnVvcNQYKFUommSLwgQvyNKkh4zC",
        "/ip6/2400:8907::f03c:94ff:fe7d:606e/udp/1211/quic-v1/p2p/12D3KooWQN4nm95h6S2yBor8MRMN4Lh8nxzbZdCZd7PZjCGoUEx6",
        "/ip4/194.195.248.34/tcp/1211/p2p/12D3KooWQN4nm95h6S2yBor8MRMN4Lh8nxzbZdCZd7PZjCGoUEx6",
        "/ip4/194.195.248.34/udp/1211/quic-v1/p2p/12D3KooWQN4nm95h6S2yBor8MRMN4Lh8nxzbZdCZd7PZjCGoUEx6",
        "/ip6/2400:8907::f03c:94ff:fe7d:606e/tcp/1211/p2p/12D3KooWQN4nm95h6S2yBor8MRMN4Lh8nxzbZdCZd7PZjCGoUEx6",
        "/ip4/176.58.113.16/tcp/1211/p2p/12D3KooWGf6CcF7WvRJxoDdDwEgnEbyyhDRLcxtosHZ3PMwuza6Y",
        "/ip4/176.58.113.16/udp/1211/quic-v1/p2p/12D3KooWGf6CcF7WvRJxoDdDwEgnEbyyhDRLcxtosHZ3PMwuza6Y",
        "/ip6/2a01:7e00::f03c:94ff:fe7d:60a4/tcp/1211/p2p/12D3KooWGf6CcF7WvRJxoDdDwEgnEbyyhDRLcxtosHZ3PMwuza6Y",
        "/ip6/2a01:7e00::f03c:94ff:fe7d:60a4/udp/1211/quic-v1/p2p/12D3KooWGf6CcF7WvRJxoDdDwEgnEbyyhDRLcxtosHZ3PMwuza6Y",
        "/ip4/45.79.137.197/tcp/1211/p2p/12D3KooWPNjy83Yi4eerqVhRbmv32856cTbUxd6r2N1hzsY6cCeW",
        "/ip4/45.79.137.197/udp/1211/quic-v1/p2p/12D3KooWPNjy83Yi4eerqVhRbmv32856cTbUxd6r2N1hzsY6cCeW",
        "/ip6/2600:3c03::f03c:94ff:fe7d:60c1/tcp/1211/p2p/12D3KooWPNjy83Yi4eerqVhRbmv32856cTbUxd6r2N1hzsY6cCeW",
        "/ip6/2600:3c03::f03c:94ff:fe7d:60c1/udp/1211/quic-v1/p2p/12D3KooWPNjy83Yi4eerqVhRbmv32856cTbUxd6r2N1hzsY6cCeW",
        "/ip4/192.53.115.228/tcp/1211/p2p/12D3KooWNUDY828t1pNoMAQkrWWicX8QvJTmWYophSX9xfHcvBs1",
        "/ip4/192.53.115.228/udp/1211/quic-v1/p2p/12D3KooWNUDY828t1pNoMAQkrWWicX8QvJTmWYophSX9xfHcvBs1",
        "/ip6/2400:8901::f03c:94ff:fe7d:605e/tcp/1211/p2p/12D3KooWNUDY828t1pNoMAQkrWWicX8QvJTmWYophSX9xfHcvBs1",
        "/ip6/2400:8901::f03c:94ff:fe7d:605e/udp/1211/quic-v1/p2p/12D3KooWNUDY828t1pNoMAQkrWWicX8QvJTmWYophSX9xfHcvBs1",
        "/ip4/172.236.64.61/tcp/1211/p2p/12D3KooWMN4NrFhYSGRrXhZx3KFpdFZr2NDAU67rteRSK9QS1656",
        "/ip4/172.236.64.61/udp/1211/quic-v1/p2p/12D3KooWMN4NrFhYSGRrXhZx3KFpdFZr2NDAU67rteRSK9QS1656",
        "/ip6/2600:3c08::f03c:94ff:fe7d:6085/tcp/1211/p2p/12D3KooWMN4NrFhYSGRrXhZx3KFpdFZr2NDAU67rteRSK9QS1656",
        "/ip6/2600:3c08::f03c:94ff:fe7d:6085/udp/1211/quic-v1/p2p/12D3KooWMN4NrFhYSGRrXhZx3KFpdFZr2NDAU67rteRSK9QS1656",
        "/ip4/192.53.121.104/tcp/1211/p2p/12D3KooWGkjynXAsBLSA5MUFfTjZGEY3V1exj7NdsD7YsWhBnMji",
        "/ip4/192.53.121.104/udp/1211/quic-v1/p2p/12D3KooWGkjynXAsBLSA5MUFfTjZGEY3V1exj7NdsD7YsWhBnMji",
        "/ip6/2600:3c04::f03c:94ff:fe7d:6052/tcp/1211/p2p/12D3KooWGkjynXAsBLSA5MUFfTjZGEY3V1exj7NdsD7YsWhBnMji",
        "/ip6/2600:3c04::f03c:94ff:fe7d:6052/udp/1211/quic-v1/p2p/12D3KooWGkjynXAsBLSA5MUFfTjZGEY3V1exj7NdsD7YsWhBnMji",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB