windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c04::f03c:94ff:feb7:b4cc/tcp/1211/p2p/12D3KooWLXhcnGChfMDb19cGCWWD98tYhcLDrGrJ7uftz2jJpZmH",
        "/ip6/2600:3c04::f03c:94ff:feb7:b4cc/udp/1211/quic-v1/p2p/12D3KooWLXhcnGChfMDb19cGCWWD98tYhcLDrGrJ7uftz2jJpZmH",
        "/ip4/172.105.6.6/tcp/1211/p2p/12D3KooWLXhcnGChfMDb19cGCWWD98tYhcLDrGrJ7uftz2jJpZmH",
        "/ip4/172.105.6.6/udp/1211/quic-v1/p2p/12D3KooWLXhcnGChfMDb19cGCWWD98tYhcLDrGrJ7uftz2jJpZmH",
        "/ip4/172.104.160.116/tcp/1211/p2p/12D3KooWBiWXBmtkXEPJZdEnzms8uLuYkSdFDMAE9JDySBzjxCNe",
        "/ip4/172.104.160.116/udp/1211/quic-v1/p2p/12D3KooWBiWXBmtkXEPJZdEnzms8uLuYkSdFDMAE9JDySBzjxCNe",
        "/ip6/2400:8901::f03c:94ff:feb7:b439/tcp/1211/p2p/12D3KooWBiWXBmtkXEPJZdEnzms8uLuYkSdFDMAE9JDySBzjxCNe",
        "/ip6/2400:8901::f03c:94ff:feb7:b439/udp/1211/quic-v1/p2p/12D3KooWBiWXBmtkXEPJZdEnzms8uLuYkSdFDMAE9JDySBzjxCNe",
        "/ip6/2a01:7e04::f03c:94ff:feb7:b447/tcp/1211/p2p/12D3KooWFWDasxDUxjfykdAUa2ZMrKxgQB7xdhzDLeh5QqgJp14x",
        "/ip6/2a01:7e04::f03c:94ff:feb7:b447/udp/1211/quic-v1/p2p/12D3KooWFWDasxDUxjfykdAUa2ZMrKxgQB7xdhzDLeh5QqgJp14x",
        "/ip4/172.235.133.214/tcp/1211/p2p/12D3KooWFWDasxDUxjfykdAUa2ZMrKxgQB7xdhzDLeh5QqgJp14x",
        "/ip4/172.235.133.214/udp/1211/quic-v1/p2p/12D3KooWFWDasxDUxjfykdAUa2ZMrKxgQB7xdhzDLeh5QqgJp14x",
        "/ip6/2600:3c03::f03c:94ff:feb7:b4bd/tcp/1211/p2p/12D3KooWGVEa8y4VkCVMAQDbaVG7Jz5kLB1bi5sgK4JEQ5sJLBEd",
        "/ip6/2600:3c03::f03c:94ff:feb7:b4bd/udp/1211/quic-v1/p2p/12D3KooWGVEa8y4VkCVMAQDbaVG7Jz5kLB1bi5sgK4JEQ5sJLBEd",
        "/ip4/192.155.89.171/tcp/1211/p2p/12D3KooWGVEa8y4VkCVMAQDbaVG7Jz5kLB1bi5sgK4JEQ5sJLBEd",
        "/ip4/192.155.89.171/udp/1211/quic-v1/p2p/12D3KooWGVEa8y4VkCVMAQDbaVG7Jz5kLB1bi5sgK4JEQ5sJLBEd",
        "/ip4/172.236.72.113/tcp/1211/p2p/12D3KooWKVKMCN8EsXzXXtTjenDFhYuW2EhddjLgXrDimnfQFYBC",
        "/ip4/172.236.72.113/udp/1211/quic-v1/p2p/12D3KooWKVKMCN8EsXzXXtTjenDFhYuW2EhddjLgXrDimnfQFYBC",
        "/ip6/2600:3c08::f03c:94ff:feb7:b40c/tcp/1211/p2p/12D3KooWKVKMCN8EsXzXXtTjenDFhYuW2EhddjLgXrDimnfQFYBC",
        "/ip6/2600:3c08::f03c:94ff:feb7:b40c/udp/1211/quic-v1/p2p/12D3KooWKVKMCN8EsXzXXtTjenDFhYuW2EhddjLgXrDimnfQFYBC",
        "/ip4/172.234.85.41/tcp/1211/p2p/12D3KooWP8dUBSu1xFg5TzpznRkQCbtErwZQHBrXk8SX3RKWeN5R",
        "/ip4/172.234.85.41/udp/1211/quic-v1/p2p/12D3KooWP8dUBSu1xFg5TzpznRkQCbtErwZQHBrXk8SX3RKWeN5R",
        "/ip6/2400:8905::f03c:94ff:feb7:b425/tcp/1211/p2p/12D3KooWP8dUBSu1xFg5TzpznRkQCbtErwZQHBrXk8SX3RKWeN5R",
        "/ip6/2400:8905::f03c:94ff:feb7:b425/udp/1211/quic-v1/p2p/12D3KooWP8dUBSu1xFg5TzpznRkQCbtErwZQHBrXk8SX3RKWeN5R",
        "/ip4/176.58.119.138/tcp/1211/p2p/12D3KooWHLgcTrBgPnF6JRLpc3PHuv5fLjMRMqhaehTPcXKaETpr",
        "/ip4/176.58.119.138/udp/1211/quic-v1/p2p/12D3KooWHLgcTrBgPnF6JRLpc3PHuv5fLjMRMqhaehTPcXKaETpr",
        "/ip6/2a01:7e00::f03c:94ff:feb7:b49c/tcp/1211/p2p/12D3KooWHLgcTrBgPnF6JRLpc3PHuv5fLjMRMqhaehTPcXKaETpr",
        "/ip6/2a01:7e00::f03c:94ff:feb7:b49c/udp/1211/quic-v1/p2p/12D3KooWHLgcTrBgPnF6JRLpc3PHuv5fLjMRMqhaehTPcXKaETpr",
        "/ip4/139.162.168.39/tcp/1211/p2p/12D3KooWJpHK9KCwUqj5wYZ59oKrxhPF7T7apkMUiaECkHMW9cWg",
        "/ip4/139.162.168.39/udp/1211/quic-v1/p2p/12D3KooWJpHK9KCwUqj5wYZ59oKrxhPF7T7apkMUiaECkHMW9cWg",
        "/ip6/2a01:7e01::f03c:94ff:feb7:b4cd/tcp/1211/p2p/12D3KooWJpHK9KCwUqj5wYZ59oKrxhPF7T7apkMUiaECkHMW9cWg",
        "/ip6/2a01:7e01::f03c:94ff:feb7:b4cd/udp/1211/quic-v1/p2p/12D3KooWJpHK9KCwUqj5wYZ59oKrxhPF7T7apkMUiaECkHMW9cWg",
        "/ip4/198.58.111.228/tcp/1211/p2p/12D3KooWPEW9g2a7Q7wiYTPpfQWt5h93DsUErubev8gsyacqEVeB",
        "/ip4/198.58.111.228/udp/1211/quic-v1/p2p/12D3KooWPEW9g2a7Q7wiYTPpfQWt5h93DsUErubev8gsyacqEVeB",
        "/ip6/2600:3c00::f03c:94ff:feb7:b40f/tcp/1211/p2p/12D3KooWPEW9g2a7Q7wiYTPpfQWt5h93DsUErubev8gsyacqEVeB",
        "/ip6/2600:3c00::f03c:94ff:feb7:b40f/udp/1211/quic-v1/p2p/12D3KooWPEW9g2a7Q7wiYTPpfQWt5h93DsUErubev8gsyacqEVeB",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securachainDataPath: ".securachainData/"
blockRegistryPath: "blockRegistry.json"
fileRegistryPath: "fileRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB