windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.233.160.183/tcp/1211/p2p/12D3KooWBZyvPtgAsCWmZcoZjr8kUyUFodCmvg5djAF2Xp5NGEkg",
        "/ip4/172.233.160.183/udp/1211/quic-v1/p2p/12D3KooWBZyvPtgAsCWmZcoZjr8kUyUFodCmvg5djAF2Xp5NGEkg",
        "/ip6/2a01:7e04::f03c:94ff:fe62:5d72/tcp/1211/p2p/12D3KooWBZyvPtgAsCWmZcoZjr8kUyUFodCmvg5djAF2Xp5NGEkg",
        "/ip6/2a01:7e04::f03c:94ff:fe62:5d72/udp/1211/quic-v1/p2p/12D3KooWBZyvPtgAsCWmZcoZjr8kUyUFodCmvg5djAF2Xp5NGEkg",
        "/ip4/172.105.110.119/tcp/1211/p2p/12D3KooWJf8uvmHVCtTtAjPapTX9VLXhkECcMfV8jVDAZo4Qmi9L",
        "/ip4/172.105.110.119/udp/1211/quic-v1/p2p/12D3KooWJf8uvmHVCtTtAjPapTX9VLXhkECcMfV8jVDAZo4Qmi9L",
        "/ip6/2600:3c04::f03c:94ff:fe62:9c08/tcp/1211/p2p/12D3KooWJf8uvmHVCtTtAjPapTX9VLXhkECcMfV8jVDAZo4Qmi9L",
        "/ip6/2600:3c04::f03c:94ff:fe62:9c08/udp/1211/quic-v1/p2p/12D3KooWJf8uvmHVCtTtAjPapTX9VLXhkECcMfV8jVDAZo4Qmi9L",
        "/ip6/2a01:7e00::f03c:94ff:fe62:9c74/tcp/1211/p2p/12D3KooWKkDrmpCy1S8V3iYtbx2Z28p3zqTJtkxAqC4cVyoSGZ5S",
        "/ip6/2a01:7e00::f03c:94ff:fe62:9c74/udp/1211/quic-v1/p2p/12D3KooWKkDrmpCy1S8V3iYtbx2Z28p3zqTJtkxAqC4cVyoSGZ5S",
        "/ip4/139.162.245.108/tcp/1211/p2p/12D3KooWKkDrmpCy1S8V3iYtbx2Z28p3zqTJtkxAqC4cVyoSGZ5S",
        "/ip4/139.162.245.108/udp/1211/quic-v1/p2p/12D3KooWKkDrmpCy1S8V3iYtbx2Z28p3zqTJtkxAqC4cVyoSGZ5S",
        "/ip4/172.233.62.175/tcp/1211/p2p/12D3KooWPuRMftfbVVXWpSwEa81bDzoEf29tCgL9HHSwzkSLrPVV",
        "/ip4/172.233.62.175/udp/1211/quic-v1/p2p/12D3KooWPuRMftfbVVXWpSwEa81bDzoEf29tCgL9HHSwzkSLrPVV",
        "/ip6/2600:3c0e::f03c:94ff:fe62:9c90/tcp/1211/p2p/12D3KooWPuRMftfbVVXWpSwEa81bDzoEf29tCgL9HHSwzkSLrPVV",
        "/ip6/2600:3c0e::f03c:94ff:fe62:9c90/udp/1211/quic-v1/p2p/12D3KooWPuRMftfbVVXWpSwEa81bDzoEf29tCgL9HHSwzkSLrPVV",
        "/ip4/172.232.208.143/tcp/1211/p2p/12D3KooWSNDJD6dXMJm2tsbsqdWQniHv5wNUFEYz3XV6LgnXXtcN",
        "/ip4/172.232.208.143/udp/1211/quic-v1/p2p/12D3KooWSNDJD6dXMJm2tsbsqdWQniHv5wNUFEYz3XV6LgnXXtcN",
        "/ip6/2600:3c0b::f03c:94ff:fe62:9cbe/tcp/1211/p2p/12D3KooWSNDJD6dXMJm2tsbsqdWQniHv5wNUFEYz3XV6LgnXXtcN",
        "/ip6/2600:3c0b::f03c:94ff:fe62:9cbe/udp/1211/quic-v1/p2p/12D3KooWSNDJD6dXMJm2tsbsqdWQniHv5wNUFEYz3XV6LgnXXtcN",
        "/ip4/172.105.37.164/tcp/1211/p2p/12D3KooWGrRXd38qwVXu8Z4Auhg4E5hWsktdw6ihne69vCk6PqmS",
        "/ip4/172.105.37.164/udp/1211/quic-v1/p2p/12D3KooWGrRXd38qwVXu8Z4Auhg4E5hWsktdw6ihne69vCk6PqmS",
        "/ip6/2400:8904::f03c:94ff:fe62:5d88/tcp/1211/p2p/12D3KooWGrRXd38qwVXu8Z4Auhg4E5hWsktdw6ihne69vCk6PqmS",
        "/ip6/2400:8904::f03c:94ff:fe62:5d88/udp/1211/quic-v1/p2p/12D3KooWGrRXd38qwVXu8Z4Auhg4E5hWsktdw6ihne69vCk6PqmS",
        "/ip6/2a01:7e01::f03c:94ff:fe62:9c14/tcp/1211/p2p/12D3KooWHZaTEpZ9YMGmtp2m1cASHFoa3wWbEMzQZ2ojQgHe9jW2",
        "/ip6/2a01:7e01::f03c:94ff:fe62:9c14/udp/1211/quic-v1/p2p/12D3KooWHZaTEpZ9YMGmtp2m1cASHFoa3wWbEMzQZ2ojQgHe9jW2",
        "/ip4/139.162.146.38/tcp/1211/p2p/12D3KooWHZaTEpZ9YMGmtp2m1cASHFoa3wWbEMzQZ2ojQgHe9jW2",
        "/ip4/139.162.146.38/udp/1211/quic-v1/p2p/12D3KooWHZaTEpZ9YMGmtp2m1cASHFoa3wWbEMzQZ2ojQgHe9jW2",
        "/ip4/172.233.25.4/tcp/1211/p2p/12D3KooWCWhEESCZm8hQCjMcwyR2zoYuuoTaeCQsEpNPdD8yae8A",
        "/ip4/172.233.25.4/udp/1211/quic-v1/p2p/12D3KooWCWhEESCZm8hQCjMcwyR2zoYuuoTaeCQsEpNPdD8yae8A",
        "/ip6/2600:3c0d::f03c:94ff:fe62:9ce1/tcp/1211/p2p/12D3KooWCWhEESCZm8hQCjMcwyR2zoYuuoTaeCQsEpNPdD8yae8A",
        "/ip6/2600:3c0d::f03c:94ff:fe62:9ce1/udp/1211/quic-v1/p2p/12D3KooWCWhEESCZm8hQCjMcwyR2zoYuuoTaeCQsEpNPdD8yae8A",
        "/ip6/2600:3c04::f03c:94ff:fe62:9ce3/udp/1211/quic-v1/p2p/12D3KooWDfZNEUVbRF3Mn5a6w5G9jiXbKGtewnQrQMuE7m7ve5Vm",
        "/ip4/172.105.18.181/tcp/1211/p2p/12D3KooWDfZNEUVbRF3Mn5a6w5G9jiXbKGtewnQrQMuE7m7ve5Vm",
        "/ip4/172.105.18.181/udp/1211/quic-v1/p2p/12D3KooWDfZNEUVbRF3Mn5a6w5G9jiXbKGtewnQrQMuE7m7ve5Vm",
        "/ip6/2600:3c04::f03c:94ff:fe62:9ce3/tcp/1211/p2p/12D3KooWDfZNEUVbRF3Mn5a6w5G9jiXbKGtewnQrQMuE7m7ve5Vm",
        "/ip4/172.235.27.110/tcp/1211/p2p/12D3KooWHJHmrSjeEzHfNtbpUM3FytYKCKwd5izMAZZ7tqbNgUxq",
        "/ip4/172.235.27.110/udp/1211/quic-v1/p2p/12D3KooWHJHmrSjeEzHfNtbpUM3FytYKCKwd5izMAZZ7tqbNgUxq",
        "/ip6/2600:3c08::f03c:94ff:fe62:9c4e/tcp/1211/p2p/12D3KooWHJHmrSjeEzHfNtbpUM3FytYKCKwd5izMAZZ7tqbNgUxq",
        "/ip6/2600:3c08::f03c:94ff:fe62:9c4e/udp/1211/quic-v1/p2p/12D3KooWHJHmrSjeEzHfNtbpUM3FytYKCKwd5izMAZZ7tqbNgUxq",
        "/ip6/2600:3c03::f03c:94ff:fe62:9c8e/udp/1211/quic-v1/p2p/12D3KooWQFsNLLjeyVJuXPdXVwkpDRFjBEtkCBpNiB55G6AGgmiW",
        "/ip4/172.104.13.213/tcp/1211/p2p/12D3KooWQFsNLLjeyVJuXPdXVwkpDRFjBEtkCBpNiB55G6AGgmiW",
        "/ip4/172.104.13.213/udp/1211/quic-v1/p2p/12D3KooWQFsNLLjeyVJuXPdXVwkpDRFjBEtkCBpNiB55G6AGgmiW",
        "/ip6/2600:3c03::f03c:94ff:fe62:9c8e/tcp/1211/p2p/12D3KooWQFsNLLjeyVJuXPdXVwkpDRFjBEtkCBpNiB55G6AGgmiW",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB