windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/139.162.255.105/tcp/1211/p2p/12D3KooWLkZXjXK1AWnsgVrGKnx2GFrQRkjwRVBAv1YmGtQLTcvE",
        "/ip4/139.162.255.105/udp/1211/quic-v1/p2p/12D3KooWLkZXjXK1AWnsgVrGKnx2GFrQRkjwRVBAv1YmGtQLTcvE",
        "/ip6/2a01:7e00::f03c:94ff:fe30:988a/tcp/1211/p2p/12D3KooWLkZXjXK1AWnsgVrGKnx2GFrQRkjwRVBAv1YmGtQLTcvE",
        "/ip6/2a01:7e00::f03c:94ff:fe30:988a/udp/1211/quic-v1/p2p/12D3KooWLkZXjXK1AWnsgVrGKnx2GFrQRkjwRVBAv1YmGtQLTcvE",
        "/ip4/45.79.171.104/udp/1211/quic-v1/p2p/12D3KooWGr5UPSQy1pyvjSfJhpe3Ed2QgrrdNYeAnzkAMKo8U8jd",
        "/ip6/2600:3c03::f03c:94ff:fe30:2472/tcp/1211/p2p/12D3KooWGr5UPSQy1pyvjSfJhpe3Ed2QgrrdNYeAnzkAMKo8U8jd",
        "/ip6/2600:3c03::f03c:94ff:fe30:2472/udp/1211/quic-v1/p2p/12D3KooWGr5UPSQy1pyvjSfJhpe3Ed2QgrrdNYeAnzkAMKo8U8jd",
        "/ip4/45.79.171.104/tcp/1211/p2p/12D3KooWGr5UPSQy1pyvjSfJhpe3Ed2QgrrdNYeAnzkAMKo8U8jd",
        "/ip4/172.235.141.175/tcp/1211/p2p/12D3KooWRztqAC8dJPMFdfTaKM2M4CynCubjikZvdWViSaB8sQa7",
        "/ip4/172.235.141.175/udp/1211/quic-v1/p2p/12D3KooWRztqAC8dJPMFdfTaKM2M4CynCubjikZvdWViSaB8sQa7",
        "/ip6/2a01:7e04::f03c:94ff:fe30:9848/tcp/1211/p2p/12D3KooWRztqAC8dJPMFdfTaKM2M4CynCubjikZvdWViSaB8sQa7",
        "/ip6/2a01:7e04::f03c:94ff:fe30:9848/udp/1211/quic-v1/p2p/12D3KooWRztqAC8dJPMFdfTaKM2M4CynCubjikZvdWViSaB8sQa7",
        "/ip6/2600:3c0e::f03c:94ff:fe30:9844/udp/1211/quic-v1/p2p/12D3KooWDq8QBsrNKjLUf2RP8XdyK73YSmjcSaVf7vUoXLs9hE6B",
        "/ip4/172.233.38.192/tcp/1211/p2p/12D3KooWDq8QBsrNKjLUf2RP8XdyK73YSmjcSaVf7vUoXLs9hE6B",
        "/ip4/172.233.38.192/udp/1211/quic-v1/p2p/12D3KooWDq8QBsrNKjLUf2RP8XdyK73YSmjcSaVf7vUoXLs9hE6B",
        "/ip6/2600:3c0e::f03c:94ff:fe30:9844/tcp/1211/p2p/12D3KooWDq8QBsrNKjLUf2RP8XdyK73YSmjcSaVf7vUoXLs9hE6B",
        "/ip4/172.233.28.53/tcp/1211/p2p/12D3KooWHq1EAs1gkQMd6wdNzo9H9bNs5oCFbUpEcQwaSCh8o3hf",
        "/ip4/172.233.28.53/udp/1211/quic-v1/p2p/12D3KooWHq1EAs1gkQMd6wdNzo9H9bNs5oCFbUpEcQwaSCh8o3hf",
        "/ip6/2600:3c0d::f03c:94ff:fe30:ceea/tcp/1211/p2p/12D3KooWHq1EAs1gkQMd6wdNzo9H9bNs5oCFbUpEcQwaSCh8o3hf",
        "/ip6/2600:3c0d::f03c:94ff:fe30:ceea/udp/1211/quic-v1/p2p/12D3KooWHq1EAs1gkQMd6wdNzo9H9bNs5oCFbUpEcQwaSCh8o3hf",
        "/ip4/45.79.171.138/tcp/1211/p2p/12D3KooWBxo9uB1gtp2swoEQzKVSmVXna31QChzUwWtZJUja8Lzd",
        "/ip4/45.79.171.138/udp/1211/quic-v1/p2p/12D3KooWBxo9uB1gtp2swoEQzKVSmVXna31QChzUwWtZJUja8Lzd",
        "/ip6/2600:3c03::f03c:94ff:fe30:24c5/tcp/1211/p2p/12D3KooWBxo9uB1gtp2swoEQzKVSmVXna31QChzUwWtZJUja8Lzd",
        "/ip6/2600:3c03::f03c:94ff:fe30:24c5/udp/1211/quic-v1/p2p/12D3KooWBxo9uB1gtp2swoEQzKVSmVXna31QChzUwWtZJUja8Lzd",
        "/ip4/194.195.125.27/tcp/1211/p2p/12D3KooWKQzAEPSFnNzQsGXLKYzckmCfxYALKxM3NZs8HkQkVmWt",
        "/ip4/194.195.125.27/udp/1211/quic-v1/p2p/12D3KooWKQzAEPSFnNzQsGXLKYzckmCfxYALKxM3NZs8HkQkVmWt",
        "/ip6/2400:8907::f03c:94ff:fe30:e5fe/tcp/1211/p2p/12D3KooWKQzAEPSFnNzQsGXLKYzckmCfxYALKxM3NZs8HkQkVmWt",
        "/ip6/2400:8907::f03c:94ff:fe30:e5fe/udp/1211/quic-v1/p2p/12D3KooWKQzAEPSFnNzQsGXLKYzckmCfxYALKxM3NZs8HkQkVmWt",
        "/ip4/172.233.50.60/tcp/1211/p2p/12D3KooWMxFQKc5Xc7jMUKWkvT5rD8vS5TCdHrDcXizJTS4xLA1f",
        "/ip4/172.233.50.60/udp/1211/quic-v1/p2p/12D3KooWMxFQKc5Xc7jMUKWkvT5rD8vS5TCdHrDcXizJTS4xLA1f",
        "/ip6/2600:3c0e::f03c:94ff:fe30:cea5/tcp/1211/p2p/12D3KooWMxFQKc5Xc7jMUKWkvT5rD8vS5TCdHrDcXizJTS4xLA1f",
        "/ip6/2600:3c0e::f03c:94ff:fe30:cea5/udp/1211/quic-v1/p2p/12D3KooWMxFQKc5Xc7jMUKWkvT5rD8vS5TCdHrDcXizJTS4xLA1f",
        "/ip4/139.162.187.175/tcp/1211/p2p/12D3KooWJqgSkuoNetNqNtWFQNBt8kgThZHJHMbTLWEKdo7tGhWP",
        "/ip4/139.162.187.175/udp/1211/quic-v1/p2p/12D3KooWJqgSkuoNetNqNtWFQNBt8kgThZHJHMbTLWEKdo7tGhWP",
        "/ip6/2a01:7e01::f03c:94ff:fe30:6254/tcp/1211/p2p/12D3KooWJqgSkuoNetNqNtWFQNBt8kgThZHJHMbTLWEKdo7tGhWP",
        "/ip6/2a01:7e01::f03c:94ff:fe30:6254/udp/1211/quic-v1/p2p/12D3KooWJqgSkuoNetNqNtWFQNBt8kgThZHJHMbTLWEKdo7tGhWP",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB