windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/45.79.137.197/tcp/1211/p2p/12D3KooWNeDcL92dh2386jQ4bBm8UFmT1fBnvQF88nSDencLz4Qv",
        "/ip4/45.79.137.197/udp/1211/quic-v1/p2p/12D3KooWNeDcL92dh2386jQ4bBm8UFmT1fBnvQF88nSDencLz4Qv",
        "/ip6/2600:3c03::f03c:94ff:fe0b:7f6d/tcp/1211/p2p/12D3KooWNeDcL92dh2386jQ4bBm8UFmT1fBnvQF88nSDencLz4Qv",
        "/ip6/2600:3c03::f03c:94ff:fe0b:7f6d/udp/1211/quic-v1/p2p/12D3KooWNeDcL92dh2386jQ4bBm8UFmT1fBnvQF88nSDencLz4Qv",
        "/ip6/2600:3c0d::f03c:94ff:fe0b:5607/udp/1211/quic-v1/p2p/12D3KooWPgxtremCTLMmciCMvneiUpMxfEtSVwwnGHR45yrYMyBp",
        "/ip4/172.233.17.160/tcp/1211/p2p/12D3KooWPgxtremCTLMmciCMvneiUpMxfEtSVwwnGHR45yrYMyBp",
        "/ip4/172.233.17.160/udp/1211/quic-v1/p2p/12D3KooWPgxtremCTLMmciCMvneiUpMxfEtSVwwnGHR45yrYMyBp",
        "/ip6/2600:3c0d::f03c:94ff:fe0b:5607/tcp/1211/p2p/12D3KooWPgxtremCTLMmciCMvneiUpMxfEtSVwwnGHR45yrYMyBp",
        "/ip4/192.53.115.228/tcp/1211/p2p/12D3KooWHpiRyzmnYaVssL9WKDbLUSX7LQTGRfakMYXHi1nq9B4x",
        "/ip4/192.53.115.228/udp/1211/quic-v1/p2p/12D3KooWHpiRyzmnYaVssL9WKDbLUSX7LQTGRfakMYXHi1nq9B4x",
        "/ip6/2400:8901::f03c:94ff:fe0b:7f8e/tcp/1211/p2p/12D3KooWHpiRyzmnYaVssL9WKDbLUSX7LQTGRfakMYXHi1nq9B4x",
        "/ip6/2400:8901::f03c:94ff:fe0b:7f8e/udp/1211/quic-v1/p2p/12D3KooWHpiRyzmnYaVssL9WKDbLUSX7LQTGRfakMYXHi1nq9B4x",
        "/ip4/172.105.17.232/tcp/1211/p2p/12D3KooWE3jUkEAJP7uSzJ5PGTb3xMP3jcAizc2UdpKXtZzCrgkD",
        "/ip4/172.105.17.232/udp/1211/quic-v1/p2p/12D3KooWE3jUkEAJP7uSzJ5PGTb3xMP3jcAizc2UdpKXtZzCrgkD",
        "/ip6/2600:3c04::f03c:94ff:fe0b:5691/tcp/1211/p2p/12D3KooWE3jUkEAJP7uSzJ5PGTb3xMP3jcAizc2UdpKXtZzCrgkD",
        "/ip6/2600:3c04::f03c:94ff:fe0b:5691/udp/1211/quic-v1/p2p/12D3KooWE3jUkEAJP7uSzJ5PGTb3xMP3jcAizc2UdpKXtZzCrgkD",
        "/ip4/45.79.237.88/tcp/1211/p2p/12D3KooWQgCiNbAKT2Bq6sX9QCpqFQmrsmW7MkqvmLZB3FLV3GFw",
        "/ip4/45.79.237.88/udp/1211/quic-v1/p2p/12D3KooWQgCiNbAKT2Bq6sX9QCpqFQmrsmW7MkqvmLZB3FLV3GFw",
        "/ip6/2400:8907::f03c:94ff:fe0b:7fe8/tcp/1211/p2p/12D3KooWQgCiNbAKT2Bq6sX9QCpqFQmrsmW7MkqvmLZB3FLV3GFw",
        "/ip6/2400:8907::f03c:94ff:fe0b:7fe8/udp/1211/quic-v1/p2p/12D3KooWQgCiNbAKT2Bq6sX9QCpqFQmrsmW7MkqvmLZB3FLV3GFw",
        "/ip4/45.79.172.28/tcp/1211/p2p/12D3KooWDGqJSjqCiwvZKaxf4RDWUjKy8UixSFGc3poVF64o4fsC",
        "/ip4/45.79.172.28/udp/1211/quic-v1/p2p/12D3KooWDGqJSjqCiwvZKaxf4RDWUjKy8UixSFGc3poVF64o4fsC",
        "/ip6/2600:3c03::f03c:94ff:fe0b:568b/tcp/1211/p2p/12D3KooWDGqJSjqCiwvZKaxf4RDWUjKy8UixSFGc3poVF64o4fsC",
        "/ip6/2600:3c03::f03c:94ff:fe0b:568b/udp/1211/quic-v1/p2p/12D3KooWDGqJSjqCiwvZKaxf4RDWUjKy8UixSFGc3poVF64o4fsC",
        "/ip4/172.233.110.137/tcp/1211/p2p/12D3KooWPVA3pBXNExajET7PCZTjNGS9eJFqiZWBfMqzjUdQm6zS",
        "/ip4/172.233.110.137/udp/1211/quic-v1/p2p/12D3KooWPVA3pBXNExajET7PCZTjNGS9eJFqiZWBfMqzjUdQm6zS",
        "/ip6/2a01:7e02::f03c:94ff:fe0b:7ffd/tcp/1211/p2p/12D3KooWPVA3pBXNExajET7PCZTjNGS9eJFqiZWBfMqzjUdQm6zS",
        "/ip6/2a01:7e02::f03c:94ff:fe0b:7ffd/udp/1211/quic-v1/p2p/12D3KooWPVA3pBXNExajET7PCZTjNGS9eJFqiZWBfMqzjUdQm6zS",
        "/ip4/172.232.121.153/tcp/1211/p2p/12D3KooWASydYCHtKAW6ry5ioywbYwL3rF5XVZcdJV2GCkvi694o",
        "/ip4/172.232.121.153/udp/1211/quic-v1/p2p/12D3KooWASydYCHtKAW6ry5ioywbYwL3rF5XVZcdJV2GCkvi694o",
        "/ip6/2600:3c08::f03c:94ff:fe0b:56e5/tcp/1211/p2p/12D3KooWASydYCHtKAW6ry5ioywbYwL3rF5XVZcdJV2GCkvi694o",
        "/ip6/2600:3c08::f03c:94ff:fe0b:56e5/udp/1211/quic-v1/p2p/12D3KooWASydYCHtKAW6ry5ioywbYwL3rF5XVZcdJV2GCkvi694o",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB