# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: true
  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
  go: '1.21.3'

# linters configuration options
linters:
# Enable all available linters.
  # Default: false
  enable-all: true
  disable:
    - nosnakecase
    - exhaustivestruct
    - deadcode
    - structcheck
    - golint
    - maligned
    - varcheck
    - ifshort
    - interfacer
    - scopelint