windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
  # "/ip4/13.37.148.174/tcp/1212/p2p/12D3KooWRWobba8bZYeUX2cCKMzvWzkRBG2h5yTZaGzutAH8Sjrx", # bootstrap node test
  # "/ip4/13.37.148.174/udp/1212/quic-v1/p2p/12D3KooWRWobba8bZYeUX2cCKMzvWzkRBG2h5yTZaGzutAH8Sjrx", # bootstrap node test
  # "/ip4/13.37.148.174/tcp/1211/p2p/12D3KooWMX4fAauTifC6fuDTWymjPTVkAuYsw3Ksc2DUoQdtwsEd",
	# "/ip4/13.37.148.174/udp/1211/quic-v1/p2p/12D3KooWMX4fAauTifC6fuDTWymjPTVkAuYsw3Ksc2DUoQdtwsEd",
	# "/ip4/154.56.63.167/tcp/1211/p2p/12D3KooWLRxRgyy5KAHWbU5LSPdYsMnZz5ArbtkLG72bdanEgFsK",
	# "/ip4/154.56.63.167/udp/1211/quic-v1/p2p/12D3KooWLRxRgyy5KAHWbU5LSPdYsMnZz5ArbtkLG72bdanEgFsK",
  "/ip4/172.232.44.124/tcp/36955/p2p/12D3KooWFoeiNVjF3qCCgfvo4qyzBNVv99AGKomsrpFaeDYTUvo8",
  "/ip4/172.232.44.124/udp/39347/quic-v1/p2p/12D3KooWFoeiNVjF3qCCgfvo4qyzBNVv99AGKomsrpFaeDYTUvo8",
  "/ip6/2600:3c07::f03c:94ff:fecc:aee6/tcp/42973/p2p/12D3KooWFoeiNVjF3qCCgfvo4qyzBNVv99AGKomsrpFaeDYTUvo8",
  "/ip6/2600:3c07::f03c:94ff:fecc:aee6/udp/38805/quic-v1/p2p/12D3KooWFoeiNVjF3qCCgfvo4qyzBNVv99AGKomsrpFaeDYTUvo8",
]
listeningPort: 0
discoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB