windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c03::f03c:94ff:fea6:7d7a/tcp/1211/p2p/12D3KooWMZqkm13KViPZqytTRVh9oksLyEz8WrK9SPop6u2YLW6Y",
        "/ip6/2600:3c03::f03c:94ff:fea6:7d7a/udp/1211/quic-v1/p2p/12D3KooWMZqkm13KViPZqytTRVh9oksLyEz8WrK9SPop6u2YLW6Y",
        "/ip4/45.79.143.237/tcp/1211/p2p/12D3KooWMZqkm13KViPZqytTRVh9oksLyEz8WrK9SPop6u2YLW6Y",
        "/ip4/45.79.143.237/udp/1211/quic-v1/p2p/12D3KooWMZqkm13KViPZqytTRVh9oksLyEz8WrK9SPop6u2YLW6Y",
        "/ip6/2600:3c0e::f03c:94ff:fea6:7dfd/tcp/1211/p2p/12D3KooWBDw9dDsumu2mmFwaZUniD9ucwiL6AijbW5Jp1tCZWnxb",
        "/ip6/2600:3c0e::f03c:94ff:fea6:7dfd/udp/1211/quic-v1/p2p/12D3KooWBDw9dDsumu2mmFwaZUniD9ucwiL6AijbW5Jp1tCZWnxb",
        "/ip4/172.233.38.20/tcp/1211/p2p/12D3KooWBDw9dDsumu2mmFwaZUniD9ucwiL6AijbW5Jp1tCZWnxb",
        "/ip4/172.233.38.20/udp/1211/quic-v1/p2p/12D3KooWBDw9dDsumu2mmFwaZUniD9ucwiL6AijbW5Jp1tCZWnxb",
        "/ip4/139.162.138.18/udp/1211/quic-v1/p2p/12D3KooWCP4g2iuBDgyaGpFZBu9S1xVQwgJ9bMyDcuu7cQFF61jj",
        "/ip6/2a01:7e01::f03c:94ff:fea6:7d79/tcp/1211/p2p/12D3KooWCP4g2iuBDgyaGpFZBu9S1xVQwgJ9bMyDcuu7cQFF61jj",
        "/ip6/2a01:7e01::f03c:94ff:fea6:7d79/udp/1211/quic-v1/p2p/12D3KooWCP4g2iuBDgyaGpFZBu9S1xVQwgJ9bMyDcuu7cQFF61jj",
        "/ip4/139.162.138.18/tcp/1211/p2p/12D3KooWCP4g2iuBDgyaGpFZBu9S1xVQwgJ9bMyDcuu7cQFF61jj",
        "/ip6/2a01:7e04::f03c:94ff:fea6:7d49/tcp/1211/p2p/12D3KooWNiEcFEgpJDhgyDbCMn1vvP4YdoqBcHshbtvAiazbeg3e",
        "/ip6/2a01:7e04::f03c:94ff:fea6:7d49/udp/1211/quic-v1/p2p/12D3KooWNiEcFEgpJDhgyDbCMn1vvP4YdoqBcHshbtvAiazbeg3e",
        "/ip4/172.233.181.16/tcp/1211/p2p/12D3KooWNiEcFEgpJDhgyDbCMn1vvP4YdoqBcHshbtvAiazbeg3e",
        "/ip4/172.233.181.16/udp/1211/quic-v1/p2p/12D3KooWNiEcFEgpJDhgyDbCMn1vvP4YdoqBcHshbtvAiazbeg3e",
        "/ip6/2400:8904::f03c:94ff:fea6:30ef/tcp/1211/p2p/12D3KooWDYqVhdnF1iLSdDC3QdhJAaXxaMzraVtJmGkPzeFhK6sh",
        "/ip6/2400:8904::f03c:94ff:fea6:30ef/udp/1211/quic-v1/p2p/12D3KooWDYqVhdnF1iLSdDC3QdhJAaXxaMzraVtJmGkPzeFhK6sh",
        "/ip4/172.105.49.133/tcp/1211/p2p/12D3KooWDYqVhdnF1iLSdDC3QdhJAaXxaMzraVtJmGkPzeFhK6sh",
        "/ip4/172.105.49.133/udp/1211/quic-v1/p2p/12D3KooWDYqVhdnF1iLSdDC3QdhJAaXxaMzraVtJmGkPzeFhK6sh",
        "/ip6/2a01:7e04::f03c:94ff:fea6:7d66/udp/1211/quic-v1/p2p/12D3KooWEkMEFUU4DNxvxyyyiYKYywPrwH8uqv94ieBJSau3FBCK",
        "/ip4/172.233.174.12/tcp/1211/p2p/12D3KooWEkMEFUU4DNxvxyyyiYKYywPrwH8uqv94ieBJSau3FBCK",
        "/ip4/172.233.174.12/udp/1211/quic-v1/p2p/12D3KooWEkMEFUU4DNxvxyyyiYKYywPrwH8uqv94ieBJSau3FBCK",
        "/ip6/2a01:7e04::f03c:94ff:fea6:7d66/tcp/1211/p2p/12D3KooWEkMEFUU4DNxvxyyyiYKYywPrwH8uqv94ieBJSau3FBCK",
        "/ip4/45.33.1.36/tcp/1211/p2p/12D3KooWPfTGUoGsekZ4GM3TZe6VWAfSDLEHAyEAjhQf1WEBGrrZ",
        "/ip4/45.33.1.36/udp/1211/quic-v1/p2p/12D3KooWPfTGUoGsekZ4GM3TZe6VWAfSDLEHAyEAjhQf1WEBGrrZ",
        "/ip6/2600:3c00::f03c:94ff:fea6:7d20/tcp/1211/p2p/12D3KooWPfTGUoGsekZ4GM3TZe6VWAfSDLEHAyEAjhQf1WEBGrrZ",
        "/ip6/2600:3c00::f03c:94ff:fea6:7d20/udp/1211/quic-v1/p2p/12D3KooWPfTGUoGsekZ4GM3TZe6VWAfSDLEHAyEAjhQf1WEBGrrZ",
        "/ip6/2600:3c04::f03c:94ff:fea6:3025/tcp/1211/p2p/12D3KooWR2LNavBnwUte9QNwENaox3itLr1efyZvPz5WbFi6J177",
        "/ip6/2600:3c04::f03c:94ff:fea6:3025/udp/1211/quic-v1/p2p/12D3KooWR2LNavBnwUte9QNwENaox3itLr1efyZvPz5WbFi6J177",
        "/ip4/172.105.8.7/tcp/1211/p2p/12D3KooWR2LNavBnwUte9QNwENaox3itLr1efyZvPz5WbFi6J177",
        "/ip4/172.105.8.7/udp/1211/quic-v1/p2p/12D3KooWR2LNavBnwUte9QNwENaox3itLr1efyZvPz5WbFi6J177",
        "/ip4/172.234.90.210/udp/1211/quic-v1/p2p/12D3KooWFymye2t2gWC1Ce6zmGagAufiTPmH8ZSxjJGb8hg9bc9o",
        "/ip6/2400:8905::f03c:94ff:fea6:307c/tcp/1211/p2p/12D3KooWFymye2t2gWC1Ce6zmGagAufiTPmH8ZSxjJGb8hg9bc9o",
        "/ip6/2400:8905::f03c:94ff:fea6:307c/udp/1211/quic-v1/p2p/12D3KooWFymye2t2gWC1Ce6zmGagAufiTPmH8ZSxjJGb8hg9bc9o",
        "/ip4/172.234.90.210/tcp/1211/p2p/12D3KooWFymye2t2gWC1Ce6zmGagAufiTPmH8ZSxjJGb8hg9bc9o",
        "/ip6/2600:3c00::f03c:94ff:fea6:3012/tcp/1211/p2p/12D3KooWAoUkxNkKdrxBJnP4yW4nR3kPxen3v5sr33jUM3pg1uvV",
        "/ip6/2600:3c00::f03c:94ff:fea6:3012/udp/1211/quic-v1/p2p/12D3KooWAoUkxNkKdrxBJnP4yW4nR3kPxen3v5sr33jUM3pg1uvV",
        "/ip4/198.58.113.139/tcp/1211/p2p/12D3KooWAoUkxNkKdrxBJnP4yW4nR3kPxen3v5sr33jUM3pg1uvV",
        "/ip4/198.58.113.139/udp/1211/quic-v1/p2p/12D3KooWAoUkxNkKdrxBJnP4yW4nR3kPxen3v5sr33jUM3pg1uvV",
        "/ip6/2600:3c03::f03c:94ff:fea6:30d2/udp/1211/quic-v1/p2p/12D3KooWL4Y91NuCxWVmjh9TNpFVLBA1qMSefxji7TwT1PDj8H48",
        "/ip4/45.79.189.79/tcp/1211/p2p/12D3KooWL4Y91NuCxWVmjh9TNpFVLBA1qMSefxji7TwT1PDj8H48",
        "/ip4/45.79.189.79/udp/1211/quic-v1/p2p/12D3KooWL4Y91NuCxWVmjh9TNpFVLBA1qMSefxji7TwT1PDj8H48",
        "/ip6/2600:3c03::f03c:94ff:fea6:30d2/tcp/1211/p2p/12D3KooWL4Y91NuCxWVmjh9TNpFVLBA1qMSefxji7TwT1PDj8H48",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB