windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c08::f03c:94ff:fe42:366c/tcp/1211/p2p/12D3KooWQVT9vX1GFX4GYRjdo1qj69BjZ3GCyUWEpefo3kXK3TVq",
        "/ip6/2600:3c08::f03c:94ff:fe42:366c/udp/1211/quic-v1/p2p/12D3KooWQVT9vX1GFX4GYRjdo1qj69BjZ3GCyUWEpefo3kXK3TVq",
        "/ip4/172.235.4.254/tcp/1211/p2p/12D3KooWQVT9vX1GFX4GYRjdo1qj69BjZ3GCyUWEpefo3kXK3TVq",
        "/ip4/172.235.4.254/udp/1211/quic-v1/p2p/12D3KooWQVT9vX1GFX4GYRjdo1qj69BjZ3GCyUWEpefo3kXK3TVq",
        "/ip6/2400:8901::f03c:94ff:fe42:36ac/udp/1211/quic-v1/p2p/12D3KooWRTs37G1UhXH3eSCTNu73fJ5t8VerwEci1NSFJuGDdsRU",
        "/ip4/170.187.225.196/tcp/1211/p2p/12D3KooWRTs37G1UhXH3eSCTNu73fJ5t8VerwEci1NSFJuGDdsRU",
        "/ip4/170.187.225.196/udp/1211/quic-v1/p2p/12D3KooWRTs37G1UhXH3eSCTNu73fJ5t8VerwEci1NSFJuGDdsRU",
        "/ip6/2400:8901::f03c:94ff:fe42:36ac/tcp/1211/p2p/12D3KooWRTs37G1UhXH3eSCTNu73fJ5t8VerwEci1NSFJuGDdsRU",
        "/ip4/172.105.0.222/tcp/1211/p2p/12D3KooWMQCYd8s5rikn2fh26QQcuph4zarJhfW3UsLuU4qj2sq9",
        "/ip4/172.105.0.222/udp/1211/quic-v1/p2p/12D3KooWMQCYd8s5rikn2fh26QQcuph4zarJhfW3UsLuU4qj2sq9",
        "/ip6/2600:3c04::f03c:94ff:fe42:3638/tcp/1211/p2p/12D3KooWMQCYd8s5rikn2fh26QQcuph4zarJhfW3UsLuU4qj2sq9",
        "/ip6/2600:3c04::f03c:94ff:fe42:3638/udp/1211/quic-v1/p2p/12D3KooWMQCYd8s5rikn2fh26QQcuph4zarJhfW3UsLuU4qj2sq9",
        "/ip4/172.105.23.237/tcp/1211/p2p/12D3KooWFJCSZgNabhSy8Rc49xDExJkUpq4sgPpheNcYG18u4TxC",
        "/ip4/172.105.23.237/udp/1211/quic-v1/p2p/12D3KooWFJCSZgNabhSy8Rc49xDExJkUpq4sgPpheNcYG18u4TxC",
        "/ip6/2600:3c04::f03c:94ff:fe42:362e/tcp/1211/p2p/12D3KooWFJCSZgNabhSy8Rc49xDExJkUpq4sgPpheNcYG18u4TxC",
        "/ip6/2600:3c04::f03c:94ff:fe42:362e/udp/1211/quic-v1/p2p/12D3KooWFJCSZgNabhSy8Rc49xDExJkUpq4sgPpheNcYG18u4TxC",
        "/ip4/172.233.40.174/tcp/1211/p2p/12D3KooWSptKw4gnXXExGWBMjsbcHsfc2LzaEacLV2aVTPEWQwVq",
        "/ip4/172.233.40.174/udp/1211/quic-v1/p2p/12D3KooWSptKw4gnXXExGWBMjsbcHsfc2LzaEacLV2aVTPEWQwVq",
        "/ip6/2600:3c0e::f03c:94ff:fe42:36fa/tcp/1211/p2p/12D3KooWSptKw4gnXXExGWBMjsbcHsfc2LzaEacLV2aVTPEWQwVq",
        "/ip6/2600:3c0e::f03c:94ff:fe42:36fa/udp/1211/quic-v1/p2p/12D3KooWSptKw4gnXXExGWBMjsbcHsfc2LzaEacLV2aVTPEWQwVq",
        "/ip4/172.233.107.251/udp/1211/quic-v1/p2p/12D3KooWQFcxaYXe65qEUciLbxrnwAFDM6hBv2tyghUkHkkT9p6N",
        "/ip6/2a01:7e02::f03c:94ff:fe42:363c/tcp/1211/p2p/12D3KooWQFcxaYXe65qEUciLbxrnwAFDM6hBv2tyghUkHkkT9p6N",
        "/ip6/2a01:7e02::f03c:94ff:fe42:363c/udp/1211/quic-v1/p2p/12D3KooWQFcxaYXe65qEUciLbxrnwAFDM6hBv2tyghUkHkkT9p6N",
        "/ip4/172.233.107.251/tcp/1211/p2p/12D3KooWQFcxaYXe65qEUciLbxrnwAFDM6hBv2tyghUkHkkT9p6N",
        "/ip4/172.105.186.149/tcp/1211/p2p/12D3KooWSKe3gAatCdPLfytWcv5Tuz1mT86GaPw4Fx4ut4yEJ2Mh",
        "/ip4/172.105.186.149/udp/1211/quic-v1/p2p/12D3KooWSKe3gAatCdPLfytWcv5Tuz1mT86GaPw4Fx4ut4yEJ2Mh",
        "/ip6/2400:8907::f03c:94ff:fe42:3678/tcp/1211/p2p/12D3KooWSKe3gAatCdPLfytWcv5Tuz1mT86GaPw4Fx4ut4yEJ2Mh",
        "/ip6/2400:8907::f03c:94ff:fe42:3678/udp/1211/quic-v1/p2p/12D3KooWSKe3gAatCdPLfytWcv5Tuz1mT86GaPw4Fx4ut4yEJ2Mh",
        "/ip4/97.107.135.216/udp/1211/quic-v1/p2p/12D3KooWJvHnBY2zJ52BsGPqTtt82QaqHFnpmuFvzDTdad1xgPn9",
        "/ip6/2600:3c03::f03c:94ff:fe42:36f9/tcp/1211/p2p/12D3KooWJvHnBY2zJ52BsGPqTtt82QaqHFnpmuFvzDTdad1xgPn9",
        "/ip6/2600:3c03::f03c:94ff:fe42:36f9/udp/1211/quic-v1/p2p/12D3KooWJvHnBY2zJ52BsGPqTtt82QaqHFnpmuFvzDTdad1xgPn9",
        "/ip4/97.107.135.216/tcp/1211/p2p/12D3KooWJvHnBY2zJ52BsGPqTtt82QaqHFnpmuFvzDTdad1xgPn9",
        "/ip4/172.233.1.87/udp/1211/quic-v1/p2p/12D3KooWFRuKjMsPB1SSkPbYETa2G3YxYRzo1A8RqGpskmTEMpE7",
        "/ip6/2600:3c0d::f03c:94ff:fe42:36f5/tcp/1211/p2p/12D3KooWFRuKjMsPB1SSkPbYETa2G3YxYRzo1A8RqGpskmTEMpE7",
        "/ip6/2600:3c0d::f03c:94ff:fe42:36f5/udp/1211/quic-v1/p2p/12D3KooWFRuKjMsPB1SSkPbYETa2G3YxYRzo1A8RqGpskmTEMpE7",
        "/ip4/172.233.1.87/tcp/1211/p2p/12D3KooWFRuKjMsPB1SSkPbYETa2G3YxYRzo1A8RqGpskmTEMpE7",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB