windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
ecdsaKeyPairPassword: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
  "/ip4/13.37.148.174/tcp/1212/p2p/12D3KooWSwK3gCNp3pc7MQYsF4giuk78wPEGwg5zSGQRXHgrgkan", # bootstrap node test
  "/ip4/13.37.148.174/udp/1212/quic-v1/p2p/12D3KooWSwK3gCNp3pc7MQYsF4giuk78wPEGwg5zSGQRXHgrgkan", # bootstrap node test
  # "/ip4/13.37.148.174/tcp/1211/p2p/12D3KooWBm6aEtcGiJNsnsCwaiH4SoqJHZMgvctdQsyAenwyt8Ds",
	# "/ip4/13.37.148.174/udp/1211/quic-v1/p2p/12D3KooWBm6aEtcGiJNsnsCwaiH4SoqJHZMgvctdQsyAenwyt8Ds",
	# "/ip4/154.56.63.167/tcp/1211/p2p/12D3KooWA8jcyCRDXhk1H7kgBg1ui1pBi2ezJC4mtmkRuvPFUegc",
	# "/ip4/154.56.63.167/udp/1211/quic-v1/p2p/12D3KooWA8jcyCRDXhk1H7kgBg1ui1pBi2ezJC4mtmkRuvPFUegc",
]
listeningPort: 0
discoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB