windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/139.162.34.35/udp/1211/quic-v1/p2p/12D3KooWGum5U9Ht87WTUpRQ4vfwhWEafb2tWU5fwMVUaLkwnS3N",
        "/ip6/2400:8901::f03c:94ff:feb6:fc3a/tcp/1211/p2p/12D3KooWGum5U9Ht87WTUpRQ4vfwhWEafb2tWU5fwMVUaLkwnS3N",
        "/ip6/2400:8901::f03c:94ff:feb6:fc3a/udp/1211/quic-v1/p2p/12D3KooWGum5U9Ht87WTUpRQ4vfwhWEafb2tWU5fwMVUaLkwnS3N",
        "/ip4/139.162.34.35/tcp/1211/p2p/12D3KooWGum5U9Ht87WTUpRQ4vfwhWEafb2tWU5fwMVUaLkwnS3N",
        "/ip4/45.79.131.244/tcp/1211/p2p/12D3KooWDgxL1A6XTSQWdaEmCL2S9pDjwFVDkzBUKuTCUjo7PUjD",
        "/ip4/45.79.131.244/udp/1211/quic-v1/p2p/12D3KooWDgxL1A6XTSQWdaEmCL2S9pDjwFVDkzBUKuTCUjo7PUjD",
        "/ip6/2600:3c03::f03c:94ff:feb6:fc64/tcp/1211/p2p/12D3KooWDgxL1A6XTSQWdaEmCL2S9pDjwFVDkzBUKuTCUjo7PUjD",
        "/ip6/2600:3c03::f03c:94ff:feb6:fc64/udp/1211/quic-v1/p2p/12D3KooWDgxL1A6XTSQWdaEmCL2S9pDjwFVDkzBUKuTCUjo7PUjD",
        "/ip4/172.233.108.40/tcp/1211/p2p/12D3KooWNg7F4EqkF3twjHyp7ZL8UuLxTd6v1QRAUrWts65QaUmv",
        "/ip4/172.233.108.40/udp/1211/quic-v1/p2p/12D3KooWNg7F4EqkF3twjHyp7ZL8UuLxTd6v1QRAUrWts65QaUmv",
        "/ip6/2a01:7e02::f03c:94ff:feb6:fc20/tcp/1211/p2p/12D3KooWNg7F4EqkF3twjHyp7ZL8UuLxTd6v1QRAUrWts65QaUmv",
        "/ip6/2a01:7e02::f03c:94ff:feb6:fc20/udp/1211/quic-v1/p2p/12D3KooWNg7F4EqkF3twjHyp7ZL8UuLxTd6v1QRAUrWts65QaUmv",
        "/ip6/2a01:7e00::f03c:94ff:feb6:fce1/udp/1211/quic-v1/p2p/12D3KooWSSdf1gob1gd95nT5XzHhz6onGkfnitCSvpy2jvJTUtVU",
        "/ip4/139.162.231.79/tcp/1211/p2p/12D3KooWSSdf1gob1gd95nT5XzHhz6onGkfnitCSvpy2jvJTUtVU",
        "/ip4/139.162.231.79/udp/1211/quic-v1/p2p/12D3KooWSSdf1gob1gd95nT5XzHhz6onGkfnitCSvpy2jvJTUtVU",
        "/ip6/2a01:7e00::f03c:94ff:feb6:fce1/tcp/1211/p2p/12D3KooWSSdf1gob1gd95nT5XzHhz6onGkfnitCSvpy2jvJTUtVU",
        "/ip4/192.46.223.24/tcp/1211/p2p/12D3KooWHPtQu5XLSc6mk7AMWQurdKXVG2ma6RsASGv7yoP5t15u",
        "/ip4/192.46.223.24/udp/1211/quic-v1/p2p/12D3KooWHPtQu5XLSc6mk7AMWQurdKXVG2ma6RsASGv7yoP5t15u",
        "/ip6/2600:3c04::f03c:94ff:feb6:fca8/tcp/1211/p2p/12D3KooWHPtQu5XLSc6mk7AMWQurdKXVG2ma6RsASGv7yoP5t15u",
        "/ip6/2600:3c04::f03c:94ff:feb6:fca8/udp/1211/quic-v1/p2p/12D3KooWHPtQu5XLSc6mk7AMWQurdKXVG2ma6RsASGv7yoP5t15u",
        "/ip4/172.235.16.150/tcp/1211/p2p/12D3KooWBb4RaKb9WfSdy1EXHXf2EqvN7qZLHPyUVWaRNn5oyHJv",
        "/ip4/172.235.16.150/udp/1211/quic-v1/p2p/12D3KooWBb4RaKb9WfSdy1EXHXf2EqvN7qZLHPyUVWaRNn5oyHJv",
        "/ip6/2600:3c08::f03c:94ff:feb6:fcd1/tcp/1211/p2p/12D3KooWBb4RaKb9WfSdy1EXHXf2EqvN7qZLHPyUVWaRNn5oyHJv",
        "/ip6/2600:3c08::f03c:94ff:feb6:fcd1/udp/1211/quic-v1/p2p/12D3KooWBb4RaKb9WfSdy1EXHXf2EqvN7qZLHPyUVWaRNn5oyHJv",
        "/ip4/172.105.99.7/tcp/1211/p2p/12D3KooWCcny4z7GxZvdgR1wD1LA2ydkrb7GM5E2UXg2uJQDLGzK",
        "/ip4/172.105.99.7/udp/1211/quic-v1/p2p/12D3KooWCcny4z7GxZvdgR1wD1LA2ydkrb7GM5E2UXg2uJQDLGzK",
        "/ip6/2600:3c04::f03c:94ff:feb6:fc7f/tcp/1211/p2p/12D3KooWCcny4z7GxZvdgR1wD1LA2ydkrb7GM5E2UXg2uJQDLGzK",
        "/ip6/2600:3c04::f03c:94ff:feb6:fc7f/udp/1211/quic-v1/p2p/12D3KooWCcny4z7GxZvdgR1wD1LA2ydkrb7GM5E2UXg2uJQDLGzK",
        "/ip4/194.195.248.139/tcp/1211/p2p/12D3KooWCuoro7P8AFU7uZX1VYatuovKn5TGfnLQvZccEXEMEg8n",
        "/ip4/194.195.248.139/udp/1211/quic-v1/p2p/12D3KooWCuoro7P8AFU7uZX1VYatuovKn5TGfnLQvZccEXEMEg8n",
        "/ip6/2400:8907::f03c:94ff:feb6:fcff/tcp/1211/p2p/12D3KooWCuoro7P8AFU7uZX1VYatuovKn5TGfnLQvZccEXEMEg8n",
        "/ip6/2400:8907::f03c:94ff:feb6:fcff/udp/1211/quic-v1/p2p/12D3KooWCuoro7P8AFU7uZX1VYatuovKn5TGfnLQvZccEXEMEg8n",
        "/ip4/172.233.40.112/tcp/1211/p2p/12D3KooWMJM2WptopAVpkPR7gvngdkhofsnbhZXbUMwjyDMKsEXY",
        "/ip4/172.233.40.112/udp/1211/quic-v1/p2p/12D3KooWMJM2WptopAVpkPR7gvngdkhofsnbhZXbUMwjyDMKsEXY",
        "/ip6/2600:3c0e::f03c:94ff:feb6:fcb8/tcp/1211/p2p/12D3KooWMJM2WptopAVpkPR7gvngdkhofsnbhZXbUMwjyDMKsEXY",
        "/ip6/2600:3c0e::f03c:94ff:feb6:fcb8/udp/1211/quic-v1/p2p/12D3KooWMJM2WptopAVpkPR7gvngdkhofsnbhZXbUMwjyDMKsEXY",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB