windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c0e::f03c:94ff:fe80:da89/tcp/1211/p2p/12D3KooWCQ1DkmMUFjQPsCKvUJ3Xe6BZQAV9F7NmBuRpzgNq4ttf",
        "/ip6/2600:3c0e::f03c:94ff:fe80:da89/udp/1211/quic-v1/p2p/12D3KooWCQ1DkmMUFjQPsCKvUJ3Xe6BZQAV9F7NmBuRpzgNq4ttf",
        "/ip4/172.233.38.171/tcp/1211/p2p/12D3KooWCQ1DkmMUFjQPsCKvUJ3Xe6BZQAV9F7NmBuRpzgNq4ttf",
        "/ip4/172.233.38.171/udp/1211/quic-v1/p2p/12D3KooWCQ1DkmMUFjQPsCKvUJ3Xe6BZQAV9F7NmBuRpzgNq4ttf",
        "/ip4/172.104.173.134/tcp/1211/p2p/12D3KooWNwSMxaUc51Jp1A3KE64ZvchVZ4761kCE3oLRWwqfEmXa",
        "/ip4/172.104.173.134/udp/1211/quic-v1/p2p/12D3KooWNwSMxaUc51Jp1A3KE64ZvchVZ4761kCE3oLRWwqfEmXa",
        "/ip6/2400:8901::f03c:94ff:fe80:dac3/tcp/1211/p2p/12D3KooWNwSMxaUc51Jp1A3KE64ZvchVZ4761kCE3oLRWwqfEmXa",
        "/ip6/2400:8901::f03c:94ff:fe80:dac3/udp/1211/quic-v1/p2p/12D3KooWNwSMxaUc51Jp1A3KE64ZvchVZ4761kCE3oLRWwqfEmXa",
        "/ip4/172.105.191.70/tcp/1211/p2p/12D3KooWCNJCwhXPR5VMoAFDjQ1yby4XTUkUZPaxm1JTKpw7mXaT",
        "/ip4/172.105.191.70/udp/1211/quic-v1/p2p/12D3KooWCNJCwhXPR5VMoAFDjQ1yby4XTUkUZPaxm1JTKpw7mXaT",
        "/ip6/2400:8907::f03c:94ff:fe80:dafc/tcp/1211/p2p/12D3KooWCNJCwhXPR5VMoAFDjQ1yby4XTUkUZPaxm1JTKpw7mXaT",
        "/ip6/2400:8907::f03c:94ff:fe80:dafc/udp/1211/quic-v1/p2p/12D3KooWCNJCwhXPR5VMoAFDjQ1yby4XTUkUZPaxm1JTKpw7mXaT",
        "/ip4/172.233.120.89/tcp/1211/p2p/12D3KooWLagxab39z5HPNqrQUp23iMaG9Mu1Nas7rsLM5GA9v7Ua",
        "/ip4/172.233.120.89/udp/1211/quic-v1/p2p/12D3KooWLagxab39z5HPNqrQUp23iMaG9Mu1Nas7rsLM5GA9v7Ua",
        "/ip6/2a01:7e02::f03c:94ff:fe80:dadd/tcp/1211/p2p/12D3KooWLagxab39z5HPNqrQUp23iMaG9Mu1Nas7rsLM5GA9v7Ua",
        "/ip6/2a01:7e02::f03c:94ff:fe80:dadd/udp/1211/quic-v1/p2p/12D3KooWLagxab39z5HPNqrQUp23iMaG9Mu1Nas7rsLM5GA9v7Ua",
        "/ip6/2600:3c04::f03c:94ff:fe80:da6b/tcp/1211/p2p/12D3KooWJ2HNMogQUdAaRtr2i8rMTetPJ1a5KizUhddq2Fo4R74d",
        "/ip6/2600:3c04::f03c:94ff:fe80:da6b/udp/1211/quic-v1/p2p/12D3KooWJ2HNMogQUdAaRtr2i8rMTetPJ1a5KizUhddq2Fo4R74d",
        "/ip4/172.105.5.244/tcp/1211/p2p/12D3KooWJ2HNMogQUdAaRtr2i8rMTetPJ1a5KizUhddq2Fo4R74d",
        "/ip4/172.105.5.244/udp/1211/quic-v1/p2p/12D3KooWJ2HNMogQUdAaRtr2i8rMTetPJ1a5KizUhddq2Fo4R74d",
        "/ip4/172.233.15.111/tcp/1211/p2p/12D3KooWM6SJptjY1mUpc2o44KRmcmcLzjpcJxCTHSBFuLgaXZot",
        "/ip4/172.233.15.111/udp/1211/quic-v1/p2p/12D3KooWM6SJptjY1mUpc2o44KRmcmcLzjpcJxCTHSBFuLgaXZot",
        "/ip6/2600:3c0d::f03c:94ff:fe80:daf9/tcp/1211/p2p/12D3KooWM6SJptjY1mUpc2o44KRmcmcLzjpcJxCTHSBFuLgaXZot",
        "/ip6/2600:3c0d::f03c:94ff:fe80:daf9/udp/1211/quic-v1/p2p/12D3KooWM6SJptjY1mUpc2o44KRmcmcLzjpcJxCTHSBFuLgaXZot",
        "/ip6/2a01:7e00::f03c:94ff:fe80:da3c/tcp/1211/p2p/12D3KooWALkMkNgRcbzfhTgKLtRmQb1zoce8asnuoQ5QPk37pWMQ",
        "/ip6/2a01:7e00::f03c:94ff:fe80:da3c/udp/1211/quic-v1/p2p/12D3KooWALkMkNgRcbzfhTgKLtRmQb1zoce8asnuoQ5QPk37pWMQ",
        "/ip4/212.71.235.76/tcp/1211/p2p/12D3KooWALkMkNgRcbzfhTgKLtRmQb1zoce8asnuoQ5QPk37pWMQ",
        "/ip4/212.71.235.76/udp/1211/quic-v1/p2p/12D3KooWALkMkNgRcbzfhTgKLtRmQb1zoce8asnuoQ5QPk37pWMQ",
        "/ip4/172.235.6.176/tcp/1211/p2p/12D3KooWRiV7rQWgzFCXgb99vs5ZXkD5v55KymNBNsJPsgzBGuvz",
        "/ip4/172.235.6.176/udp/1211/quic-v1/p2p/12D3KooWRiV7rQWgzFCXgb99vs5ZXkD5v55KymNBNsJPsgzBGuvz",
        "/ip6/2600:3c08::f03c:94ff:fe80:daa4/tcp/1211/p2p/12D3KooWRiV7rQWgzFCXgb99vs5ZXkD5v55KymNBNsJPsgzBGuvz",
        "/ip6/2600:3c08::f03c:94ff:fe80:daa4/udp/1211/quic-v1/p2p/12D3KooWRiV7rQWgzFCXgb99vs5ZXkD5v55KymNBNsJPsgzBGuvz",
        "/ip6/2600:3c04::f03c:94ff:fe80:da97/tcp/1211/p2p/12D3KooWQoHmoeFq8K2GM8CMzcaCC4aXGjbSQkrnUEUTc2mRFzkJ",
        "/ip6/2600:3c04::f03c:94ff:fe80:da97/udp/1211/quic-v1/p2p/12D3KooWQoHmoeFq8K2GM8CMzcaCC4aXGjbSQkrnUEUTc2mRFzkJ",
        "/ip4/172.105.15.252/tcp/1211/p2p/12D3KooWQoHmoeFq8K2GM8CMzcaCC4aXGjbSQkrnUEUTc2mRFzkJ",
        "/ip4/172.105.15.252/udp/1211/quic-v1/p2p/12D3KooWQoHmoeFq8K2GM8CMzcaCC4aXGjbSQkrnUEUTc2mRFzkJ",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB