windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.235.205.122/tcp/1211/p2p/12D3KooWGHLxQPSsxcLewetkKHFP66gR8bP2wWNqQRMchR8bUGbu",
        "/ip4/172.235.205.122/udp/1211/quic-v1/p2p/12D3KooWGHLxQPSsxcLewetkKHFP66gR8bP2wWNqQRMchR8bUGbu",
        "/ip6/2400:8905::f03c:94ff:fe05:f693/tcp/1211/p2p/12D3KooWGHLxQPSsxcLewetkKHFP66gR8bP2wWNqQRMchR8bUGbu",
        "/ip6/2400:8905::f03c:94ff:fe05:f693/udp/1211/quic-v1/p2p/12D3KooWGHLxQPSsxcLewetkKHFP66gR8bP2wWNqQRMchR8bUGbu",
        "/ip4/72.14.181.238/tcp/1211/p2p/12D3KooWKzETUoiqxrEZEYQQqwKbkcf3nwqhCBNP77AL3GYE87ht",
        "/ip4/72.14.181.238/udp/1211/quic-v1/p2p/12D3KooWKzETUoiqxrEZEYQQqwKbkcf3nwqhCBNP77AL3GYE87ht",
        "/ip6/2600:3c00::f03c:94ff:fe05:a278/tcp/1211/p2p/12D3KooWKzETUoiqxrEZEYQQqwKbkcf3nwqhCBNP77AL3GYE87ht",
        "/ip6/2600:3c00::f03c:94ff:fe05:a278/udp/1211/quic-v1/p2p/12D3KooWKzETUoiqxrEZEYQQqwKbkcf3nwqhCBNP77AL3GYE87ht",
        "/ip4/172.235.205.131/tcp/1211/p2p/12D3KooWBgF8EdVkEhsZfFoGcXoroGDqPB4rZpc7EBriUXRxdEi6",
        "/ip4/172.235.205.131/udp/1211/quic-v1/p2p/12D3KooWBgF8EdVkEhsZfFoGcXoroGDqPB4rZpc7EBriUXRxdEi6",
        "/ip6/2400:8905::f03c:94ff:fe05:8031/tcp/1211/p2p/12D3KooWBgF8EdVkEhsZfFoGcXoroGDqPB4rZpc7EBriUXRxdEi6",
        "/ip6/2400:8905::f03c:94ff:fe05:8031/udp/1211/quic-v1/p2p/12D3KooWBgF8EdVkEhsZfFoGcXoroGDqPB4rZpc7EBriUXRxdEi6",
        "/ip6/2600:3c0d::f03c:94ff:fe05:809c/tcp/1211/p2p/12D3KooWMQaC86fdoi4hYBb4f8NbFqeWDXuMnYG6CLaArUPdfUpA",
        "/ip6/2600:3c0d::f03c:94ff:fe05:809c/udp/1211/quic-v1/p2p/12D3KooWMQaC86fdoi4hYBb4f8NbFqeWDXuMnYG6CLaArUPdfUpA",
        "/ip4/172.233.28.232/tcp/1211/p2p/12D3KooWMQaC86fdoi4hYBb4f8NbFqeWDXuMnYG6CLaArUPdfUpA",
        "/ip4/172.233.28.232/udp/1211/quic-v1/p2p/12D3KooWMQaC86fdoi4hYBb4f8NbFqeWDXuMnYG6CLaArUPdfUpA",
        "/ip4/172.232.206.216/tcp/1211/p2p/12D3KooWKmHq1j9JwGMx2wkDNDb4FEnXGy9yfYduvTXxYiGYjbxL",
        "/ip4/172.232.206.216/udp/1211/quic-v1/p2p/12D3KooWKmHq1j9JwGMx2wkDNDb4FEnXGy9yfYduvTXxYiGYjbxL",
        "/ip6/2600:3c0b::f03c:94ff:fe05:f6c3/tcp/1211/p2p/12D3KooWKmHq1j9JwGMx2wkDNDb4FEnXGy9yfYduvTXxYiGYjbxL",
        "/ip6/2600:3c0b::f03c:94ff:fe05:f6c3/udp/1211/quic-v1/p2p/12D3KooWKmHq1j9JwGMx2wkDNDb4FEnXGy9yfYduvTXxYiGYjbxL",
        "/ip4/45.79.120.63/tcp/1211/p2p/12D3KooWGpkCSTQr9c9aKqCRxGvNs4p2QBZ42J6cLCzaNm14dj7k",
        "/ip4/45.79.120.63/udp/1211/quic-v1/p2p/12D3KooWGpkCSTQr9c9aKqCRxGvNs4p2QBZ42J6cLCzaNm14dj7k",
        "/ip6/2400:8904::f03c:94ff:fe05:a288/tcp/1211/p2p/12D3KooWGpkCSTQr9c9aKqCRxGvNs4p2QBZ42J6cLCzaNm14dj7k",
        "/ip6/2400:8904::f03c:94ff:fe05:a288/udp/1211/quic-v1/p2p/12D3KooWGpkCSTQr9c9aKqCRxGvNs4p2QBZ42J6cLCzaNm14dj7k",
        "/ip6/2a01:7e00::f03c:94ff:fe05:80f0/tcp/1211/p2p/12D3KooWDEWLKbusS6PE8nFqYKEVobVD2anC5KapBBMvCB6avZAB",
        "/ip6/2a01:7e00::f03c:94ff:fe05:80f0/udp/1211/quic-v1/p2p/12D3KooWDEWLKbusS6PE8nFqYKEVobVD2anC5KapBBMvCB6avZAB",
        "/ip4/176.58.99.203/tcp/1211/p2p/12D3KooWDEWLKbusS6PE8nFqYKEVobVD2anC5KapBBMvCB6avZAB",
        "/ip4/176.58.99.203/udp/1211/quic-v1/p2p/12D3KooWDEWLKbusS6PE8nFqYKEVobVD2anC5KapBBMvCB6avZAB",
        "/ip6/2600:3c08::f03c:94ff:fe05:8032/tcp/1211/p2p/12D3KooWBjojzbjnmx4rYXz48oMmVbjonQrSmqubtffPgCdrVEj3",
        "/ip6/2600:3c08::f03c:94ff:fe05:8032/udp/1211/quic-v1/p2p/12D3KooWBjojzbjnmx4rYXz48oMmVbjonQrSmqubtffPgCdrVEj3",
        "/ip4/172.232.125.188/tcp/1211/p2p/12D3KooWBjojzbjnmx4rYXz48oMmVbjonQrSmqubtffPgCdrVEj3",
        "/ip4/172.232.125.188/udp/1211/quic-v1/p2p/12D3KooWBjojzbjnmx4rYXz48oMmVbjonQrSmqubtffPgCdrVEj3",
        "/ip4/172.233.163.117/tcp/1211/p2p/12D3KooWN7yjYBstzDrYeAnUBJZZoNBXxsac4RgYif7jdiV2AeA9",
        "/ip4/172.233.163.117/udp/1211/quic-v1/p2p/12D3KooWN7yjYBstzDrYeAnUBJZZoNBXxsac4RgYif7jdiV2AeA9",
        "/ip6/2a01:7e04::f03c:94ff:fe05:5be/tcp/1211/p2p/12D3KooWN7yjYBstzDrYeAnUBJZZoNBXxsac4RgYif7jdiV2AeA9",
        "/ip6/2a01:7e04::f03c:94ff:fe05:5be/udp/1211/quic-v1/p2p/12D3KooWN7yjYBstzDrYeAnUBJZZoNBXxsac4RgYif7jdiV2AeA9",
        "/ip4/139.162.10.115/tcp/1211/p2p/12D3KooWN8GHCrdLqH8LsD2wJ8Z5L6137sdPXnupNY795sQMpBzB",
        "/ip4/139.162.10.115/udp/1211/quic-v1/p2p/12D3KooWN8GHCrdLqH8LsD2wJ8Z5L6137sdPXnupNY795sQMpBzB",
        "/ip6/2400:8901::f03c:94ff:fe05:558/tcp/1211/p2p/12D3KooWN8GHCrdLqH8LsD2wJ8Z5L6137sdPXnupNY795sQMpBzB",
        "/ip6/2400:8901::f03c:94ff:fe05:558/udp/1211/quic-v1/p2p/12D3KooWN8GHCrdLqH8LsD2wJ8Z5L6137sdPXnupNY795sQMpBzB",
        "/ip4/139.177.179.127/tcp/1211/p2p/12D3KooWLswqN2jVfqBs8iQcPzqHd1X6hv6umGZcXZRrsQ9GjWH8",
        "/ip4/139.177.179.127/udp/1211/quic-v1/p2p/12D3KooWLswqN2jVfqBs8iQcPzqHd1X6hv6umGZcXZRrsQ9GjWH8",
        "/ip6/2a01:7e01::f03c:94ff:fe05:f60f/tcp/1211/p2p/12D3KooWLswqN2jVfqBs8iQcPzqHd1X6hv6umGZcXZRrsQ9GjWH8",
        "/ip6/2a01:7e01::f03c:94ff:fe05:f60f/udp/1211/quic-v1/p2p/12D3KooWLswqN2jVfqBs8iQcPzqHd1X6hv6umGZcXZRrsQ9GjWH8",
        "/ip4/172.105.28.146/udp/1211/quic-v1/p2p/12D3KooWDg2jJ82svSTfzTzf9Spv5EgpbmJKG3R9Nem5DLqvAN9u",
        "/ip6/2600:3c04::f03c:94ff:fe05:584/tcp/1211/p2p/12D3KooWDg2jJ82svSTfzTzf9Spv5EgpbmJKG3R9Nem5DLqvAN9u",
        "/ip6/2600:3c04::f03c:94ff:fe05:584/udp/1211/quic-v1/p2p/12D3KooWDg2jJ82svSTfzTzf9Spv5EgpbmJKG3R9Nem5DLqvAN9u",
        "/ip4/172.105.28.146/tcp/1211/p2p/12D3KooWDg2jJ82svSTfzTzf9Spv5EgpbmJKG3R9Nem5DLqvAN9u",
        "/ip6/2400:8901::f03c:94ff:fe05:a236/tcp/1211/p2p/12D3KooWLKqK5AxJ89aRirzZtX8D6wrBAVE7PHRBfKHKs1jQqson",
        "/ip6/2400:8901::f03c:94ff:fe05:a236/udp/1211/quic-v1/p2p/12D3KooWLKqK5AxJ89aRirzZtX8D6wrBAVE7PHRBfKHKs1jQqson",
        "/ip4/139.162.61.82/tcp/1211/p2p/12D3KooWLKqK5AxJ89aRirzZtX8D6wrBAVE7PHRBfKHKs1jQqson",
        "/ip4/139.162.61.82/udp/1211/quic-v1/p2p/12D3KooWLKqK5AxJ89aRirzZtX8D6wrBAVE7PHRBfKHKs1jQqson",
        "/ip4/172.232.125.27/tcp/1211/p2p/12D3KooWE89NuAHGMdYeyDaiSd3Vn768x99g6LNWFAHYnx2nYuL1",
        "/ip4/172.232.125.27/udp/1211/quic-v1/p2p/12D3KooWE89NuAHGMdYeyDaiSd3Vn768x99g6LNWFAHYnx2nYuL1",
        "/ip6/2600:3c08::f03c:94ff:fe05:f6d3/tcp/1211/p2p/12D3KooWE89NuAHGMdYeyDaiSd3Vn768x99g6LNWFAHYnx2nYuL1",
        "/ip6/2600:3c08::f03c:94ff:fe05:f6d3/udp/1211/quic-v1/p2p/12D3KooWE89NuAHGMdYeyDaiSd3Vn768x99g6LNWFAHYnx2nYuL1",
        "/ip4/192.46.221.117/tcp/1211/p2p/12D3KooWNrhQQXUMx1TrL6o94saCk3Xr53nvXtpD8bfHx7uXqkTQ",
        "/ip4/192.46.221.117/udp/1211/quic-v1/p2p/12D3KooWNrhQQXUMx1TrL6o94saCk3Xr53nvXtpD8bfHx7uXqkTQ",
        "/ip6/2400:8907::f03c:94ff:fe05:80cc/tcp/1211/p2p/12D3KooWNrhQQXUMx1TrL6o94saCk3Xr53nvXtpD8bfHx7uXqkTQ",
        "/ip6/2400:8907::f03c:94ff:fe05:80cc/udp/1211/quic-v1/p2p/12D3KooWNrhQQXUMx1TrL6o94saCk3Xr53nvXtpD8bfHx7uXqkTQ",
        "/ip4/45.33.30.63/tcp/1211/p2p/12D3KooWNcwXnUQmSB9vxoxMLyip6E7bVxr9gbirj81a9QUBEv8K",
        "/ip4/45.33.30.63/udp/1211/quic-v1/p2p/12D3KooWNcwXnUQmSB9vxoxMLyip6E7bVxr9gbirj81a9QUBEv8K",
        "/ip6/2600:3c00::f03c:94ff:fe05:50d/tcp/1211/p2p/12D3KooWNcwXnUQmSB9vxoxMLyip6E7bVxr9gbirj81a9QUBEv8K",
        "/ip6/2600:3c00::f03c:94ff:fe05:50d/udp/1211/quic-v1/p2p/12D3KooWNcwXnUQmSB9vxoxMLyip6E7bVxr9gbirj81a9QUBEv8K",
        "/ip4/66.228.47.164/tcp/1211/p2p/12D3KooWHkQMa2BHkuxn4JnbjNrW4WKLEn2fYPcsj5ASbNgHHurb",
        "/ip4/66.228.47.164/udp/1211/quic-v1/p2p/12D3KooWHkQMa2BHkuxn4JnbjNrW4WKLEn2fYPcsj5ASbNgHHurb",
        "/ip6/2600:3c03::f03c:94ff:fe05:7a70/tcp/1211/p2p/12D3KooWHkQMa2BHkuxn4JnbjNrW4WKLEn2fYPcsj5ASbNgHHurb",
        "/ip6/2600:3c03::f03c:94ff:fe05:7a70/udp/1211/quic-v1/p2p/12D3KooWHkQMa2BHkuxn4JnbjNrW4WKLEn2fYPcsj5ASbNgHHurb",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB