windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.190.124/tcp/1211/p2p/12D3KooWFbarzeocVXZBfKsGdg3dLuEc3GGczR9fYxmHDmi4vtfj",
        "/ip4/172.105.190.124/udp/1211/quic-v1/p2p/12D3KooWFbarzeocVXZBfKsGdg3dLuEc3GGczR9fYxmHDmi4vtfj",
        "/ip6/2400:8907::f03c:94ff:fef5:619d/tcp/1211/p2p/12D3KooWFbarzeocVXZBfKsGdg3dLuEc3GGczR9fYxmHDmi4vtfj",
        "/ip6/2400:8907::f03c:94ff:fef5:619d/udp/1211/quic-v1/p2p/12D3KooWFbarzeocVXZBfKsGdg3dLuEc3GGczR9fYxmHDmi4vtfj",
        "/ip4/172.105.103.75/tcp/1211/p2p/12D3KooWEi42QLWbgxzqVjwAsD4enfMkujoDTYYcjBxfrXNhUdTd",
        "/ip4/172.105.103.75/udp/1211/quic-v1/p2p/12D3KooWEi42QLWbgxzqVjwAsD4enfMkujoDTYYcjBxfrXNhUdTd",
        "/ip6/2600:3c04::f03c:94ff:fef5:614e/tcp/1211/p2p/12D3KooWEi42QLWbgxzqVjwAsD4enfMkujoDTYYcjBxfrXNhUdTd",
        "/ip6/2600:3c04::f03c:94ff:fef5:614e/udp/1211/quic-v1/p2p/12D3KooWEi42QLWbgxzqVjwAsD4enfMkujoDTYYcjBxfrXNhUdTd",
        "/ip4/172.104.178.80/tcp/1211/p2p/12D3KooWBd8FXEA2M35bUkoREK6C7eGXw9tJvHFTter9F5MjXqvr",
        "/ip4/172.104.178.80/udp/1211/quic-v1/p2p/12D3KooWBd8FXEA2M35bUkoREK6C7eGXw9tJvHFTter9F5MjXqvr",
        "/ip6/2400:8901::f03c:94ff:fef5:6125/tcp/1211/p2p/12D3KooWBd8FXEA2M35bUkoREK6C7eGXw9tJvHFTter9F5MjXqvr",
        "/ip6/2400:8901::f03c:94ff:fef5:6125/udp/1211/quic-v1/p2p/12D3KooWBd8FXEA2M35bUkoREK6C7eGXw9tJvHFTter9F5MjXqvr",
        "/ip4/178.79.166.146/tcp/1211/p2p/12D3KooWJub84iCC5HUi7Y6VsS9bRtoUfFxYfMPUzp8M6MeDg9hS",
        "/ip4/178.79.166.146/udp/1211/quic-v1/p2p/12D3KooWJub84iCC5HUi7Y6VsS9bRtoUfFxYfMPUzp8M6MeDg9hS",
        "/ip6/2a01:7e00::f03c:94ff:fef5:61bc/tcp/1211/p2p/12D3KooWJub84iCC5HUi7Y6VsS9bRtoUfFxYfMPUzp8M6MeDg9hS",
        "/ip6/2a01:7e00::f03c:94ff:fef5:61bc/udp/1211/quic-v1/p2p/12D3KooWJub84iCC5HUi7Y6VsS9bRtoUfFxYfMPUzp8M6MeDg9hS",
        "/ip6/2600:3c03::f03c:94ff:fef5:61e9/udp/1211/quic-v1/p2p/12D3KooWJtZnEj4pAi1mWgLrbyGcxjbPMrNLGgQxJhQjJtMZ9XeZ",
        "/ip4/96.126.110.223/tcp/1211/p2p/12D3KooWJtZnEj4pAi1mWgLrbyGcxjbPMrNLGgQxJhQjJtMZ9XeZ",
        "/ip4/96.126.110.223/udp/1211/quic-v1/p2p/12D3KooWJtZnEj4pAi1mWgLrbyGcxjbPMrNLGgQxJhQjJtMZ9XeZ",
        "/ip6/2600:3c03::f03c:94ff:fef5:61e9/tcp/1211/p2p/12D3KooWJtZnEj4pAi1mWgLrbyGcxjbPMrNLGgQxJhQjJtMZ9XeZ",
        "/ip6/2a01:7e02::f03c:94ff:fef5:610c/tcp/1211/p2p/12D3KooWQ8nrwnpjt28CqBaGe8yq9iHKSzCzyrJRnPL5fxAoSf88",
        "/ip6/2a01:7e02::f03c:94ff:fef5:610c/udp/1211/quic-v1/p2p/12D3KooWQ8nrwnpjt28CqBaGe8yq9iHKSzCzyrJRnPL5fxAoSf88",
        "/ip4/172.233.120.216/tcp/1211/p2p/12D3KooWQ8nrwnpjt28CqBaGe8yq9iHKSzCzyrJRnPL5fxAoSf88",
        "/ip4/172.233.120.216/udp/1211/quic-v1/p2p/12D3KooWQ8nrwnpjt28CqBaGe8yq9iHKSzCzyrJRnPL5fxAoSf88",
        "/ip4/172.235.6.215/tcp/1211/p2p/12D3KooWJGjeBAzxnQVf4SWLanRGNWbXb6yd9Rbgs47aEjNWj9qp",
        "/ip4/172.235.6.215/udp/1211/quic-v1/p2p/12D3KooWJGjeBAzxnQVf4SWLanRGNWbXb6yd9Rbgs47aEjNWj9qp",
        "/ip6/2600:3c08::f03c:94ff:fef5:6169/tcp/1211/p2p/12D3KooWJGjeBAzxnQVf4SWLanRGNWbXb6yd9Rbgs47aEjNWj9qp",
        "/ip6/2600:3c08::f03c:94ff:fef5:6169/udp/1211/quic-v1/p2p/12D3KooWJGjeBAzxnQVf4SWLanRGNWbXb6yd9Rbgs47aEjNWj9qp",
        "/ip4/172.233.11.87/tcp/1211/p2p/12D3KooWAWcF5MawBRZerkzLLFso4DZNRjFTgFDyckEazkxmQRsN",
        "/ip4/172.233.11.87/udp/1211/quic-v1/p2p/12D3KooWAWcF5MawBRZerkzLLFso4DZNRjFTgFDyckEazkxmQRsN",
        "/ip6/2600:3c0d::f03c:94ff:fef5:615d/tcp/1211/p2p/12D3KooWAWcF5MawBRZerkzLLFso4DZNRjFTgFDyckEazkxmQRsN",
        "/ip6/2600:3c0d::f03c:94ff:fef5:615d/udp/1211/quic-v1/p2p/12D3KooWAWcF5MawBRZerkzLLFso4DZNRjFTgFDyckEazkxmQRsN",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB