windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.23.162/tcp/1211/p2p/12D3KooWF6H1WFv8wnYwUbVA11RiG4Qkg743uoTizbfyoS2jQBLq",
        "/ip4/172.105.23.162/udp/1211/quic-v1/p2p/12D3KooWF6H1WFv8wnYwUbVA11RiG4Qkg743uoTizbfyoS2jQBLq",
        "/ip6/2600:3c04::f03c:94ff:fe76:8ba/tcp/1211/p2p/12D3KooWF6H1WFv8wnYwUbVA11RiG4Qkg743uoTizbfyoS2jQBLq",
        "/ip6/2600:3c04::f03c:94ff:fe76:8ba/udp/1211/quic-v1/p2p/12D3KooWF6H1WFv8wnYwUbVA11RiG4Qkg743uoTizbfyoS2jQBLq",
        "/ip6/2600:3c04::f03c:94ff:fe76:8f2/udp/1211/quic-v1/p2p/12D3KooWGyoukkBag1SG88grWFLxQmb7CehqzSE5mk4JXX1ZyKk2",
        "/ip4/172.105.23.192/tcp/1211/p2p/12D3KooWGyoukkBag1SG88grWFLxQmb7CehqzSE5mk4JXX1ZyKk2",
        "/ip4/172.105.23.192/udp/1211/quic-v1/p2p/12D3KooWGyoukkBag1SG88grWFLxQmb7CehqzSE5mk4JXX1ZyKk2",
        "/ip6/2600:3c04::f03c:94ff:fe76:8f2/tcp/1211/p2p/12D3KooWGyoukkBag1SG88grWFLxQmb7CehqzSE5mk4JXX1ZyKk2",
        "/ip4/172.233.120.133/tcp/1211/p2p/12D3KooWLMDBzEmWME3N6ukr4ZiGDpJrxd4fmqSbW13DALAFpSuf",
        "/ip4/172.233.120.133/udp/1211/quic-v1/p2p/12D3KooWLMDBzEmWME3N6ukr4ZiGDpJrxd4fmqSbW13DALAFpSuf",
        "/ip6/2a01:7e02::f03c:94ff:fe76:8bf/tcp/1211/p2p/12D3KooWLMDBzEmWME3N6ukr4ZiGDpJrxd4fmqSbW13DALAFpSuf",
        "/ip6/2a01:7e02::f03c:94ff:fe76:8bf/udp/1211/quic-v1/p2p/12D3KooWLMDBzEmWME3N6ukr4ZiGDpJrxd4fmqSbW13DALAFpSuf",
        "/ip4/172.105.161.235/tcp/1211/p2p/12D3KooW9wBfUpSawrwNLpyhMJrEnatJJP2oSFjaV3asz88LTyFe",
        "/ip4/172.105.161.235/udp/1211/quic-v1/p2p/12D3KooW9wBfUpSawrwNLpyhMJrEnatJJP2oSFjaV3asz88LTyFe",
        "/ip6/2400:8907::f03c:94ff:fe76:847/tcp/1211/p2p/12D3KooW9wBfUpSawrwNLpyhMJrEnatJJP2oSFjaV3asz88LTyFe",
        "/ip6/2400:8907::f03c:94ff:fe76:847/udp/1211/quic-v1/p2p/12D3KooW9wBfUpSawrwNLpyhMJrEnatJJP2oSFjaV3asz88LTyFe",
        "/ip4/85.159.213.222/tcp/1211/p2p/12D3KooWEA2hPZi5o1EMS1wBdfmfwTvPcoHwUyfUC7xnjoiXPown",
        "/ip4/85.159.213.222/udp/1211/quic-v1/p2p/12D3KooWEA2hPZi5o1EMS1wBdfmfwTvPcoHwUyfUC7xnjoiXPown",
        "/ip6/2a01:7e00::f03c:94ff:fe76:859/tcp/1211/p2p/12D3KooWEA2hPZi5o1EMS1wBdfmfwTvPcoHwUyfUC7xnjoiXPown",
        "/ip6/2a01:7e00::f03c:94ff:fe76:859/udp/1211/quic-v1/p2p/12D3KooWEA2hPZi5o1EMS1wBdfmfwTvPcoHwUyfUC7xnjoiXPown",
        "/ip4/172.104.209.42/tcp/1211/p2p/12D3KooWFxyQFhFu65YadqMdgmsWtrXSDsnmUMfX1BQNLZk4tus2",
        "/ip4/172.104.209.42/udp/1211/quic-v1/p2p/12D3KooWFxyQFhFu65YadqMdgmsWtrXSDsnmUMfX1BQNLZk4tus2",
        "/ip6/2600:3c03::f03c:94ff:fe76:840/tcp/1211/p2p/12D3KooWFxyQFhFu65YadqMdgmsWtrXSDsnmUMfX1BQNLZk4tus2",
        "/ip6/2600:3c03::f03c:94ff:fe76:840/udp/1211/quic-v1/p2p/12D3KooWFxyQFhFu65YadqMdgmsWtrXSDsnmUMfX1BQNLZk4tus2",
        "/ip6/2600:3c0e::f03c:94ff:fe76:887/tcp/1211/p2p/12D3KooWGsQDGBA7g4jXtSfw3Efqithvx9bYvWGv3KTeR3RTBRW8",
        "/ip6/2600:3c0e::f03c:94ff:fe76:887/udp/1211/quic-v1/p2p/12D3KooWGsQDGBA7g4jXtSfw3Efqithvx9bYvWGv3KTeR3RTBRW8",
        "/ip4/172.233.47.64/tcp/1211/p2p/12D3KooWGsQDGBA7g4jXtSfw3Efqithvx9bYvWGv3KTeR3RTBRW8",
        "/ip4/172.233.47.64/udp/1211/quic-v1/p2p/12D3KooWGsQDGBA7g4jXtSfw3Efqithvx9bYvWGv3KTeR3RTBRW8",
        "/ip6/2400:8901::f03c:94ff:fe76:8f6/tcp/1211/p2p/12D3KooWLcSL1pUC9rDeTZ1u22y3kajFWGJS4Gquiaox2LVZrAv8",
        "/ip6/2400:8901::f03c:94ff:fe76:8f6/udp/1211/quic-v1/p2p/12D3KooWLcSL1pUC9rDeTZ1u22y3kajFWGJS4Gquiaox2LVZrAv8",
        "/ip4/172.104.62.144/tcp/1211/p2p/12D3KooWLcSL1pUC9rDeTZ1u22y3kajFWGJS4Gquiaox2LVZrAv8",
        "/ip4/172.104.62.144/udp/1211/quic-v1/p2p/12D3KooWLcSL1pUC9rDeTZ1u22y3kajFWGJS4Gquiaox2LVZrAv8",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB