windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/192.53.121.117/udp/1211/quic-v1/p2p/12D3KooWMZZGJ3CpGLKuM4eUKZenLchjLW29MYseuFZ9XXXwMdpS",
        "/ip6/2600:3c04::f03c:94ff:fed9:e3d0/tcp/1211/p2p/12D3KooWMZZGJ3CpGLKuM4eUKZenLchjLW29MYseuFZ9XXXwMdpS",
        "/ip6/2600:3c04::f03c:94ff:fed9:e3d0/udp/1211/quic-v1/p2p/12D3KooWMZZGJ3CpGLKuM4eUKZenLchjLW29MYseuFZ9XXXwMdpS",
        "/ip4/192.53.121.117/tcp/1211/p2p/12D3KooWMZZGJ3CpGLKuM4eUKZenLchjLW29MYseuFZ9XXXwMdpS",
        "/ip4/50.116.53.162/tcp/1211/p2p/12D3KooWQZL6Nyj8GNivQhfDy44h15M8EsYuAvpFbsL5GZGr1Q4W",
        "/ip4/50.116.53.162/udp/1211/quic-v1/p2p/12D3KooWQZL6Nyj8GNivQhfDy44h15M8EsYuAvpFbsL5GZGr1Q4W",
        "/ip6/2600:3c03::f03c:94ff:fed9:e3c2/tcp/1211/p2p/12D3KooWQZL6Nyj8GNivQhfDy44h15M8EsYuAvpFbsL5GZGr1Q4W",
        "/ip6/2600:3c03::f03c:94ff:fed9:e3c2/udp/1211/quic-v1/p2p/12D3KooWQZL6Nyj8GNivQhfDy44h15M8EsYuAvpFbsL5GZGr1Q4W",
        "/ip6/2a01:7e00::f03c:94ff:fed9:e311/udp/1211/quic-v1/p2p/12D3KooWPend1neCi43iDKMhV4WaRWePNyU1gATCATYSTa4gdocd",
        "/ip4/139.162.207.106/tcp/1211/p2p/12D3KooWPend1neCi43iDKMhV4WaRWePNyU1gATCATYSTa4gdocd",
        "/ip4/139.162.207.106/udp/1211/quic-v1/p2p/12D3KooWPend1neCi43iDKMhV4WaRWePNyU1gATCATYSTa4gdocd",
        "/ip6/2a01:7e00::f03c:94ff:fed9:e311/tcp/1211/p2p/12D3KooWPend1neCi43iDKMhV4WaRWePNyU1gATCATYSTa4gdocd",
        "/ip6/2600:3c0e::f03c:94ff:fed9:e35b/tcp/1211/p2p/12D3KooWAjSSeXQsxX8cX8dZgsjSt1Mc9ZyPpEFLojGZtJNpNf96",
        "/ip6/2600:3c0e::f03c:94ff:fed9:e35b/udp/1211/quic-v1/p2p/12D3KooWAjSSeXQsxX8cX8dZgsjSt1Mc9ZyPpEFLojGZtJNpNf96",
        "/ip4/172.233.51.181/tcp/1211/p2p/12D3KooWAjSSeXQsxX8cX8dZgsjSt1Mc9ZyPpEFLojGZtJNpNf96",
        "/ip4/172.233.51.181/udp/1211/quic-v1/p2p/12D3KooWAjSSeXQsxX8cX8dZgsjSt1Mc9ZyPpEFLojGZtJNpNf96",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB