windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/109.74.195.123/tcp/1211/p2p/12D3KooWDvrQWnwXcAGs1y9REfHFFmjWYUTaNszKiy23Y3ugaYcT",
        "/ip4/109.74.195.123/udp/1211/quic-v1/p2p/12D3KooWDvrQWnwXcAGs1y9REfHFFmjWYUTaNszKiy23Y3ugaYcT",
        "/ip6/2a01:7e00::f03c:94ff:fe40:320f/tcp/1211/p2p/12D3KooWDvrQWnwXcAGs1y9REfHFFmjWYUTaNszKiy23Y3ugaYcT",
        "/ip6/2a01:7e00::f03c:94ff:fe40:320f/udp/1211/quic-v1/p2p/12D3KooWDvrQWnwXcAGs1y9REfHFFmjWYUTaNszKiy23Y3ugaYcT",
        "/ip4/172.233.17.209/tcp/1211/p2p/12D3KooWQL5pHozX727aedpnMfHJ6R6q5zJ6utjaMmBxfqpTTCTD",
        "/ip4/172.233.17.209/udp/1211/quic-v1/p2p/12D3KooWQL5pHozX727aedpnMfHJ6R6q5zJ6utjaMmBxfqpTTCTD",
        "/ip6/2600:3c0d::f03c:94ff:fe40:328e/tcp/1211/p2p/12D3KooWQL5pHozX727aedpnMfHJ6R6q5zJ6utjaMmBxfqpTTCTD",
        "/ip6/2600:3c0d::f03c:94ff:fe40:328e/udp/1211/quic-v1/p2p/12D3KooWQL5pHozX727aedpnMfHJ6R6q5zJ6utjaMmBxfqpTTCTD",
        "/ip6/2a01:7e02::f03c:94ff:fe40:32a0/udp/1211/quic-v1/p2p/12D3KooWLJsxkVq66XSDaEMvtk3PxJSRK8DsvUcnrMkT5TwGcvBa",
        "/ip4/172.233.120.140/tcp/1211/p2p/12D3KooWLJsxkVq66XSDaEMvtk3PxJSRK8DsvUcnrMkT5TwGcvBa",
        "/ip4/172.233.120.140/udp/1211/quic-v1/p2p/12D3KooWLJsxkVq66XSDaEMvtk3PxJSRK8DsvUcnrMkT5TwGcvBa",
        "/ip6/2a01:7e02::f03c:94ff:fe40:32a0/tcp/1211/p2p/12D3KooWLJsxkVq66XSDaEMvtk3PxJSRK8DsvUcnrMkT5TwGcvBa",
        "/ip4/172.105.11.120/tcp/1211/p2p/12D3KooWSZR6o1EajQgaqWMGBEsdwPcynB5ny4Z7qwDKnZcRCNxm",
        "/ip4/172.105.11.120/udp/1211/quic-v1/p2p/12D3KooWSZR6o1EajQgaqWMGBEsdwPcynB5ny4Z7qwDKnZcRCNxm",
        "/ip6/2600:3c04::f03c:94ff:fe40:32d9/tcp/1211/p2p/12D3KooWSZR6o1EajQgaqWMGBEsdwPcynB5ny4Z7qwDKnZcRCNxm",
        "/ip6/2600:3c04::f03c:94ff:fe40:32d9/udp/1211/quic-v1/p2p/12D3KooWSZR6o1EajQgaqWMGBEsdwPcynB5ny4Z7qwDKnZcRCNxm",
        "/ip6/2600:3c08::f03c:94ff:fe40:32c9/udp/1211/quic-v1/p2p/12D3KooWQkRvxNFY8vXUy77ifkjpfbqqtWKJJiEVkJ4qWAj9PDvp",
        "/ip4/172.232.103.225/tcp/1211/p2p/12D3KooWQkRvxNFY8vXUy77ifkjpfbqqtWKJJiEVkJ4qWAj9PDvp",
        "/ip4/172.232.103.225/udp/1211/quic-v1/p2p/12D3KooWQkRvxNFY8vXUy77ifkjpfbqqtWKJJiEVkJ4qWAj9PDvp",
        "/ip6/2600:3c08::f03c:94ff:fe40:32c9/tcp/1211/p2p/12D3KooWQkRvxNFY8vXUy77ifkjpfbqqtWKJJiEVkJ4qWAj9PDvp",
        "/ip4/50.116.53.243/tcp/1211/p2p/12D3KooWG4qNqH5ua3oJT1E5T8Kt9d9qhSratk2AwWDgQbVc8ggs",
        "/ip4/50.116.53.243/udp/1211/quic-v1/p2p/12D3KooWG4qNqH5ua3oJT1E5T8Kt9d9qhSratk2AwWDgQbVc8ggs",
        "/ip6/2600:3c03::f03c:94ff:fe40:329c/tcp/1211/p2p/12D3KooWG4qNqH5ua3oJT1E5T8Kt9d9qhSratk2AwWDgQbVc8ggs",
        "/ip6/2600:3c03::f03c:94ff:fe40:329c/udp/1211/quic-v1/p2p/12D3KooWG4qNqH5ua3oJT1E5T8Kt9d9qhSratk2AwWDgQbVc8ggs",
        "/ip6/2400:8901::f03c:94ff:fe40:324b/tcp/1211/p2p/12D3KooWBrwfosiWhzG6N2LtvYv8EpBCQLNxQ3WtvryHRz1zeMRF",
        "/ip6/2400:8901::f03c:94ff:fe40:324b/udp/1211/quic-v1/p2p/12D3KooWBrwfosiWhzG6N2LtvYv8EpBCQLNxQ3WtvryHRz1zeMRF",
        "/ip4/172.104.191.84/tcp/1211/p2p/12D3KooWBrwfosiWhzG6N2LtvYv8EpBCQLNxQ3WtvryHRz1zeMRF",
        "/ip4/172.104.191.84/udp/1211/quic-v1/p2p/12D3KooWBrwfosiWhzG6N2LtvYv8EpBCQLNxQ3WtvryHRz1zeMRF",
        "/ip4/172.105.189.56/tcp/1211/p2p/12D3KooWDjPbtCYhCuigeYfTgnEZANFfgfGdoYKtwh2ZyTZp5VpJ",
        "/ip4/172.105.189.56/udp/1211/quic-v1/p2p/12D3KooWDjPbtCYhCuigeYfTgnEZANFfgfGdoYKtwh2ZyTZp5VpJ",
        "/ip6/2400:8907::f03c:94ff:fe40:320e/tcp/1211/p2p/12D3KooWDjPbtCYhCuigeYfTgnEZANFfgfGdoYKtwh2ZyTZp5VpJ",
        "/ip6/2400:8907::f03c:94ff:fe40:320e/udp/1211/quic-v1/p2p/12D3KooWDjPbtCYhCuigeYfTgnEZANFfgfGdoYKtwh2ZyTZp5VpJ",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
blockAnnouncementStringFlag: "BlockAnnouncement"
fullNodeAnnouncementStringFlag: "FullNodeAnnouncement"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
registryPath: "blocksRegistry.json"
memorySpace: 10 # in GB