windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c0e::f03c:94ff:fedc:7aa3/udp/1211/quic-v1/p2p/12D3KooWRP6eb62Rpr5otdTe7Bv1dqjKfDwA5o6FW6MJvQikosud",
        "/ip4/172.233.49.69/tcp/1211/p2p/12D3KooWRP6eb62Rpr5otdTe7Bv1dqjKfDwA5o6FW6MJvQikosud",
        "/ip4/172.233.49.69/udp/1211/quic-v1/p2p/12D3KooWRP6eb62Rpr5otdTe7Bv1dqjKfDwA5o6FW6MJvQikosud",
        "/ip6/2600:3c0e::f03c:94ff:fedc:7aa3/tcp/1211/p2p/12D3KooWRP6eb62Rpr5otdTe7Bv1dqjKfDwA5o6FW6MJvQikosud",
        "/ip6/2a01:7e00::f03c:94ff:fedc:7ab4/tcp/1211/p2p/12D3KooWBSbQZsA75EA8kuzEu1W6mZQVvKDkQT8rHXFM8uSCkNjn",
        "/ip6/2a01:7e00::f03c:94ff:fedc:7ab4/udp/1211/quic-v1/p2p/12D3KooWBSbQZsA75EA8kuzEu1W6mZQVvKDkQT8rHXFM8uSCkNjn",
        "/ip4/212.71.248.78/tcp/1211/p2p/12D3KooWBSbQZsA75EA8kuzEu1W6mZQVvKDkQT8rHXFM8uSCkNjn",
        "/ip4/212.71.248.78/udp/1211/quic-v1/p2p/12D3KooWBSbQZsA75EA8kuzEu1W6mZQVvKDkQT8rHXFM8uSCkNjn",
        "/ip6/2400:8901::f03c:94ff:fedc:7a68/udp/1211/quic-v1/p2p/12D3KooWDLfHjQzNkQJLP4x4Q7Zy3KKTYts2RzeePQJh4VUT33Bz",
        "/ip4/139.162.22.128/tcp/1211/p2p/12D3KooWDLfHjQzNkQJLP4x4Q7Zy3KKTYts2RzeePQJh4VUT33Bz",
        "/ip4/139.162.22.128/udp/1211/quic-v1/p2p/12D3KooWDLfHjQzNkQJLP4x4Q7Zy3KKTYts2RzeePQJh4VUT33Bz",
        "/ip6/2400:8901::f03c:94ff:fedc:7a68/tcp/1211/p2p/12D3KooWDLfHjQzNkQJLP4x4Q7Zy3KKTYts2RzeePQJh4VUT33Bz",
        "/ip4/45.56.108.38/tcp/1211/p2p/12D3KooWJ3c6zrsXWcsgmvayu7ZrECiZCRSvL29tewyQ4etaENs8",
        "/ip4/45.56.108.38/udp/1211/quic-v1/p2p/12D3KooWJ3c6zrsXWcsgmvayu7ZrECiZCRSvL29tewyQ4etaENs8",
        "/ip6/2600:3c03::f03c:94ff:fedc:7a5e/tcp/1211/p2p/12D3KooWJ3c6zrsXWcsgmvayu7ZrECiZCRSvL29tewyQ4etaENs8",
        "/ip6/2600:3c03::f03c:94ff:fedc:7a5e/udp/1211/quic-v1/p2p/12D3KooWJ3c6zrsXWcsgmvayu7ZrECiZCRSvL29tewyQ4etaENs8",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB