windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.232.208.85/tcp/1211/p2p/12D3KooWBFSWzWUfEoNNae3ssyjFzpRryqQRBsMJwA2ptfhijDxD",
        "/ip4/172.232.208.85/udp/1211/quic-v1/p2p/12D3KooWBFSWzWUfEoNNae3ssyjFzpRryqQRBsMJwA2ptfhijDxD",
        "/ip6/2600:3c0b::f03c:94ff:fea6:db5d/tcp/1211/p2p/12D3KooWBFSWzWUfEoNNae3ssyjFzpRryqQRBsMJwA2ptfhijDxD",
        "/ip6/2600:3c0b::f03c:94ff:fea6:db5d/udp/1211/quic-v1/p2p/12D3KooWBFSWzWUfEoNNae3ssyjFzpRryqQRBsMJwA2ptfhijDxD",
        "/ip4/172.105.114.231/tcp/1211/p2p/12D3KooWB41akoXK8pCDwtZJguJoEchhGgWEydp2iRYSEteGie2Q",
        "/ip4/172.105.114.231/udp/1211/quic-v1/p2p/12D3KooWB41akoXK8pCDwtZJguJoEchhGgWEydp2iRYSEteGie2Q",
        "/ip6/2400:8901::f03c:94ff:fea6:2ec2/tcp/1211/p2p/12D3KooWB41akoXK8pCDwtZJguJoEchhGgWEydp2iRYSEteGie2Q",
        "/ip6/2400:8901::f03c:94ff:fea6:2ec2/udp/1211/quic-v1/p2p/12D3KooWB41akoXK8pCDwtZJguJoEchhGgWEydp2iRYSEteGie2Q",
        "/ip6/2600:3c00::f03c:94ff:fea6:db44/tcp/1211/p2p/12D3KooWKqgYtFzLgNr7fhXAv7ym41ENVL6roRALiUS85F2oNdH3",
        "/ip6/2600:3c00::f03c:94ff:fea6:db44/udp/1211/quic-v1/p2p/12D3KooWKqgYtFzLgNr7fhXAv7ym41ENVL6roRALiUS85F2oNdH3",
        "/ip4/45.79.58.221/tcp/1211/p2p/12D3KooWKqgYtFzLgNr7fhXAv7ym41ENVL6roRALiUS85F2oNdH3",
        "/ip4/45.79.58.221/udp/1211/quic-v1/p2p/12D3KooWKqgYtFzLgNr7fhXAv7ym41ENVL6roRALiUS85F2oNdH3",
        "/ip4/212.71.251.190/tcp/1211/p2p/12D3KooWGCnTL5xaP4tCQxs7fAoVZwWVbhvrZHR62Qu7Q1EDjh2U",
        "/ip4/212.71.251.190/udp/1211/quic-v1/p2p/12D3KooWGCnTL5xaP4tCQxs7fAoVZwWVbhvrZHR62Qu7Q1EDjh2U",
        "/ip6/2a01:7e00::f03c:94ff:fea6:a7e0/tcp/1211/p2p/12D3KooWGCnTL5xaP4tCQxs7fAoVZwWVbhvrZHR62Qu7Q1EDjh2U",
        "/ip6/2a01:7e00::f03c:94ff:fea6:a7e0/udp/1211/quic-v1/p2p/12D3KooWGCnTL5xaP4tCQxs7fAoVZwWVbhvrZHR62Qu7Q1EDjh2U",
        "/ip6/2400:8901::f03c:94ff:fea6:2eff/udp/1211/quic-v1/p2p/12D3KooWHVwTXmpUV52Z9DG8foo7SNx2NjND8R9ancbnN6CjKjkU",
        "/ip4/45.118.134.72/tcp/1211/p2p/12D3KooWHVwTXmpUV52Z9DG8foo7SNx2NjND8R9ancbnN6CjKjkU",
        "/ip4/45.118.134.72/udp/1211/quic-v1/p2p/12D3KooWHVwTXmpUV52Z9DG8foo7SNx2NjND8R9ancbnN6CjKjkU",
        "/ip6/2400:8901::f03c:94ff:fea6:2eff/tcp/1211/p2p/12D3KooWHVwTXmpUV52Z9DG8foo7SNx2NjND8R9ancbnN6CjKjkU",
        "/ip4/172.233.74.140/tcp/1211/p2p/12D3KooWShaXjhzR7iErW1dGGmkkhx1okfDwcwt7mVdZrPyJVzAg",
        "/ip4/172.233.74.140/udp/1211/quic-v1/p2p/12D3KooWShaXjhzR7iErW1dGGmkkhx1okfDwcwt7mVdZrPyJVzAg",
        "/ip6/2400:8905::f03c:94ff:fea6:2e0f/tcp/1211/p2p/12D3KooWShaXjhzR7iErW1dGGmkkhx1okfDwcwt7mVdZrPyJVzAg",
        "/ip6/2400:8905::f03c:94ff:fea6:2e0f/udp/1211/quic-v1/p2p/12D3KooWShaXjhzR7iErW1dGGmkkhx1okfDwcwt7mVdZrPyJVzAg",
        "/ip4/172.232.208.91/tcp/1211/p2p/12D3KooWJCtA1vWZFi4G4cFpJ1RPFJJN4LMcrkQXfkx4qSoPtwYv",
        "/ip4/172.232.208.91/udp/1211/quic-v1/p2p/12D3KooWJCtA1vWZFi4G4cFpJ1RPFJJN4LMcrkQXfkx4qSoPtwYv",
        "/ip6/2600:3c0b::f03c:94ff:fea6:db2c/tcp/1211/p2p/12D3KooWJCtA1vWZFi4G4cFpJ1RPFJJN4LMcrkQXfkx4qSoPtwYv",
        "/ip6/2600:3c0b::f03c:94ff:fea6:db2c/udp/1211/quic-v1/p2p/12D3KooWJCtA1vWZFi4G4cFpJ1RPFJJN4LMcrkQXfkx4qSoPtwYv",
        "/ip4/172.233.162.36/tcp/1211/p2p/12D3KooWLVbHy8LL9UYNVNo3banBjfoM5tekCyETBp6FYJZzsH3f",
        "/ip4/172.233.162.36/udp/1211/quic-v1/p2p/12D3KooWLVbHy8LL9UYNVNo3banBjfoM5tekCyETBp6FYJZzsH3f",
        "/ip6/2a01:7e04::f03c:94ff:fea6:dbe5/tcp/1211/p2p/12D3KooWLVbHy8LL9UYNVNo3banBjfoM5tekCyETBp6FYJZzsH3f",
        "/ip6/2a01:7e04::f03c:94ff:fea6:dbe5/udp/1211/quic-v1/p2p/12D3KooWLVbHy8LL9UYNVNo3banBjfoM5tekCyETBp6FYJZzsH3f",
        "/ip4/172.105.60.114/tcp/1211/p2p/12D3KooWAdKJ86pMv66DMxQYGBk8yd3uwky8cxt6weCK9b57hSSW",
        "/ip4/172.105.60.114/udp/1211/quic-v1/p2p/12D3KooWAdKJ86pMv66DMxQYGBk8yd3uwky8cxt6weCK9b57hSSW",
        "/ip6/2400:8904::f03c:94ff:fea6:2e00/tcp/1211/p2p/12D3KooWAdKJ86pMv66DMxQYGBk8yd3uwky8cxt6weCK9b57hSSW",
        "/ip6/2400:8904::f03c:94ff:fea6:2e00/udp/1211/quic-v1/p2p/12D3KooWAdKJ86pMv66DMxQYGBk8yd3uwky8cxt6weCK9b57hSSW",
        "/ip4/172.233.17.186/tcp/1211/p2p/12D3KooWFccDrp4KjbJjtVuJfy4HQMLZ8BJoFswvAgWFZwX5CvUo",
        "/ip4/172.233.17.186/udp/1211/quic-v1/p2p/12D3KooWFccDrp4KjbJjtVuJfy4HQMLZ8BJoFswvAgWFZwX5CvUo",
        "/ip6/2600:3c0d::f03c:94ff:fea6:2e50/tcp/1211/p2p/12D3KooWFccDrp4KjbJjtVuJfy4HQMLZ8BJoFswvAgWFZwX5CvUo",
        "/ip6/2600:3c0d::f03c:94ff:fea6:2e50/udp/1211/quic-v1/p2p/12D3KooWFccDrp4KjbJjtVuJfy4HQMLZ8BJoFswvAgWFZwX5CvUo",
        "/ip4/172.105.35.180/tcp/1211/p2p/12D3KooWCXNdky5GaAx1YCzxE96p9Q1wSqTi96gGjgB4R4NeG17B",
        "/ip4/172.105.35.180/udp/1211/quic-v1/p2p/12D3KooWCXNdky5GaAx1YCzxE96p9Q1wSqTi96gGjgB4R4NeG17B",
        "/ip6/2400:8904::f03c:94ff:fea6:2e31/tcp/1211/p2p/12D3KooWCXNdky5GaAx1YCzxE96p9Q1wSqTi96gGjgB4R4NeG17B",
        "/ip6/2400:8904::f03c:94ff:fea6:2e31/udp/1211/quic-v1/p2p/12D3KooWCXNdky5GaAx1YCzxE96p9Q1wSqTi96gGjgB4R4NeG17B",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB