windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c03::f03c:94ff:fef5:d976/udp/1211/quic-v1/p2p/12D3KooWQp1GawetKx9L2Gq3ZoebZWPeD9AhT6AzxEd3xh36jHbE",
        "/ip4/45.33.86.144/tcp/1211/p2p/12D3KooWQp1GawetKx9L2Gq3ZoebZWPeD9AhT6AzxEd3xh36jHbE",
        "/ip4/45.33.86.144/udp/1211/quic-v1/p2p/12D3KooWQp1GawetKx9L2Gq3ZoebZWPeD9AhT6AzxEd3xh36jHbE",
        "/ip6/2600:3c03::f03c:94ff:fef5:d976/tcp/1211/p2p/12D3KooWQp1GawetKx9L2Gq3ZoebZWPeD9AhT6AzxEd3xh36jHbE",
        "/ip6/2a01:7e02::f03c:94ff:fef5:d991/tcp/1211/p2p/12D3KooWRGhCPo7hRqFZhjMYn4PX6nLXwr3LvuUmKpNwF23QWnDW",
        "/ip6/2a01:7e02::f03c:94ff:fef5:d991/udp/1211/quic-v1/p2p/12D3KooWRGhCPo7hRqFZhjMYn4PX6nLXwr3LvuUmKpNwF23QWnDW",
        "/ip4/172.233.121.214/tcp/1211/p2p/12D3KooWRGhCPo7hRqFZhjMYn4PX6nLXwr3LvuUmKpNwF23QWnDW",
        "/ip4/172.233.121.214/udp/1211/quic-v1/p2p/12D3KooWRGhCPo7hRqFZhjMYn4PX6nLXwr3LvuUmKpNwF23QWnDW",
        "/ip4/172.104.53.15/udp/1211/quic-v1/p2p/12D3KooWCoRYoi19NyY8xoEi4n8bCvVaW8ECUV3Po3EXoHJPiMUo",
        "/ip6/2400:8901::f03c:94ff:fef5:d9e0/tcp/1211/p2p/12D3KooWCoRYoi19NyY8xoEi4n8bCvVaW8ECUV3Po3EXoHJPiMUo",
        "/ip6/2400:8901::f03c:94ff:fef5:d9e0/udp/1211/quic-v1/p2p/12D3KooWCoRYoi19NyY8xoEi4n8bCvVaW8ECUV3Po3EXoHJPiMUo",
        "/ip4/172.104.53.15/tcp/1211/p2p/12D3KooWCoRYoi19NyY8xoEi4n8bCvVaW8ECUV3Po3EXoHJPiMUo",
        "/ip4/172.233.49.69/tcp/1211/p2p/12D3KooWMa9a7r3AXof8TthCk2F5A7hHYUFYLFCeMX8fvnqhMcCy",
        "/ip4/172.233.49.69/udp/1211/quic-v1/p2p/12D3KooWMa9a7r3AXof8TthCk2F5A7hHYUFYLFCeMX8fvnqhMcCy",
        "/ip6/2600:3c0e::f03c:94ff:fef5:d955/tcp/1211/p2p/12D3KooWMa9a7r3AXof8TthCk2F5A7hHYUFYLFCeMX8fvnqhMcCy",
        "/ip6/2600:3c0e::f03c:94ff:fef5:d955/udp/1211/quic-v1/p2p/12D3KooWMa9a7r3AXof8TthCk2F5A7hHYUFYLFCeMX8fvnqhMcCy",
        "/ip6/2a01:7e00::f03c:94ff:fef5:d95d/udp/1211/quic-v1/p2p/12D3KooWGPQzyfJgUqeF7rL5v1hFVC4zVR7rCX7Yn9HmE8AL2ebM",
        "/ip4/212.111.43.113/tcp/1211/p2p/12D3KooWGPQzyfJgUqeF7rL5v1hFVC4zVR7rCX7Yn9HmE8AL2ebM",
        "/ip4/212.111.43.113/udp/1211/quic-v1/p2p/12D3KooWGPQzyfJgUqeF7rL5v1hFVC4zVR7rCX7Yn9HmE8AL2ebM",
        "/ip6/2a01:7e00::f03c:94ff:fef5:d95d/tcp/1211/p2p/12D3KooWGPQzyfJgUqeF7rL5v1hFVC4zVR7rCX7Yn9HmE8AL2ebM",
        "/ip4/172.235.26.215/tcp/1211/p2p/12D3KooWLoZqrQ8rcmCkY1ngcaAxpbo4DX2vm8WdkHDcxbAuv1VZ",
        "/ip4/172.235.26.215/udp/1211/quic-v1/p2p/12D3KooWLoZqrQ8rcmCkY1ngcaAxpbo4DX2vm8WdkHDcxbAuv1VZ",
        "/ip6/2600:3c08::f03c:94ff:fef5:d995/tcp/1211/p2p/12D3KooWLoZqrQ8rcmCkY1ngcaAxpbo4DX2vm8WdkHDcxbAuv1VZ",
        "/ip6/2600:3c08::f03c:94ff:fef5:d995/udp/1211/quic-v1/p2p/12D3KooWLoZqrQ8rcmCkY1ngcaAxpbo4DX2vm8WdkHDcxbAuv1VZ",
        "/ip4/172.105.104.135/tcp/1211/p2p/12D3KooWEkrT28UjpX8ywnYZ6MSaKmWFYo8zAjxBAB4XVkGiSo9x",
        "/ip4/172.105.104.135/udp/1211/quic-v1/p2p/12D3KooWEkrT28UjpX8ywnYZ6MSaKmWFYo8zAjxBAB4XVkGiSo9x",
        "/ip6/2600:3c04::f03c:94ff:fef5:d900/tcp/1211/p2p/12D3KooWEkrT28UjpX8ywnYZ6MSaKmWFYo8zAjxBAB4XVkGiSo9x",
        "/ip6/2600:3c04::f03c:94ff:fef5:d900/udp/1211/quic-v1/p2p/12D3KooWEkrT28UjpX8ywnYZ6MSaKmWFYo8zAjxBAB4XVkGiSo9x",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
blockAnnouncementStringFlag: "BlockAnnouncement"
fullNodeAnnouncementStringFlag: "FullNodeAnnouncement"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blocksRegistryJson: "blocksRegistry.json"
memorySpace: 10 # in GB