windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/139.162.50.219/tcp/1211/p2p/12D3KooWBm8mBsErpXkdQouwuLyUtBdRHQVqKyRCvTzazRADX5cT",
        "/ip4/139.162.50.219/udp/1211/quic-v1/p2p/12D3KooWBm8mBsErpXkdQouwuLyUtBdRHQVqKyRCvTzazRADX5cT",
        "/ip6/2400:8901::f03c:94ff:fe72:afff/tcp/1211/p2p/12D3KooWBm8mBsErpXkdQouwuLyUtBdRHQVqKyRCvTzazRADX5cT",
        "/ip6/2400:8901::f03c:94ff:fe72:afff/udp/1211/quic-v1/p2p/12D3KooWBm8mBsErpXkdQouwuLyUtBdRHQVqKyRCvTzazRADX5cT",
        "/ip4/172.105.189.151/tcp/1211/p2p/12D3KooWBAjr2eVhfyDsrTEzRQA6Aw8DpsuGg6zNqNNSEQcpZ2Fw",
        "/ip4/172.105.189.151/udp/1211/quic-v1/p2p/12D3KooWBAjr2eVhfyDsrTEzRQA6Aw8DpsuGg6zNqNNSEQcpZ2Fw",
        "/ip6/2400:8907::f03c:94ff:fe72:af52/tcp/1211/p2p/12D3KooWBAjr2eVhfyDsrTEzRQA6Aw8DpsuGg6zNqNNSEQcpZ2Fw",
        "/ip6/2400:8907::f03c:94ff:fe72:af52/udp/1211/quic-v1/p2p/12D3KooWBAjr2eVhfyDsrTEzRQA6Aw8DpsuGg6zNqNNSEQcpZ2Fw",
        "/ip4/172.232.115.15/udp/1211/quic-v1/p2p/12D3KooWB7mdk7draVgAkP8BhSxfWptsyjohgZfJ1ohuRTVexJek",
        "/ip6/2600:3c08::f03c:94ff:fe72:af51/tcp/1211/p2p/12D3KooWB7mdk7draVgAkP8BhSxfWptsyjohgZfJ1ohuRTVexJek",
        "/ip6/2600:3c08::f03c:94ff:fe72:af51/udp/1211/quic-v1/p2p/12D3KooWB7mdk7draVgAkP8BhSxfWptsyjohgZfJ1ohuRTVexJek",
        "/ip4/172.232.115.15/tcp/1211/p2p/12D3KooWB7mdk7draVgAkP8BhSxfWptsyjohgZfJ1ohuRTVexJek",
        "/ip4/139.162.249.219/tcp/1211/p2p/12D3KooWK8AtJwD65rRHzCp99EBKFdq4iZiWzNUCNuVoFLDbpPyX",
        "/ip4/139.162.249.219/udp/1211/quic-v1/p2p/12D3KooWK8AtJwD65rRHzCp99EBKFdq4iZiWzNUCNuVoFLDbpPyX",
        "/ip6/2a01:7e00::f03c:94ff:fe72:af29/tcp/1211/p2p/12D3KooWK8AtJwD65rRHzCp99EBKFdq4iZiWzNUCNuVoFLDbpPyX",
        "/ip6/2a01:7e00::f03c:94ff:fe72:af29/udp/1211/quic-v1/p2p/12D3KooWK8AtJwD65rRHzCp99EBKFdq4iZiWzNUCNuVoFLDbpPyX",
        "/ip4/172.233.61.180/udp/1211/quic-v1/p2p/12D3KooWQQZFQ21tfYCf2QEiNPmKgRTgUBwoL6zqL8pyueifAWaH",
        "/ip6/2600:3c0e::f03c:94ff:fe72:af80/tcp/1211/p2p/12D3KooWQQZFQ21tfYCf2QEiNPmKgRTgUBwoL6zqL8pyueifAWaH",
        "/ip6/2600:3c0e::f03c:94ff:fe72:af80/udp/1211/quic-v1/p2p/12D3KooWQQZFQ21tfYCf2QEiNPmKgRTgUBwoL6zqL8pyueifAWaH",
        "/ip4/172.233.61.180/tcp/1211/p2p/12D3KooWQQZFQ21tfYCf2QEiNPmKgRTgUBwoL6zqL8pyueifAWaH",
        "/ip4/172.105.98.178/tcp/1211/p2p/12D3KooWChs4Vp67h2aUzkM7uHgiYY7qGP2F7k7RY1k9JeV8deyg",
        "/ip4/172.105.98.178/udp/1211/quic-v1/p2p/12D3KooWChs4Vp67h2aUzkM7uHgiYY7qGP2F7k7RY1k9JeV8deyg",
        "/ip6/2600:3c04::f03c:94ff:fe72:af11/tcp/1211/p2p/12D3KooWChs4Vp67h2aUzkM7uHgiYY7qGP2F7k7RY1k9JeV8deyg",
        "/ip6/2600:3c04::f03c:94ff:fe72:af11/udp/1211/quic-v1/p2p/12D3KooWChs4Vp67h2aUzkM7uHgiYY7qGP2F7k7RY1k9JeV8deyg",
        "/ip6/2600:3c03::f03c:94ff:fe72:af5c/udp/1211/quic-v1/p2p/12D3KooWDNXSsJfjLs9DVWrjBnj8tDxX3WzoWqGY86fss2hvnKHo",
        "/ip4/45.79.175.236/tcp/1211/p2p/12D3KooWDNXSsJfjLs9DVWrjBnj8tDxX3WzoWqGY86fss2hvnKHo",
        "/ip4/45.79.175.236/udp/1211/quic-v1/p2p/12D3KooWDNXSsJfjLs9DVWrjBnj8tDxX3WzoWqGY86fss2hvnKHo",
        "/ip6/2600:3c03::f03c:94ff:fe72:af5c/tcp/1211/p2p/12D3KooWDNXSsJfjLs9DVWrjBnj8tDxX3WzoWqGY86fss2hvnKHo",
        "/ip4/172.233.121.225/tcp/1211/p2p/12D3KooWE59eFS62x8n5H4s9vu9TyKY7zk8T9ofmYKPZmTHbTskd",
        "/ip4/172.233.121.225/udp/1211/quic-v1/p2p/12D3KooWE59eFS62x8n5H4s9vu9TyKY7zk8T9ofmYKPZmTHbTskd",
        "/ip6/2a01:7e02::f03c:94ff:fe72:afec/tcp/1211/p2p/12D3KooWE59eFS62x8n5H4s9vu9TyKY7zk8T9ofmYKPZmTHbTskd",
        "/ip6/2a01:7e02::f03c:94ff:fe72:afec/udp/1211/quic-v1/p2p/12D3KooWE59eFS62x8n5H4s9vu9TyKY7zk8T9ofmYKPZmTHbTskd",
        "/ip4/172.233.15.107/tcp/1211/p2p/12D3KooWJWtCiczdeiGJrDBrMYR9QC2NncAHUP2mDFXFCyLZSjiJ",
        "/ip4/172.233.15.107/udp/1211/quic-v1/p2p/12D3KooWJWtCiczdeiGJrDBrMYR9QC2NncAHUP2mDFXFCyLZSjiJ",
        "/ip6/2600:3c0d::f03c:94ff:fe72:afad/tcp/1211/p2p/12D3KooWJWtCiczdeiGJrDBrMYR9QC2NncAHUP2mDFXFCyLZSjiJ",
        "/ip6/2600:3c0d::f03c:94ff:fe72:afad/udp/1211/quic-v1/p2p/12D3KooWJWtCiczdeiGJrDBrMYR9QC2NncAHUP2mDFXFCyLZSjiJ",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB