windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c08::f03c:94ff:fe80:1278/udp/1211/quic-v1/p2p/12D3KooWJkqfBo88iNZpJFUa8e9Y4xp2jq93bRUyEZqJfXHfKNbs",
        "/ip4/172.235.13.6/tcp/1211/p2p/12D3KooWJkqfBo88iNZpJFUa8e9Y4xp2jq93bRUyEZqJfXHfKNbs",
        "/ip4/172.235.13.6/udp/1211/quic-v1/p2p/12D3KooWJkqfBo88iNZpJFUa8e9Y4xp2jq93bRUyEZqJfXHfKNbs",
        "/ip6/2600:3c08::f03c:94ff:fe80:1278/tcp/1211/p2p/12D3KooWJkqfBo88iNZpJFUa8e9Y4xp2jq93bRUyEZqJfXHfKNbs",
        "/ip6/2a01:7e02::f03c:94ff:fe80:1266/udp/1211/quic-v1/p2p/12D3KooWByFjBpjpo7ssCRYdrGCr8Z2GX38tA4CXXtSUAVAoUwcW",
        "/ip4/172.233.115.23/tcp/1211/p2p/12D3KooWByFjBpjpo7ssCRYdrGCr8Z2GX38tA4CXXtSUAVAoUwcW",
        "/ip4/172.233.115.23/udp/1211/quic-v1/p2p/12D3KooWByFjBpjpo7ssCRYdrGCr8Z2GX38tA4CXXtSUAVAoUwcW",
        "/ip6/2a01:7e02::f03c:94ff:fe80:1266/tcp/1211/p2p/12D3KooWByFjBpjpo7ssCRYdrGCr8Z2GX38tA4CXXtSUAVAoUwcW",
        "/ip4/172.105.117.9/tcp/1211/p2p/12D3KooWSSaE3HBDs7eibQdfGTHiYXnfkNacsvbZAYL7N3yXWYGU",
        "/ip4/172.105.117.9/udp/1211/quic-v1/p2p/12D3KooWSSaE3HBDs7eibQdfGTHiYXnfkNacsvbZAYL7N3yXWYGU",
        "/ip6/2400:8901::f03c:94ff:fe80:12e7/tcp/1211/p2p/12D3KooWSSaE3HBDs7eibQdfGTHiYXnfkNacsvbZAYL7N3yXWYGU",
        "/ip6/2400:8901::f03c:94ff:fe80:12e7/udp/1211/quic-v1/p2p/12D3KooWSSaE3HBDs7eibQdfGTHiYXnfkNacsvbZAYL7N3yXWYGU",
        "/ip4/213.219.37.207/tcp/1211/p2p/12D3KooWFHGTdnDAYXJozUj3VTCcX1P2x6tASaa1EYuRoN27HHNg",
        "/ip4/213.219.37.207/udp/1211/quic-v1/p2p/12D3KooWFHGTdnDAYXJozUj3VTCcX1P2x6tASaa1EYuRoN27HHNg",
        "/ip6/2a01:7e00::f03c:94ff:fe80:123c/tcp/1211/p2p/12D3KooWFHGTdnDAYXJozUj3VTCcX1P2x6tASaa1EYuRoN27HHNg",
        "/ip6/2a01:7e00::f03c:94ff:fe80:123c/udp/1211/quic-v1/p2p/12D3KooWFHGTdnDAYXJozUj3VTCcX1P2x6tASaa1EYuRoN27HHNg",
        "/ip4/45.33.85.13/tcp/1211/p2p/12D3KooWLtLCKFsng1ZmFg31Ua6TkG3PCasvvAYuDKoPyaEE1jRy",
        "/ip4/45.33.85.13/udp/1211/quic-v1/p2p/12D3KooWLtLCKFsng1ZmFg31Ua6TkG3PCasvvAYuDKoPyaEE1jRy",
        "/ip6/2600:3c03::f03c:94ff:fe80:12ce/tcp/1211/p2p/12D3KooWLtLCKFsng1ZmFg31Ua6TkG3PCasvvAYuDKoPyaEE1jRy",
        "/ip6/2600:3c03::f03c:94ff:fe80:12ce/udp/1211/quic-v1/p2p/12D3KooWLtLCKFsng1ZmFg31Ua6TkG3PCasvvAYuDKoPyaEE1jRy",
        "/ip4/192.53.121.142/tcp/1211/p2p/12D3KooWMMK75vKZC3gnht8YeFhvKyi4mrPKmvQ3E9y7nezRivmN",
        "/ip4/192.53.121.142/udp/1211/quic-v1/p2p/12D3KooWMMK75vKZC3gnht8YeFhvKyi4mrPKmvQ3E9y7nezRivmN",
        "/ip6/2600:3c04::f03c:94ff:fe80:122c/tcp/1211/p2p/12D3KooWMMK75vKZC3gnht8YeFhvKyi4mrPKmvQ3E9y7nezRivmN",
        "/ip6/2600:3c04::f03c:94ff:fe80:122c/udp/1211/quic-v1/p2p/12D3KooWMMK75vKZC3gnht8YeFhvKyi4mrPKmvQ3E9y7nezRivmN",
        "/ip4/172.233.38.171/tcp/1211/p2p/12D3KooWBKTKQiLxJCqTwwfeXtA7GPeVYbibJHLrgDcEx7Nx8D9c",
        "/ip4/172.233.38.171/udp/1211/quic-v1/p2p/12D3KooWBKTKQiLxJCqTwwfeXtA7GPeVYbibJHLrgDcEx7Nx8D9c",
        "/ip6/2600:3c0e::f03c:94ff:fe80:1230/tcp/1211/p2p/12D3KooWBKTKQiLxJCqTwwfeXtA7GPeVYbibJHLrgDcEx7Nx8D9c",
        "/ip6/2600:3c0e::f03c:94ff:fe80:1230/udp/1211/quic-v1/p2p/12D3KooWBKTKQiLxJCqTwwfeXtA7GPeVYbibJHLrgDcEx7Nx8D9c",
        "/ip6/2600:3c04::f03c:94ff:fe80:128c/tcp/1211/p2p/12D3KooWRvn7omggyzMkCaRD6hwMLfmWrnpMLoyX2thV1FJSHND8",
        "/ip6/2600:3c04::f03c:94ff:fe80:128c/udp/1211/quic-v1/p2p/12D3KooWRvn7omggyzMkCaRD6hwMLfmWrnpMLoyX2thV1FJSHND8",
        "/ip4/192.53.121.141/tcp/1211/p2p/12D3KooWRvn7omggyzMkCaRD6hwMLfmWrnpMLoyX2thV1FJSHND8",
        "/ip4/192.53.121.141/udp/1211/quic-v1/p2p/12D3KooWRvn7omggyzMkCaRD6hwMLfmWrnpMLoyX2thV1FJSHND8",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB