windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.233.121.117/tcp/1211/p2p/12D3KooWCHGr2xHYFBcEPKbdp1NFHciYSXc7BiRLHfXKWsedaGo8",
        "/ip4/172.233.121.117/udp/1211/quic-v1/p2p/12D3KooWCHGr2xHYFBcEPKbdp1NFHciYSXc7BiRLHfXKWsedaGo8",
        "/ip6/2a01:7e02::f03c:94ff:fe40:65d/tcp/1211/p2p/12D3KooWCHGr2xHYFBcEPKbdp1NFHciYSXc7BiRLHfXKWsedaGo8",
        "/ip6/2a01:7e02::f03c:94ff:fe40:65d/udp/1211/quic-v1/p2p/12D3KooWCHGr2xHYFBcEPKbdp1NFHciYSXc7BiRLHfXKWsedaGo8",
        "/ip4/97.107.135.203/tcp/1211/p2p/12D3KooWQM38Zi3dhcMXsnDz5G3hD5C7a72tWUHcNHZ3xNNxZdYD",
        "/ip4/97.107.135.203/udp/1211/quic-v1/p2p/12D3KooWQM38Zi3dhcMXsnDz5G3hD5C7a72tWUHcNHZ3xNNxZdYD",
        "/ip6/2600:3c03::f03c:94ff:fe40:69f/tcp/1211/p2p/12D3KooWQM38Zi3dhcMXsnDz5G3hD5C7a72tWUHcNHZ3xNNxZdYD",
        "/ip6/2600:3c03::f03c:94ff:fe40:69f/udp/1211/quic-v1/p2p/12D3KooWQM38Zi3dhcMXsnDz5G3hD5C7a72tWUHcNHZ3xNNxZdYD",
        "/ip4/172.105.105.151/tcp/1211/p2p/12D3KooWJV4ixBevkwSypVtiCLvMaS981hqNqh82MoMxFVdNsTSe",
        "/ip4/172.105.105.151/udp/1211/quic-v1/p2p/12D3KooWJV4ixBevkwSypVtiCLvMaS981hqNqh82MoMxFVdNsTSe",
        "/ip6/2600:3c04::f03c:94ff:fe40:67e/tcp/1211/p2p/12D3KooWJV4ixBevkwSypVtiCLvMaS981hqNqh82MoMxFVdNsTSe",
        "/ip6/2600:3c04::f03c:94ff:fe40:67e/udp/1211/quic-v1/p2p/12D3KooWJV4ixBevkwSypVtiCLvMaS981hqNqh82MoMxFVdNsTSe",
        "/ip4/172.105.177.169/udp/1211/quic-v1/p2p/12D3KooWGAF6ujQDTsXV51j53c7PWB7JG6pJW5KY9TsqF5iwnX8d",
        "/ip6/2400:8907::f03c:94ff:fe40:6c1/tcp/1211/p2p/12D3KooWGAF6ujQDTsXV51j53c7PWB7JG6pJW5KY9TsqF5iwnX8d",
        "/ip6/2400:8907::f03c:94ff:fe40:6c1/udp/1211/quic-v1/p2p/12D3KooWGAF6ujQDTsXV51j53c7PWB7JG6pJW5KY9TsqF5iwnX8d",
        "/ip4/172.105.177.169/tcp/1211/p2p/12D3KooWGAF6ujQDTsXV51j53c7PWB7JG6pJW5KY9TsqF5iwnX8d",
        "/ip4/172.232.115.247/tcp/1211/p2p/12D3KooWGmcjHGjFvQGKEoSqfx1xgqapQ85oNwgCjjrSDM3aZfCh",
        "/ip4/172.232.115.247/udp/1211/quic-v1/p2p/12D3KooWGmcjHGjFvQGKEoSqfx1xgqapQ85oNwgCjjrSDM3aZfCh",
        "/ip6/2600:3c08::f03c:94ff:fe40:65e/tcp/1211/p2p/12D3KooWGmcjHGjFvQGKEoSqfx1xgqapQ85oNwgCjjrSDM3aZfCh",
        "/ip6/2600:3c08::f03c:94ff:fe40:65e/udp/1211/quic-v1/p2p/12D3KooWGmcjHGjFvQGKEoSqfx1xgqapQ85oNwgCjjrSDM3aZfCh",
        "/ip4/139.162.192.195/tcp/1211/p2p/12D3KooWSYwnofKMaCoFJW268LrRdqns89PMS3fESY2Un8rh8RPp",
        "/ip4/139.162.192.195/udp/1211/quic-v1/p2p/12D3KooWSYwnofKMaCoFJW268LrRdqns89PMS3fESY2Un8rh8RPp",
        "/ip6/2a01:7e00::f03c:94ff:fe40:610/tcp/1211/p2p/12D3KooWSYwnofKMaCoFJW268LrRdqns89PMS3fESY2Un8rh8RPp",
        "/ip6/2a01:7e00::f03c:94ff:fe40:610/udp/1211/quic-v1/p2p/12D3KooWSYwnofKMaCoFJW268LrRdqns89PMS3fESY2Un8rh8RPp",
        "/ip4/172.233.27.107/tcp/1211/p2p/12D3KooWKkzHApqQz1mC6Cy61fuUFi3L6wp5UVeVM6CrvR5ePJ1j",
        "/ip4/172.233.27.107/udp/1211/quic-v1/p2p/12D3KooWKkzHApqQz1mC6Cy61fuUFi3L6wp5UVeVM6CrvR5ePJ1j",
        "/ip6/2600:3c0d::f03c:94ff:fe40:62d/tcp/1211/p2p/12D3KooWKkzHApqQz1mC6Cy61fuUFi3L6wp5UVeVM6CrvR5ePJ1j",
        "/ip6/2600:3c0d::f03c:94ff:fe40:62d/udp/1211/quic-v1/p2p/12D3KooWKkzHApqQz1mC6Cy61fuUFi3L6wp5UVeVM6CrvR5ePJ1j",
        "/ip4/172.233.61.106/tcp/1211/p2p/12D3KooWJH1Db3B7meWR1UrLJByfKqk4TWurKXWprREpKyfo5doy",
        "/ip4/172.233.61.106/udp/1211/quic-v1/p2p/12D3KooWJH1Db3B7meWR1UrLJByfKqk4TWurKXWprREpKyfo5doy",
        "/ip6/2600:3c0e::f03c:94ff:fe40:6cb/tcp/1211/p2p/12D3KooWJH1Db3B7meWR1UrLJByfKqk4TWurKXWprREpKyfo5doy",
        "/ip6/2600:3c0e::f03c:94ff:fe40:6cb/udp/1211/quic-v1/p2p/12D3KooWJH1Db3B7meWR1UrLJByfKqk4TWurKXWprREpKyfo5doy",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
blockAnnouncementStringFlag: "BlockAnnouncement"
fullNodeAnnouncementStringFlag: "FullNodeAnnouncement"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
registryPath: "blocksRegistry.json"
memorySpace: 10 # in GB