windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/45.56.108.217/tcp/1211/p2p/12D3KooWMQXZRE37AVpfzm6ujiuio3qy5KECDjb6Q1zs6jtgAs2G",
        "/ip4/45.56.108.217/udp/1211/quic-v1/p2p/12D3KooWMQXZRE37AVpfzm6ujiuio3qy5KECDjb6Q1zs6jtgAs2G",
        "/ip6/2600:3c03::f03c:94ff:fe29:24ff/tcp/1211/p2p/12D3KooWMQXZRE37AVpfzm6ujiuio3qy5KECDjb6Q1zs6jtgAs2G",
        "/ip6/2600:3c03::f03c:94ff:fe29:24ff/udp/1211/quic-v1/p2p/12D3KooWMQXZRE37AVpfzm6ujiuio3qy5KECDjb6Q1zs6jtgAs2G",
        "/ip4/172.233.61.241/tcp/1211/p2p/12D3KooWFVk7JZ5wyArtKh1Uh8uaEZW5o3ovxCXYpXeAitSbbahe",
        "/ip4/172.233.61.241/udp/1211/quic-v1/p2p/12D3KooWFVk7JZ5wyArtKh1Uh8uaEZW5o3ovxCXYpXeAitSbbahe",
        "/ip6/2600:3c0e::f03c:94ff:fe29:248a/tcp/1211/p2p/12D3KooWFVk7JZ5wyArtKh1Uh8uaEZW5o3ovxCXYpXeAitSbbahe",
        "/ip6/2600:3c0e::f03c:94ff:fe29:248a/udp/1211/quic-v1/p2p/12D3KooWFVk7JZ5wyArtKh1Uh8uaEZW5o3ovxCXYpXeAitSbbahe",
        "/ip4/176.58.107.233/tcp/1211/p2p/12D3KooWGkM8TMDq3rJM3SirM2ouDuJ43qjeVqzDhfTxXd1cm8av",
        "/ip4/176.58.107.233/udp/1211/quic-v1/p2p/12D3KooWGkM8TMDq3rJM3SirM2ouDuJ43qjeVqzDhfTxXd1cm8av",
        "/ip6/2a01:7e00::f03c:94ff:fe29:247e/tcp/1211/p2p/12D3KooWGkM8TMDq3rJM3SirM2ouDuJ43qjeVqzDhfTxXd1cm8av",
        "/ip6/2a01:7e00::f03c:94ff:fe29:247e/udp/1211/quic-v1/p2p/12D3KooWGkM8TMDq3rJM3SirM2ouDuJ43qjeVqzDhfTxXd1cm8av",
        "/ip4/172.233.107.162/tcp/1211/p2p/12D3KooWHPBVAq4cfnGPTTVmGom19sP1e7UZzJABQiX9beZGEg1h",
        "/ip4/172.233.107.162/udp/1211/quic-v1/p2p/12D3KooWHPBVAq4cfnGPTTVmGom19sP1e7UZzJABQiX9beZGEg1h",
        "/ip6/2a01:7e02::f03c:94ff:fe29:24fb/tcp/1211/p2p/12D3KooWHPBVAq4cfnGPTTVmGom19sP1e7UZzJABQiX9beZGEg1h",
        "/ip6/2a01:7e02::f03c:94ff:fe29:24fb/udp/1211/quic-v1/p2p/12D3KooWHPBVAq4cfnGPTTVmGom19sP1e7UZzJABQiX9beZGEg1h",
        "/ip4/172.104.173.196/tcp/1211/p2p/12D3KooWSPHNsepveToTDHVBixrsdXfPvo3XeGV4X5TMydHJb2Yt",
        "/ip4/172.104.173.196/udp/1211/quic-v1/p2p/12D3KooWSPHNsepveToTDHVBixrsdXfPvo3XeGV4X5TMydHJb2Yt",
        "/ip6/2400:8901::f03c:94ff:fe29:2458/tcp/1211/p2p/12D3KooWSPHNsepveToTDHVBixrsdXfPvo3XeGV4X5TMydHJb2Yt",
        "/ip6/2400:8901::f03c:94ff:fe29:2458/udp/1211/quic-v1/p2p/12D3KooWSPHNsepveToTDHVBixrsdXfPvo3XeGV4X5TMydHJb2Yt",
        "/ip4/172.235.28.42/tcp/1211/p2p/12D3KooWLLAHDU3FVBaFoyzWrfT1vS5YEAu8PojL8zLxnsZpURBC",
        "/ip4/172.235.28.42/udp/1211/quic-v1/p2p/12D3KooWLLAHDU3FVBaFoyzWrfT1vS5YEAu8PojL8zLxnsZpURBC",
        "/ip6/2600:3c08::f03c:94ff:fe29:241c/tcp/1211/p2p/12D3KooWLLAHDU3FVBaFoyzWrfT1vS5YEAu8PojL8zLxnsZpURBC",
        "/ip6/2600:3c08::f03c:94ff:fe29:241c/udp/1211/quic-v1/p2p/12D3KooWLLAHDU3FVBaFoyzWrfT1vS5YEAu8PojL8zLxnsZpURBC",
        "/ip6/2400:8907::f03c:94ff:fe29:246a/tcp/1211/p2p/12D3KooWFioFeQv73hfCNDpm2ys6srNWwpZuuwLc5VTUHUE8RtFr",
        "/ip6/2400:8907::f03c:94ff:fe29:246a/udp/1211/quic-v1/p2p/12D3KooWFioFeQv73hfCNDpm2ys6srNWwpZuuwLc5VTUHUE8RtFr",
        "/ip4/172.105.179.37/tcp/1211/p2p/12D3KooWFioFeQv73hfCNDpm2ys6srNWwpZuuwLc5VTUHUE8RtFr",
        "/ip4/172.105.179.37/udp/1211/quic-v1/p2p/12D3KooWFioFeQv73hfCNDpm2ys6srNWwpZuuwLc5VTUHUE8RtFr",
        "/ip4/172.233.15.170/tcp/1211/p2p/12D3KooWJqhq8bPrFwjGBuaynnLZEzGwGoq2CGoRwVPo2ZzHXF4u",
        "/ip4/172.233.15.170/udp/1211/quic-v1/p2p/12D3KooWJqhq8bPrFwjGBuaynnLZEzGwGoq2CGoRwVPo2ZzHXF4u",
        "/ip6/2600:3c0d::f03c:94ff:fe29:243f/tcp/1211/p2p/12D3KooWJqhq8bPrFwjGBuaynnLZEzGwGoq2CGoRwVPo2ZzHXF4u",
        "/ip6/2600:3c0d::f03c:94ff:fe29:243f/udp/1211/quic-v1/p2p/12D3KooWJqhq8bPrFwjGBuaynnLZEzGwGoq2CGoRwVPo2ZzHXF4u",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
blockAnnouncementStringFlag: "BlockAnnouncement"
fullNodeAnnouncementStringFlag: "FullNodeAnnouncement"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blocksRegistryJson: "blocksRegistry.json"
memorySpace: 10 # in GB