windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.233.51.143/tcp/1211/p2p/12D3KooWSwvEJiTEEqGg1ZhN4bBkqhYU7z7ZFv5Nj8Waxa6ivZ1i",
        "/ip4/172.233.51.143/udp/1211/quic-v1/p2p/12D3KooWSwvEJiTEEqGg1ZhN4bBkqhYU7z7ZFv5Nj8Waxa6ivZ1i",
        "/ip6/2600:3c0e::f03c:94ff:fef9:1b00/tcp/1211/p2p/12D3KooWSwvEJiTEEqGg1ZhN4bBkqhYU7z7ZFv5Nj8Waxa6ivZ1i",
        "/ip6/2600:3c0e::f03c:94ff:fef9:1b00/udp/1211/quic-v1/p2p/12D3KooWSwvEJiTEEqGg1ZhN4bBkqhYU7z7ZFv5Nj8Waxa6ivZ1i",
        "/ip4/45.33.76.49/tcp/1211/p2p/12D3KooWFAihBcbMLyVKrN9PMTHg1MHY4ign9DnLKWagn293nhNQ",
        "/ip4/45.33.76.49/udp/1211/quic-v1/p2p/12D3KooWFAihBcbMLyVKrN9PMTHg1MHY4ign9DnLKWagn293nhNQ",
        "/ip6/2600:3c03::f03c:94ff:fef9:1b02/tcp/1211/p2p/12D3KooWFAihBcbMLyVKrN9PMTHg1MHY4ign9DnLKWagn293nhNQ",
        "/ip6/2600:3c03::f03c:94ff:fef9:1b02/udp/1211/quic-v1/p2p/12D3KooWFAihBcbMLyVKrN9PMTHg1MHY4ign9DnLKWagn293nhNQ",
        "/ip4/178.79.133.23/tcp/1211/p2p/12D3KooWBb2xJU2SxsGrxq878mD1U8nqDpA8mRcPd7YA4vkgRHtB",
        "/ip4/178.79.133.23/udp/1211/quic-v1/p2p/12D3KooWBb2xJU2SxsGrxq878mD1U8nqDpA8mRcPd7YA4vkgRHtB",
        "/ip6/2a01:7e00::f03c:94ff:fef9:1b44/tcp/1211/p2p/12D3KooWBb2xJU2SxsGrxq878mD1U8nqDpA8mRcPd7YA4vkgRHtB",
        "/ip6/2a01:7e00::f03c:94ff:fef9:1b44/udp/1211/quic-v1/p2p/12D3KooWBb2xJU2SxsGrxq878mD1U8nqDpA8mRcPd7YA4vkgRHtB",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
blocAnnouncementStringFlag: "BlocAnnouncement"
fullNodeAnnouncementStringFlag: "FullNodeAnnouncement"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blocksRegistryJson: "blocksRegistry.json"
memorySpace: 10 # in GB