windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.233.51.204/tcp/1211/p2p/12D3KooWPDvZv8CTR9MPf1nUAnT1BnVwageopmbAcwQPj7AgLph2",
        "/ip4/172.233.51.204/udp/1211/quic-v1/p2p/12D3KooWPDvZv8CTR9MPf1nUAnT1BnVwageopmbAcwQPj7AgLph2",
        "/ip6/2600:3c0e::f03c:94ff:fe42:50f9/tcp/1211/p2p/12D3KooWPDvZv8CTR9MPf1nUAnT1BnVwageopmbAcwQPj7AgLph2",
        "/ip6/2600:3c0e::f03c:94ff:fe42:50f9/udp/1211/quic-v1/p2p/12D3KooWPDvZv8CTR9MPf1nUAnT1BnVwageopmbAcwQPj7AgLph2",
        # "/ip4/172.233.26.81/tcp/1211/p2p/12D3KooW9yRUMgkWhjjgeHG2wULYrSuATuTPGEEECa5Z2yYMzrTS",
        # "/ip4/172.233.26.81/udp/1211/quic-v1/p2p/12D3KooW9yRUMgkWhjjgeHG2wULYrSuATuTPGEEECa5Z2yYMzrTS",
        # "/ip6/2600:3c0d::f03c:94ff:fe42:5035/tcp/1211/p2p/12D3KooW9yRUMgkWhjjgeHG2wULYrSuATuTPGEEECa5Z2yYMzrTS",
        # "/ip6/2600:3c0d::f03c:94ff:fe42:5035/udp/1211/quic-v1/p2p/12D3KooW9yRUMgkWhjjgeHG2wULYrSuATuTPGEEECa5Z2yYMzrTS",
        # "/ip4/172.105.114.64/tcp/1211/p2p/12D3KooWHowambKrqFrrCQGxJ5deAiV9JxYUgfr56XB9CDZGDKag",
        # "/ip4/172.105.114.64/udp/1211/quic-v1/p2p/12D3KooWHowambKrqFrrCQGxJ5deAiV9JxYUgfr56XB9CDZGDKag",
        # "/ip6/2400:8901::f03c:94ff:fe42:50e8/tcp/1211/p2p/12D3KooWHowambKrqFrrCQGxJ5deAiV9JxYUgfr56XB9CDZGDKag",
        # "/ip6/2400:8901::f03c:94ff:fe42:50e8/udp/1211/quic-v1/p2p/12D3KooWHowambKrqFrrCQGxJ5deAiV9JxYUgfr56XB9CDZGDKag",
        # "/ip4/172.232.114.48/tcp/1211/p2p/12D3KooWK8UinUNwod47KYwFwrSEeHXZTYKm2oD6YKVKHY99eCjQ",
        # "/ip4/172.232.114.48/udp/1211/quic-v1/p2p/12D3KooWK8UinUNwod47KYwFwrSEeHXZTYKm2oD6YKVKHY99eCjQ",
        # "/ip6/2600:3c08::f03c:94ff:fe42:505a/tcp/1211/p2p/12D3KooWK8UinUNwod47KYwFwrSEeHXZTYKm2oD6YKVKHY99eCjQ",
        # "/ip6/2600:3c08::f03c:94ff:fe42:505a/udp/1211/quic-v1/p2p/12D3KooWK8UinUNwod47KYwFwrSEeHXZTYKm2oD6YKVKHY99eCjQ",
        # "/ip4/172.105.3.161/udp/1211/quic-v1/p2p/12D3KooWJcYubSH4KdLxosNrifj8CN9ZmnLDuqjdGqwLzpnitP8d",
        # "/ip6/2600:3c04::f03c:94ff:fe42:5068/tcp/1211/p2p/12D3KooWJcYubSH4KdLxosNrifj8CN9ZmnLDuqjdGqwLzpnitP8d",
        # "/ip6/2600:3c04::f03c:94ff:fe42:5068/udp/1211/quic-v1/p2p/12D3KooWJcYubSH4KdLxosNrifj8CN9ZmnLDuqjdGqwLzpnitP8d",
        # "/ip4/172.105.3.161/tcp/1211/p2p/12D3KooWJcYubSH4KdLxosNrifj8CN9ZmnLDuqjdGqwLzpnitP8d",
        # "/ip4/45.79.239.186/tcp/1211/p2p/12D3KooWKRMyHSzFFLr1zESr1E5sjoUWdWhufb7HRGC5ZYCGypMx",
        # "/ip4/45.79.239.186/udp/1211/quic-v1/p2p/12D3KooWKRMyHSzFFLr1zESr1E5sjoUWdWhufb7HRGC5ZYCGypMx",
        # "/ip6/2400:8907::f03c:94ff:fe42:507c/tcp/1211/p2p/12D3KooWKRMyHSzFFLr1zESr1E5sjoUWdWhufb7HRGC5ZYCGypMx",
        # "/ip6/2400:8907::f03c:94ff:fe42:507c/udp/1211/quic-v1/p2p/12D3KooWKRMyHSzFFLr1zESr1E5sjoUWdWhufb7HRGC5ZYCGypMx",
        # "/ip4/172.105.3.242/tcp/1211/p2p/12D3KooWG3b21mbgo8WAUbR77nEKZ1VeKmQ6vSuQwDgXZJJe3Txz",
        # "/ip4/172.105.3.242/udp/1211/quic-v1/p2p/12D3KooWG3b21mbgo8WAUbR77nEKZ1VeKmQ6vSuQwDgXZJJe3Txz",
        # "/ip6/2600:3c04::f03c:94ff:fe42:501e/tcp/1211/p2p/12D3KooWG3b21mbgo8WAUbR77nEKZ1VeKmQ6vSuQwDgXZJJe3Txz",
        # "/ip6/2600:3c04::f03c:94ff:fe42:501e/udp/1211/quic-v1/p2p/12D3KooWG3b21mbgo8WAUbR77nEKZ1VeKmQ6vSuQwDgXZJJe3Txz",
        # "/ip4/97.107.131.17/tcp/1211/p2p/12D3KooWSqyyonu1CFm4dUqMV6BdkwbSPJQUyewA7f7yyXjFm1gq",
        # "/ip4/97.107.131.17/udp/1211/quic-v1/p2p/12D3KooWSqyyonu1CFm4dUqMV6BdkwbSPJQUyewA7f7yyXjFm1gq",
        # "/ip6/2600:3c03::f03c:94ff:fe42:50cf/tcp/1211/p2p/12D3KooWSqyyonu1CFm4dUqMV6BdkwbSPJQUyewA7f7yyXjFm1gq",
        # "/ip6/2600:3c03::f03c:94ff:fe42:50cf/udp/1211/quic-v1/p2p/12D3KooWSqyyonu1CFm4dUqMV6BdkwbSPJQUyewA7f7yyXjFm1gq",
        # "/ip4/172.233.121.88/tcp/1211/p2p/12D3KooWRhUHiST8HzLwzLD4RYyk5Zt3tETFqeZCmAEJKKtRwSCk",
        # "/ip4/172.233.121.88/udp/1211/quic-v1/p2p/12D3KooWRhUHiST8HzLwzLD4RYyk5Zt3tETFqeZCmAEJKKtRwSCk",
        # "/ip6/2a01:7e02::f03c:94ff:fe42:50fd/tcp/1211/p2p/12D3KooWRhUHiST8HzLwzLD4RYyk5Zt3tETFqeZCmAEJKKtRwSCk",
        # "/ip6/2a01:7e02::f03c:94ff:fe42:50fd/udp/1211/quic-v1/p2p/12D3KooWRhUHiST8HzLwzLD4RYyk5Zt3tETFqeZCmAEJKKtRwSCk",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB