windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.26.29/udp/1211/quic-v1/p2p/12D3KooWQp9wXL33qZFQDaowaRnQiTk9Z4jBwFPeqUax4RLDkf9Q",
        "/ip6/2600:3c04::f03c:94ff:fe42:2793/tcp/1211/p2p/12D3KooWQp9wXL33qZFQDaowaRnQiTk9Z4jBwFPeqUax4RLDkf9Q",
        "/ip6/2600:3c04::f03c:94ff:fe42:2793/udp/1211/quic-v1/p2p/12D3KooWQp9wXL33qZFQDaowaRnQiTk9Z4jBwFPeqUax4RLDkf9Q",
        "/ip4/172.105.26.29/tcp/1211/p2p/12D3KooWQp9wXL33qZFQDaowaRnQiTk9Z4jBwFPeqUax4RLDkf9Q",
        "/ip4/172.235.6.38/tcp/1211/p2p/12D3KooWEyEAhXvCGmGAV1cTUPUkZuoFDvUs8ax6DF5Ffbp3xAk6",
        "/ip4/172.235.6.38/udp/1211/quic-v1/p2p/12D3KooWEyEAhXvCGmGAV1cTUPUkZuoFDvUs8ax6DF5Ffbp3xAk6",
        "/ip6/2600:3c08::f03c:94ff:fe42:2795/tcp/1211/p2p/12D3KooWEyEAhXvCGmGAV1cTUPUkZuoFDvUs8ax6DF5Ffbp3xAk6",
        "/ip6/2600:3c08::f03c:94ff:fe42:2795/udp/1211/quic-v1/p2p/12D3KooWEyEAhXvCGmGAV1cTUPUkZuoFDvUs8ax6DF5Ffbp3xAk6",
        "/ip4/172.105.187.181/tcp/1211/p2p/12D3KooWPHhBV9sx7EgPBXD5UTYRfak1Y6Y1za4VJknESpWZwQf8",
        "/ip4/172.105.187.181/udp/1211/quic-v1/p2p/12D3KooWPHhBV9sx7EgPBXD5UTYRfak1Y6Y1za4VJknESpWZwQf8",
        "/ip6/2400:8907::f03c:94ff:fe42:272f/tcp/1211/p2p/12D3KooWPHhBV9sx7EgPBXD5UTYRfak1Y6Y1za4VJknESpWZwQf8",
        "/ip6/2400:8907::f03c:94ff:fe42:272f/udp/1211/quic-v1/p2p/12D3KooWPHhBV9sx7EgPBXD5UTYRfak1Y6Y1za4VJknESpWZwQf8",
        "/ip6/2600:3c0e::f03c:94ff:fe42:27f4/tcp/1211/p2p/12D3KooWSEE3oxA4s9DnkDQNEBcEs1FWHes6KaWgi9NPGS5873ww",
        "/ip6/2600:3c0e::f03c:94ff:fe42:27f4/udp/1211/quic-v1/p2p/12D3KooWSEE3oxA4s9DnkDQNEBcEs1FWHes6KaWgi9NPGS5873ww",
        "/ip4/172.233.46.28/tcp/1211/p2p/12D3KooWSEE3oxA4s9DnkDQNEBcEs1FWHes6KaWgi9NPGS5873ww",
        "/ip4/172.233.46.28/udp/1211/quic-v1/p2p/12D3KooWSEE3oxA4s9DnkDQNEBcEs1FWHes6KaWgi9NPGS5873ww",
        "/ip4/172.233.26.81/tcp/1211/p2p/12D3KooWKRBW6917N1SbK3yeXsDHgLJyFk36J9wzMLLnSxeXVB9k",
        "/ip4/172.233.26.81/udp/1211/quic-v1/p2p/12D3KooWKRBW6917N1SbK3yeXsDHgLJyFk36J9wzMLLnSxeXVB9k",
        "/ip6/2600:3c0d::f03c:94ff:fe42:278d/tcp/1211/p2p/12D3KooWKRBW6917N1SbK3yeXsDHgLJyFk36J9wzMLLnSxeXVB9k",
        "/ip6/2600:3c0d::f03c:94ff:fe42:278d/udp/1211/quic-v1/p2p/12D3KooWKRBW6917N1SbK3yeXsDHgLJyFk36J9wzMLLnSxeXVB9k",
        "/ip4/172.233.121.88/udp/1211/quic-v1/p2p/12D3KooWLiUBaDXiQiVZu5NL88WjDbgUBFcmaQGXxYw7xPRia6e7",
        "/ip6/2a01:7e02::f03c:94ff:fe42:279c/tcp/1211/p2p/12D3KooWLiUBaDXiQiVZu5NL88WjDbgUBFcmaQGXxYw7xPRia6e7",
        "/ip6/2a01:7e02::f03c:94ff:fe42:279c/udp/1211/quic-v1/p2p/12D3KooWLiUBaDXiQiVZu5NL88WjDbgUBFcmaQGXxYw7xPRia6e7",
        "/ip4/172.233.121.88/tcp/1211/p2p/12D3KooWLiUBaDXiQiVZu5NL88WjDbgUBFcmaQGXxYw7xPRia6e7",
        "/ip6/2600:3c04::f03c:94ff:fe42:2722/tcp/1211/p2p/12D3KooWMJVZk2f9s8R3bxZTTysNrPs9u73wSRGHGt6iPhr82JrT",
        "/ip6/2600:3c04::f03c:94ff:fe42:2722/udp/1211/quic-v1/p2p/12D3KooWMJVZk2f9s8R3bxZTTysNrPs9u73wSRGHGt6iPhr82JrT",
        "/ip4/172.105.26.10/tcp/1211/p2p/12D3KooWMJVZk2f9s8R3bxZTTysNrPs9u73wSRGHGt6iPhr82JrT",
        "/ip4/172.105.26.10/udp/1211/quic-v1/p2p/12D3KooWMJVZk2f9s8R3bxZTTysNrPs9u73wSRGHGt6iPhr82JrT",
        "/ip4/97.107.131.17/tcp/1211/p2p/12D3KooWCJMcNHqhDw7pVS12QCwm9fQDPyUCmzxwfBSK9Z6psTWw",
        "/ip4/97.107.131.17/udp/1211/quic-v1/p2p/12D3KooWCJMcNHqhDw7pVS12QCwm9fQDPyUCmzxwfBSK9Z6psTWw",
        "/ip6/2600:3c03::f03c:94ff:fe42:2766/tcp/1211/p2p/12D3KooWCJMcNHqhDw7pVS12QCwm9fQDPyUCmzxwfBSK9Z6psTWw",
        "/ip6/2600:3c03::f03c:94ff:fe42:2766/udp/1211/quic-v1/p2p/12D3KooWCJMcNHqhDw7pVS12QCwm9fQDPyUCmzxwfBSK9Z6psTWw",
        "/ip4/139.162.205.87/tcp/1211/p2p/12D3KooWPPCTaNkByrCcbE46YaHAFdw8GstPr5v2Tenjwr7xTcej",
        "/ip4/139.162.205.87/udp/1211/quic-v1/p2p/12D3KooWPPCTaNkByrCcbE46YaHAFdw8GstPr5v2Tenjwr7xTcej",
        "/ip6/2a01:7e00::f03c:94ff:fe42:27d4/tcp/1211/p2p/12D3KooWPPCTaNkByrCcbE46YaHAFdw8GstPr5v2Tenjwr7xTcej",
        "/ip6/2a01:7e00::f03c:94ff:fe42:27d4/udp/1211/quic-v1/p2p/12D3KooWPPCTaNkByrCcbE46YaHAFdw8GstPr5v2Tenjwr7xTcej",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB