windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2a01:7e02::f03c:94ff:fec9:5937/tcp/1211/p2p/12D3KooWSKcfxiUfdYqhYTvmYrcRUvezMyGTbtRu8VLUBAgDB9Ge",
        "/ip6/2a01:7e02::f03c:94ff:fec9:5937/udp/1211/quic-v1/p2p/12D3KooWSKcfxiUfdYqhYTvmYrcRUvezMyGTbtRu8VLUBAgDB9Ge",
        "/ip4/172.233.111.219/tcp/1211/p2p/12D3KooWSKcfxiUfdYqhYTvmYrcRUvezMyGTbtRu8VLUBAgDB9Ge",
        "/ip4/172.233.111.219/udp/1211/quic-v1/p2p/12D3KooWSKcfxiUfdYqhYTvmYrcRUvezMyGTbtRu8VLUBAgDB9Ge",
        "/ip4/194.195.251.117/tcp/1211/p2p/12D3KooWNW62vpmyp1iZsFVd6Ea5abEXkTtf7drhmQbb8Cvx8Eon",
        "/ip4/194.195.251.117/udp/1211/quic-v1/p2p/12D3KooWNW62vpmyp1iZsFVd6Ea5abEXkTtf7drhmQbb8Cvx8Eon",
        "/ip6/2400:8907::f03c:94ff:fec9:59f4/tcp/1211/p2p/12D3KooWNW62vpmyp1iZsFVd6Ea5abEXkTtf7drhmQbb8Cvx8Eon",
        "/ip6/2400:8907::f03c:94ff:fec9:59f4/udp/1211/quic-v1/p2p/12D3KooWNW62vpmyp1iZsFVd6Ea5abEXkTtf7drhmQbb8Cvx8Eon",
        "/ip4/172.235.17.36/tcp/1211/p2p/12D3KooWF8TVpfwr8piWvdJs8Azc5yeA4HAL1QjmTp8PeBwDVXws",
        "/ip4/172.235.17.36/udp/1211/quic-v1/p2p/12D3KooWF8TVpfwr8piWvdJs8Azc5yeA4HAL1QjmTp8PeBwDVXws",
        "/ip6/2600:3c08::f03c:94ff:fec9:59eb/tcp/1211/p2p/12D3KooWF8TVpfwr8piWvdJs8Azc5yeA4HAL1QjmTp8PeBwDVXws",
        "/ip6/2600:3c08::f03c:94ff:fec9:59eb/udp/1211/quic-v1/p2p/12D3KooWF8TVpfwr8piWvdJs8Azc5yeA4HAL1QjmTp8PeBwDVXws",
        "/ip6/2600:3c03::f03c:94ff:fec9:597b/udp/1211/quic-v1/p2p/12D3KooWFvssVSmsDcjrVxGaqyrMEjPQbfT8w9iGCQ4QndshrdTy",
        "/ip4/45.33.84.147/tcp/1211/p2p/12D3KooWFvssVSmsDcjrVxGaqyrMEjPQbfT8w9iGCQ4QndshrdTy",
        "/ip4/45.33.84.147/udp/1211/quic-v1/p2p/12D3KooWFvssVSmsDcjrVxGaqyrMEjPQbfT8w9iGCQ4QndshrdTy",
        "/ip6/2600:3c03::f03c:94ff:fec9:597b/tcp/1211/p2p/12D3KooWFvssVSmsDcjrVxGaqyrMEjPQbfT8w9iGCQ4QndshrdTy",
        "/ip4/172.233.26.75/tcp/1211/p2p/12D3KooWA4qr5vyA1b1yoYNz2KqDQoxWRTHvqRyA2M5WCGFqh54T",
        "/ip4/172.233.26.75/udp/1211/quic-v1/p2p/12D3KooWA4qr5vyA1b1yoYNz2KqDQoxWRTHvqRyA2M5WCGFqh54T",
        "/ip6/2600:3c0d::f03c:94ff:fec9:5964/tcp/1211/p2p/12D3KooWA4qr5vyA1b1yoYNz2KqDQoxWRTHvqRyA2M5WCGFqh54T",
        "/ip6/2600:3c0d::f03c:94ff:fec9:5964/udp/1211/quic-v1/p2p/12D3KooWA4qr5vyA1b1yoYNz2KqDQoxWRTHvqRyA2M5WCGFqh54T",
        "/ip4/172.105.103.180/tcp/1211/p2p/12D3KooWNZyzNXUPY33sb7FCxUgiq4kwn6xhMftEtzeHqnHirnQb",
        "/ip4/172.105.103.180/udp/1211/quic-v1/p2p/12D3KooWNZyzNXUPY33sb7FCxUgiq4kwn6xhMftEtzeHqnHirnQb",
        "/ip6/2600:3c04::f03c:94ff:fec9:5961/tcp/1211/p2p/12D3KooWNZyzNXUPY33sb7FCxUgiq4kwn6xhMftEtzeHqnHirnQb",
        "/ip6/2600:3c04::f03c:94ff:fec9:5961/udp/1211/quic-v1/p2p/12D3KooWNZyzNXUPY33sb7FCxUgiq4kwn6xhMftEtzeHqnHirnQb",
        "/ip4/139.162.201.198/tcp/1211/p2p/12D3KooWRyT2UYgtAQSeJnWmdBfcgeAt278jYUNrBA2STooKkadf",
        "/ip4/139.162.201.198/udp/1211/quic-v1/p2p/12D3KooWRyT2UYgtAQSeJnWmdBfcgeAt278jYUNrBA2STooKkadf",
        "/ip6/2a01:7e00::f03c:94ff:fec9:59e6/tcp/1211/p2p/12D3KooWRyT2UYgtAQSeJnWmdBfcgeAt278jYUNrBA2STooKkadf",
        "/ip6/2a01:7e00::f03c:94ff:fec9:59e6/udp/1211/quic-v1/p2p/12D3KooWRyT2UYgtAQSeJnWmdBfcgeAt278jYUNrBA2STooKkadf",
        "/ip4/172.105.103.190/udp/1211/quic-v1/p2p/12D3KooWFPKgJkKSQdvz35wYcPiHiMV968qgMqKaVPTw8jEqAdZv",
        "/ip6/2600:3c04::f03c:94ff:fec9:5938/tcp/1211/p2p/12D3KooWFPKgJkKSQdvz35wYcPiHiMV968qgMqKaVPTw8jEqAdZv",
        "/ip6/2600:3c04::f03c:94ff:fec9:5938/udp/1211/quic-v1/p2p/12D3KooWFPKgJkKSQdvz35wYcPiHiMV968qgMqKaVPTw8jEqAdZv",
        "/ip4/172.105.103.190/tcp/1211/p2p/12D3KooWFPKgJkKSQdvz35wYcPiHiMV968qgMqKaVPTw8jEqAdZv",
        "/ip4/172.233.46.185/tcp/1211/p2p/12D3KooWAhDuAVBE7fXTpJX1qBoqCptv4Mc7Jm6USojor2NukQWs",
        "/ip4/172.233.46.185/udp/1211/quic-v1/p2p/12D3KooWAhDuAVBE7fXTpJX1qBoqCptv4Mc7Jm6USojor2NukQWs",
        "/ip6/2600:3c0e::f03c:94ff:fec9:59e2/tcp/1211/p2p/12D3KooWAhDuAVBE7fXTpJX1qBoqCptv4Mc7Jm6USojor2NukQWs",
        "/ip6/2600:3c0e::f03c:94ff:fec9:59e2/udp/1211/quic-v1/p2p/12D3KooWAhDuAVBE7fXTpJX1qBoqCptv4Mc7Jm6USojor2NukQWs",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB