windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/109.74.202.213/tcp/1211/p2p/12D3KooWAfqoGgZyQWoJMoTpJ4xnYpgSgidRxXADk5EJ22zxWXFd",
        "/ip4/109.74.202.213/udp/1211/quic-v1/p2p/12D3KooWAfqoGgZyQWoJMoTpJ4xnYpgSgidRxXADk5EJ22zxWXFd",
        "/ip6/2a01:7e00::f03c:94ff:fe42:ade9/tcp/1211/p2p/12D3KooWAfqoGgZyQWoJMoTpJ4xnYpgSgidRxXADk5EJ22zxWXFd",
        "/ip6/2a01:7e00::f03c:94ff:fe42:ade9/udp/1211/quic-v1/p2p/12D3KooWAfqoGgZyQWoJMoTpJ4xnYpgSgidRxXADk5EJ22zxWXFd",

        "/ip4/23.92.21.204/tcp/1211/p2p/12D3KooWHAnrhY1eQTHi99gLtDqYjEXbqhzjvK8uoqSRq1A377Am",
        "/ip4/23.92.21.204/udp/1211/quic-v1/p2p/12D3KooWHAnrhY1eQTHi99gLtDqYjEXbqhzjvK8uoqSRq1A377Am",
        "/ip6/2600:3c03::f03c:94ff:fe42:ada3/tcp/1211/p2p/12D3KooWHAnrhY1eQTHi99gLtDqYjEXbqhzjvK8uoqSRq1A377Am",
        "/ip6/2600:3c03::f03c:94ff:fe42:ada3/udp/1211/quic-v1/p2p/12D3KooWHAnrhY1eQTHi99gLtDqYjEXbqhzjvK8uoqSRq1A377Am",

        "/ip4/172.233.51.6/tcp/1211/p2p/12D3KooWB8tiZnTf2dCKNenwtmakkGBL4HSKKKvhswzMBzy3emCk",
        "/ip4/172.233.51.6/udp/1211/quic-v1/p2p/12D3KooWB8tiZnTf2dCKNenwtmakkGBL4HSKKKvhswzMBzy3emCk",
        "/ip6/2600:3c0e::f03c:94ff:fe42:ad98/tcp/1211/p2p/12D3KooWB8tiZnTf2dCKNenwtmakkGBL4HSKKKvhswzMBzy3emCk",
        "/ip6/2600:3c0e::f03c:94ff:fe42:ad98/udp/1211/quic-v1/p2p/12D3KooWB8tiZnTf2dCKNenwtmakkGBL4HSKKKvhswzMBzy3emCk",

        "/ip4/172.105.185.116/tcp/1211/p2p/12D3KooWL6gHvaM9RoAMobZb8qrYpdNyxfUuTD14UzNPaRp1LywB",
        "/ip4/172.105.185.116/udp/1211/quic-v1/p2p/12D3KooWL6gHvaM9RoAMobZb8qrYpdNyxfUuTD14UzNPaRp1LywB",
        "/ip6/2400:8907::f03c:94ff:fe42:ad62/tcp/1211/p2p/12D3KooWL6gHvaM9RoAMobZb8qrYpdNyxfUuTD14UzNPaRp1LywB",
        "/ip6/2400:8907::f03c:94ff:fe42:ad62/udp/1211/quic-v1/p2p/12D3KooWL6gHvaM9RoAMobZb8qrYpdNyxfUuTD14UzNPaRp1LywB",

        "/ip4/139.162.40.10/tcp/1211/p2p/12D3KooWSuu9FKA4dviDFRDTjCBG959rnVprtFu3bchikYqiG6hj",
        "/ip4/139.162.40.10/udp/1211/quic-v1/p2p/12D3KooWSuu9FKA4dviDFRDTjCBG959rnVprtFu3bchikYqiG6hj",
        "/ip6/2400:8901::f03c:94ff:fe42:ada1/tcp/1211/p2p/12D3KooWSuu9FKA4dviDFRDTjCBG959rnVprtFu3bchikYqiG6hj",
        "/ip6/2400:8901::f03c:94ff:fe42:ada1/udp/1211/quic-v1/p2p/12D3KooWSuu9FKA4dviDFRDTjCBG959rnVprtFu3bchikYqiG6hj",

        "/ip6/2a01:7e02::f03c:94ff:fe42:ad94/tcp/1211/p2p/12D3KooWRmpkUcxD9MwsDp3H2w2DDUA5d7hsx28FzDzcVdGuzMuu",
        "/ip6/2a01:7e02::f03c:94ff:fe42:ad94/udp/1211/quic-v1/p2p/12D3KooWRmpkUcxD9MwsDp3H2w2DDUA5d7hsx28FzDzcVdGuzMuu",
        "/ip4/172.233.107.50/tcp/1211/p2p/12D3KooWRmpkUcxD9MwsDp3H2w2DDUA5d7hsx28FzDzcVdGuzMuu",
        "/ip4/172.233.107.50/udp/1211/quic-v1/p2p/12D3KooWRmpkUcxD9MwsDp3H2w2DDUA5d7hsx28FzDzcVdGuzMuu",

        "/ip4/172.105.3.254/tcp/1211/p2p/12D3KooWSBQLzZnFCJ3J9Wr7aYTU4nU4fgu7pSKa5sqFwc3w4QrE",
        "/ip4/172.105.3.254/udp/1211/quic-v1/p2p/12D3KooWSBQLzZnFCJ3J9Wr7aYTU4nU4fgu7pSKa5sqFwc3w4QrE",
        "/ip6/2600:3c04::f03c:94ff:fe42:ad1e/tcp/1211/p2p/12D3KooWSBQLzZnFCJ3J9Wr7aYTU4nU4fgu7pSKa5sqFwc3w4QrE",
        "/ip6/2600:3c04::f03c:94ff:fe42:ad1e/udp/1211/quic-v1/p2p/12D3KooWSBQLzZnFCJ3J9Wr7aYTU4nU4fgu7pSKa5sqFwc3w4QrE",

        "/ip4/172.233.26.183/tcp/1211/p2p/12D3KooWBD93yHdnG2raj879qWspp2Nez8wJniDjSiiGxeSkdnm6",
        "/ip4/172.233.26.183/udp/1211/quic-v1/p2p/12D3KooWBD93yHdnG2raj879qWspp2Nez8wJniDjSiiGxeSkdnm6",
        "/ip6/2600:3c0d::f03c:94ff:fe42:adaf/tcp/1211/p2p/12D3KooWBD93yHdnG2raj879qWspp2Nez8wJniDjSiiGxeSkdnm6",
        "/ip6/2600:3c0d::f03c:94ff:fe42:adaf/udp/1211/quic-v1/p2p/12D3KooWBD93yHdnG2raj879qWspp2Nez8wJniDjSiiGxeSkdnm6",
        
        "/ip4/172.105.13.36/tcp/1211/p2p/12D3KooWGACcL6u77kZLVLbr6UxhGE6ZupkyDm72T9j4VsxrZt9u",
        "/ip4/172.105.13.36/udp/1211/quic-v1/p2p/12D3KooWGACcL6u77kZLVLbr6UxhGE6ZupkyDm72T9j4VsxrZt9u",
        "/ip6/2600:3c04::f03c:94ff:fe42:add5/tcp/1211/p2p/12D3KooWGACcL6u77kZLVLbr6UxhGE6ZupkyDm72T9j4VsxrZt9u",
        "/ip6/2600:3c04::f03c:94ff:fe42:add5/udp/1211/quic-v1/p2p/12D3KooWGACcL6u77kZLVLbr6UxhGE6ZupkyDm72T9j4VsxrZt9u",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB