windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.13.36/tcp/1211/p2p/12D3KooWLofTAbCad8de3ErePDpZgqThZoYAjWSwfaw4zL3rJ1hW",
        "/ip4/172.105.13.36/udp/1211/quic-v1/p2p/12D3KooWLofTAbCad8de3ErePDpZgqThZoYAjWSwfaw4zL3rJ1hW",
        "/ip6/2600:3c04::f03c:94ff:fe42:cd32/tcp/1211/p2p/12D3KooWLofTAbCad8de3ErePDpZgqThZoYAjWSwfaw4zL3rJ1hW",
        "/ip6/2600:3c04::f03c:94ff:fe42:cd32/udp/1211/quic-v1/p2p/12D3KooWLofTAbCad8de3ErePDpZgqThZoYAjWSwfaw4zL3rJ1hW",

        "/ip4/97.107.135.216/udp/1211/quic-v1/p2p/12D3KooWML52oJUwLX1zAM5Nvzv2ZXuFVFdrTfyankx5TtxbJKPu",
        "/ip6/2600:3c03::f03c:94ff:fe42:cd38/tcp/1211/p2p/12D3KooWML52oJUwLX1zAM5Nvzv2ZXuFVFdrTfyankx5TtxbJKPu",
        "/ip6/2600:3c03::f03c:94ff:fe42:cd38/udp/1211/quic-v1/p2p/12D3KooWML52oJUwLX1zAM5Nvzv2ZXuFVFdrTfyankx5TtxbJKPu",
        "/ip4/97.107.135.216/tcp/1211/p2p/12D3KooWML52oJUwLX1zAM5Nvzv2ZXuFVFdrTfyankx5TtxbJKPu",

        "/ip4/192.53.115.95/tcp/1211/p2p/12D3KooWPLAycbZT1o5t8wM5aWkFLQUWo9j89SnsyudWkPzaEebP",
        "/ip4/192.53.115.95/udp/1211/quic-v1/p2p/12D3KooWPLAycbZT1o5t8wM5aWkFLQUWo9j89SnsyudWkPzaEebP",
        "/ip6/2400:8901::f03c:94ff:fe42:cd08/tcp/1211/p2p/12D3KooWPLAycbZT1o5t8wM5aWkFLQUWo9j89SnsyudWkPzaEebP",
        "/ip6/2400:8901::f03c:94ff:fe42:cd08/udp/1211/quic-v1/p2p/12D3KooWPLAycbZT1o5t8wM5aWkFLQUWo9j89SnsyudWkPzaEebP",

        "/ip6/2a01:7e00::f03c:94ff:fe42:cd93/udp/1211/quic-v1/p2p/12D3KooWMWFsdeMVwhN9GPjqGW8apsi5hrDDW8zZtruepStF5u3f",
        "/ip4/176.58.113.167/tcp/1211/p2p/12D3KooWMWFsdeMVwhN9GPjqGW8apsi5hrDDW8zZtruepStF5u3f",
        "/ip4/176.58.113.167/udp/1211/quic-v1/p2p/12D3KooWMWFsdeMVwhN9GPjqGW8apsi5hrDDW8zZtruepStF5u3f",
        "/ip6/2a01:7e00::f03c:94ff:fe42:cd93/tcp/1211/p2p/12D3KooWMWFsdeMVwhN9GPjqGW8apsi5hrDDW8zZtruepStF5u3f",

        "/ip4/172.105.13.208/tcp/1211/p2p/12D3KooWJgB8cgDLHnptFCZZa2eQMwgyP3uzFh8pf35rBm2vh7hn",
        "/ip4/172.105.13.208/udp/1211/quic-v1/p2p/12D3KooWJgB8cgDLHnptFCZZa2eQMwgyP3uzFh8pf35rBm2vh7hn",
        "/ip6/2600:3c04::f03c:94ff:fe42:cde0/tcp/1211/p2p/12D3KooWJgB8cgDLHnptFCZZa2eQMwgyP3uzFh8pf35rBm2vh7hn",
        "/ip6/2600:3c04::f03c:94ff:fe42:cde0/udp/1211/quic-v1/p2p/12D3KooWJgB8cgDLHnptFCZZa2eQMwgyP3uzFh8pf35rBm2vh7hn",

        "/ip6/2600:3c0e::f03c:94ff:fe42:cd05/udp/1211/quic-v1/p2p/12D3KooWCw2poVrcKvtzfSL9BEXWYcKyZDUk9M1XKp8dca3vvN24",
        "/ip4/172.233.49.167/tcp/1211/p2p/12D3KooWCw2poVrcKvtzfSL9BEXWYcKyZDUk9M1XKp8dca3vvN24",
        "/ip4/172.233.49.167/udp/1211/quic-v1/p2p/12D3KooWCw2poVrcKvtzfSL9BEXWYcKyZDUk9M1XKp8dca3vvN24",
        "/ip6/2600:3c0e::f03c:94ff:fe42:cd05/tcp/1211/p2p/12D3KooWCw2poVrcKvtzfSL9BEXWYcKyZDUk9M1XKp8dca3vvN24",

        "/ip6/2a01:7e02::f03c:94ff:fe42:cd3c/udp/1211/quic-v1/p2p/12D3KooWD8dgmhadsTqeyodAZmnNv16KFv7ySt2ELMUo1ZNVXApU",
        "/ip4/172.233.111.219/tcp/1211/p2p/12D3KooWD8dgmhadsTqeyodAZmnNv16KFv7ySt2ELMUo1ZNVXApU",
        "/ip4/172.233.111.219/udp/1211/quic-v1/p2p/12D3KooWD8dgmhadsTqeyodAZmnNv16KFv7ySt2ELMUo1ZNVXApU",
        "/ip6/2a01:7e02::f03c:94ff:fe42:cd3c/tcp/1211/p2p/12D3KooWD8dgmhadsTqeyodAZmnNv16KFv7ySt2ELMUo1ZNVXApU",

        "/ip4/172.235.19.233/tcp/1211/p2p/12D3KooWSWUoLACQSmqoXdLhixT27bEfkxS2yFQK1AeBuXgdSrRB",
        "/ip4/172.235.19.233/udp/1211/quic-v1/p2p/12D3KooWSWUoLACQSmqoXdLhixT27bEfkxS2yFQK1AeBuXgdSrRB",
        "/ip6/2600:3c08::f03c:94ff:fe42:cdb0/tcp/1211/p2p/12D3KooWSWUoLACQSmqoXdLhixT27bEfkxS2yFQK1AeBuXgdSrRB",
        "/ip6/2600:3c08::f03c:94ff:fe42:cdb0/udp/1211/quic-v1/p2p/12D3KooWSWUoLACQSmqoXdLhixT27bEfkxS2yFQK1AeBuXgdSrRB",
        
        "/ip4/194.195.120.220/udp/1211/quic-v1/p2p/12D3KooWEfttzP3fjgsAXbafQmYQ59qjtYoWjfQzvVxzEZMoSFiD",
        "/ip6/2400:8907::f03c:94ff:fe42:cd83/tcp/1211/p2p/12D3KooWEfttzP3fjgsAXbafQmYQ59qjtYoWjfQzvVxzEZMoSFiD",
        "/ip6/2400:8907::f03c:94ff:fe42:cd83/udp/1211/quic-v1/p2p/12D3KooWEfttzP3fjgsAXbafQmYQ59qjtYoWjfQzvVxzEZMoSFiD",
        "/ip4/194.195.120.220/tcp/1211/p2p/12D3KooWEfttzP3fjgsAXbafQmYQ59qjtYoWjfQzvVxzEZMoSFiD",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB