windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/139.162.144.163/tcp/1211/p2p/12D3KooWEigksapPULkvzsfLmgFdVopKXs3zw4FGR3fdFnThxdaE",
        "/ip4/139.162.144.163/udp/1211/quic-v1/p2p/12D3KooWEigksapPULkvzsfLmgFdVopKXs3zw4FGR3fdFnThxdaE",
        "/ip6/2a01:7e01::f03c:94ff:fea6:4643/tcp/1211/p2p/12D3KooWEigksapPULkvzsfLmgFdVopKXs3zw4FGR3fdFnThxdaE",
        "/ip6/2a01:7e01::f03c:94ff:fea6:4643/udp/1211/quic-v1/p2p/12D3KooWEigksapPULkvzsfLmgFdVopKXs3zw4FGR3fdFnThxdaE",
        "/ip4/139.162.172.57/tcp/1211/p2p/12D3KooWAbVBdnzJ2xLuDSn3w23azeSTBwsAfAj1n5r3zKBXPYt6",
        "/ip4/139.162.172.57/udp/1211/quic-v1/p2p/12D3KooWAbVBdnzJ2xLuDSn3w23azeSTBwsAfAj1n5r3zKBXPYt6",
        "/ip6/2a01:7e01::f03c:94ff:fea6:9f36/tcp/1211/p2p/12D3KooWAbVBdnzJ2xLuDSn3w23azeSTBwsAfAj1n5r3zKBXPYt6",
        "/ip6/2a01:7e01::f03c:94ff:fea6:9f36/udp/1211/quic-v1/p2p/12D3KooWAbVBdnzJ2xLuDSn3w23azeSTBwsAfAj1n5r3zKBXPYt6",
        "/ip4/172.105.4.125/tcp/1211/p2p/12D3KooWFZM6rszCSQgaC1Fm8NeYBZLJux7apuG2VGEtYRBhGLLg",
        "/ip4/172.105.4.125/udp/1211/quic-v1/p2p/12D3KooWFZM6rszCSQgaC1Fm8NeYBZLJux7apuG2VGEtYRBhGLLg",
        "/ip6/2600:3c04::f03c:94ff:fea6:46ce/tcp/1211/p2p/12D3KooWFZM6rszCSQgaC1Fm8NeYBZLJux7apuG2VGEtYRBhGLLg",
        "/ip6/2600:3c04::f03c:94ff:fea6:46ce/udp/1211/quic-v1/p2p/12D3KooWFZM6rszCSQgaC1Fm8NeYBZLJux7apuG2VGEtYRBhGLLg",
        "/ip6/2400:8904::f03c:94ff:fea6:4624/tcp/1211/p2p/12D3KooWQWKexgsjKY9AFyYwN9fjptGSjxd719Q5sjBw37MSMYXH",
        "/ip6/2400:8904::f03c:94ff:fea6:4624/udp/1211/quic-v1/p2p/12D3KooWQWKexgsjKY9AFyYwN9fjptGSjxd719Q5sjBw37MSMYXH",
        "/ip4/172.105.252.243/tcp/1211/p2p/12D3KooWQWKexgsjKY9AFyYwN9fjptGSjxd719Q5sjBw37MSMYXH",
        "/ip4/172.105.252.243/udp/1211/quic-v1/p2p/12D3KooWQWKexgsjKY9AFyYwN9fjptGSjxd719Q5sjBw37MSMYXH",
        "/ip4/172.233.161.190/tcp/1211/p2p/12D3KooWNJY2ajAHUaQvjT5QxFTfXkNhKYfw72viYrFqbHXcMKoy",
        "/ip4/172.233.161.190/udp/1211/quic-v1/p2p/12D3KooWNJY2ajAHUaQvjT5QxFTfXkNhKYfw72viYrFqbHXcMKoy",
        "/ip6/2a01:7e04::f03c:94ff:fea6:4634/tcp/1211/p2p/12D3KooWNJY2ajAHUaQvjT5QxFTfXkNhKYfw72viYrFqbHXcMKoy",
        "/ip6/2a01:7e04::f03c:94ff:fea6:4634/udp/1211/quic-v1/p2p/12D3KooWNJY2ajAHUaQvjT5QxFTfXkNhKYfw72viYrFqbHXcMKoy",
        "/ip4/172.105.252.101/tcp/1211/p2p/12D3KooWCM1XCVF5gDdLw7tNDhK7PPAs3xTUxBwLtvw48tVSk6gE",
        "/ip4/172.105.252.101/udp/1211/quic-v1/p2p/12D3KooWCM1XCVF5gDdLw7tNDhK7PPAs3xTUxBwLtvw48tVSk6gE",
        "/ip6/2400:8904::f03c:94ff:fea6:4608/tcp/1211/p2p/12D3KooWCM1XCVF5gDdLw7tNDhK7PPAs3xTUxBwLtvw48tVSk6gE",
        "/ip6/2400:8904::f03c:94ff:fea6:4608/udp/1211/quic-v1/p2p/12D3KooWCM1XCVF5gDdLw7tNDhK7PPAs3xTUxBwLtvw48tVSk6gE",
        "/ip6/2400:8907::f03c:94ff:fea6:46fa/tcp/1211/p2p/12D3KooWQtApziJd5PqK3a4QoEbivD1ptgwcTvmZYmXGpnpx6HWt",
        "/ip6/2400:8907::f03c:94ff:fea6:46fa/udp/1211/quic-v1/p2p/12D3KooWQtApziJd5PqK3a4QoEbivD1ptgwcTvmZYmXGpnpx6HWt",
        "/ip4/194.195.126.139/tcp/1211/p2p/12D3KooWQtApziJd5PqK3a4QoEbivD1ptgwcTvmZYmXGpnpx6HWt",
        "/ip4/194.195.126.139/udp/1211/quic-v1/p2p/12D3KooWQtApziJd5PqK3a4QoEbivD1ptgwcTvmZYmXGpnpx6HWt",
        "/ip4/172.233.44.139/tcp/1211/p2p/12D3KooWCmAnAULhapf1ZPLGpkRjmjJE3yK9APiTSargpSZLdKkX",
        "/ip4/172.233.44.139/udp/1211/quic-v1/p2p/12D3KooWCmAnAULhapf1ZPLGpkRjmjJE3yK9APiTSargpSZLdKkX",
        "/ip6/2600:3c0e::f03c:94ff:fea6:9fc6/tcp/1211/p2p/12D3KooWCmAnAULhapf1ZPLGpkRjmjJE3yK9APiTSargpSZLdKkX",
        "/ip6/2600:3c0e::f03c:94ff:fea6:9fc6/udp/1211/quic-v1/p2p/12D3KooWCmAnAULhapf1ZPLGpkRjmjJE3yK9APiTSargpSZLdKkX",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB