windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.235.160.207/tcp/1211/p2p/12D3KooWKK7YemTwedqAYHKnKo1ZbyzP2RyKHmcUUQd3zCook8XY",
        "/ip4/172.235.160.207/udp/1211/quic-v1/p2p/12D3KooWKK7YemTwedqAYHKnKo1ZbyzP2RyKHmcUUQd3zCook8XY",
        "/ip6/2600:3c0e::f03c:94ff:fe5a:8947/tcp/1211/p2p/12D3KooWKK7YemTwedqAYHKnKo1ZbyzP2RyKHmcUUQd3zCook8XY",
        "/ip6/2600:3c0e::f03c:94ff:fe5a:8947/udp/1211/quic-v1/p2p/12D3KooWKK7YemTwedqAYHKnKo1ZbyzP2RyKHmcUUQd3zCook8XY",
        "/ip6/2a01:7e01::f03c:94ff:fe5a:6293/udp/1211/quic-v1/p2p/12D3KooWKzhGzvMqobs36fyjq5GcjsrPg9GyojsPu5q6HEiH5tuQ",
        "/ip4/172.104.237.100/tcp/1211/p2p/12D3KooWKzhGzvMqobs36fyjq5GcjsrPg9GyojsPu5q6HEiH5tuQ",
        "/ip4/172.104.237.100/udp/1211/quic-v1/p2p/12D3KooWKzhGzvMqobs36fyjq5GcjsrPg9GyojsPu5q6HEiH5tuQ",
        "/ip6/2a01:7e01::f03c:94ff:fe5a:6293/tcp/1211/p2p/12D3KooWKzhGzvMqobs36fyjq5GcjsrPg9GyojsPu5q6HEiH5tuQ",
        "/ip4/172.233.174.24/tcp/1211/p2p/12D3KooWJjnXAdP74CUhtQYLCGtvk8X7X3TYue8H6xqdKr4js4z7",
        "/ip4/172.233.174.24/udp/1211/quic-v1/p2p/12D3KooWJjnXAdP74CUhtQYLCGtvk8X7X3TYue8H6xqdKr4js4z7",
        "/ip6/2a01:7e04::f03c:94ff:fe5a:894f/tcp/1211/p2p/12D3KooWJjnXAdP74CUhtQYLCGtvk8X7X3TYue8H6xqdKr4js4z7",
        "/ip6/2a01:7e04::f03c:94ff:fe5a:894f/udp/1211/quic-v1/p2p/12D3KooWJjnXAdP74CUhtQYLCGtvk8X7X3TYue8H6xqdKr4js4z7",
        "/ip4/172.235.25.84/tcp/1211/p2p/12D3KooWDMfDMLuAo2sA9qgtgsNScCQuykADLevRiMQSbA1YQNkn",
        "/ip4/172.235.25.84/udp/1211/quic-v1/p2p/12D3KooWDMfDMLuAo2sA9qgtgsNScCQuykADLevRiMQSbA1YQNkn",
        "/ip6/2600:3c08::f03c:94ff:fe5a:89c2/tcp/1211/p2p/12D3KooWDMfDMLuAo2sA9qgtgsNScCQuykADLevRiMQSbA1YQNkn",
        "/ip6/2600:3c08::f03c:94ff:fe5a:89c2/udp/1211/quic-v1/p2p/12D3KooWDMfDMLuAo2sA9qgtgsNScCQuykADLevRiMQSbA1YQNkn",
        "/ip6/2400:8907::f03c:94ff:fe5a:6253/tcp/1211/p2p/12D3KooWJmRgjZpvisUJxaaXBLKPhPVWyfLLfDzoVvtSphSaU6hi",
        "/ip6/2400:8907::f03c:94ff:fe5a:6253/udp/1211/quic-v1/p2p/12D3KooWJmRgjZpvisUJxaaXBLKPhPVWyfLLfDzoVvtSphSaU6hi",
        "/ip4/172.105.189.81/tcp/1211/p2p/12D3KooWJmRgjZpvisUJxaaXBLKPhPVWyfLLfDzoVvtSphSaU6hi",
        "/ip4/172.105.189.81/udp/1211/quic-v1/p2p/12D3KooWJmRgjZpvisUJxaaXBLKPhPVWyfLLfDzoVvtSphSaU6hi",
        "/ip4/139.177.196.183/udp/1211/quic-v1/p2p/12D3KooWBM4ScNznkYYhGKWdRk3XMvqHt2aE5gKobJx8onjfJXgH",
        "/ip6/2600:3c04::f03c:94ff:fe5a:620f/tcp/1211/p2p/12D3KooWBM4ScNznkYYhGKWdRk3XMvqHt2aE5gKobJx8onjfJXgH",
        "/ip6/2600:3c04::f03c:94ff:fe5a:620f/udp/1211/quic-v1/p2p/12D3KooWBM4ScNznkYYhGKWdRk3XMvqHt2aE5gKobJx8onjfJXgH",
        "/ip4/139.177.196.183/tcp/1211/p2p/12D3KooWBM4ScNznkYYhGKWdRk3XMvqHt2aE5gKobJx8onjfJXgH",
        "/ip6/2600:3c03::f03c:94ff:fe5a:89cd/udp/1211/quic-v1/p2p/12D3KooWFTapgiQkip7NxRAhprReBTPgcAC3JtkD5HBWqvszjMUh",
        "/ip4/66.175.213.96/tcp/1211/p2p/12D3KooWFTapgiQkip7NxRAhprReBTPgcAC3JtkD5HBWqvszjMUh",
        "/ip4/66.175.213.96/udp/1211/quic-v1/p2p/12D3KooWFTapgiQkip7NxRAhprReBTPgcAC3JtkD5HBWqvszjMUh",
        "/ip6/2600:3c03::f03c:94ff:fe5a:89cd/tcp/1211/p2p/12D3KooWFTapgiQkip7NxRAhprReBTPgcAC3JtkD5HBWqvszjMUh",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securaChainDataPath: ".securachainData/"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB