windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: "."
aesKeyPath: "."
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.235.142.21/tcp/1211/p2p/12D3KooWKqSkU2Z9zaeSg72aCDWjX5vghq7r4CQncRaJB2qtJ9as",
        "/ip4/172.235.142.21/udp/1211/quic-v1/p2p/12D3KooWKqSkU2Z9zaeSg72aCDWjX5vghq7r4CQncRaJB2qtJ9as",
        "/ip6/2a01:7e04::f03c:94ff:fe22:75dc/tcp/1211/p2p/12D3KooWKqSkU2Z9zaeSg72aCDWjX5vghq7r4CQncRaJB2qtJ9as",
        "/ip6/2a01:7e04::f03c:94ff:fe22:75dc/udp/1211/quic-v1/p2p/12D3KooWKqSkU2Z9zaeSg72aCDWjX5vghq7r4CQncRaJB2qtJ9as",
        "/ip4/172.233.85.29/tcp/1211/p2p/12D3KooWS7MEy6eCkDGBkRBorRfQvVtj759sKvCJbxyqsEgbJbiX",
        "/ip4/172.233.85.29/udp/1211/quic-v1/p2p/12D3KooWS7MEy6eCkDGBkRBorRfQvVtj759sKvCJbxyqsEgbJbiX",
        "/ip6/2400:8905::f03c:94ff:fe22:801c/tcp/1211/p2p/12D3KooWS7MEy6eCkDGBkRBorRfQvVtj759sKvCJbxyqsEgbJbiX",
        "/ip6/2400:8905::f03c:94ff:fe22:801c/udp/1211/quic-v1/p2p/12D3KooWS7MEy6eCkDGBkRBorRfQvVtj759sKvCJbxyqsEgbJbiX",
        "/ip4/45.56.77.27/udp/1211/quic-v1/p2p/12D3KooWEqiwXKXkZM712WdsSXiFyMPLyNQJ3BdRgp76qT2Sgaus",
        "/ip6/2600:3c00::f03c:94ff:fe22:8073/tcp/1211/p2p/12D3KooWEqiwXKXkZM712WdsSXiFyMPLyNQJ3BdRgp76qT2Sgaus",
        "/ip6/2600:3c00::f03c:94ff:fe22:8073/udp/1211/quic-v1/p2p/12D3KooWEqiwXKXkZM712WdsSXiFyMPLyNQJ3BdRgp76qT2Sgaus",
        "/ip4/45.56.77.27/tcp/1211/p2p/12D3KooWEqiwXKXkZM712WdsSXiFyMPLyNQJ3BdRgp76qT2Sgaus",
        "/ip6/2600:3c03::f03c:94ff:fe22:8021/tcp/1211/p2p/12D3KooWJfW5H3nsjrZBuUHefAfGPbb7YRXHGCkETSgjUit7Fajc",
        "/ip6/2600:3c03::f03c:94ff:fe22:8021/udp/1211/quic-v1/p2p/12D3KooWJfW5H3nsjrZBuUHefAfGPbb7YRXHGCkETSgjUit7Fajc",
        "/ip4/162.216.16.182/tcp/1211/p2p/12D3KooWJfW5H3nsjrZBuUHefAfGPbb7YRXHGCkETSgjUit7Fajc",
        "/ip4/162.216.16.182/udp/1211/quic-v1/p2p/12D3KooWJfW5H3nsjrZBuUHefAfGPbb7YRXHGCkETSgjUit7Fajc",
        "/ip4/172.232.112.20/tcp/1211/p2p/12D3KooWR8GQHHEK5w6tcDqTFVrxoC4vbDd6Kexnavb4XUPvno8Q",
        "/ip4/172.232.112.20/udp/1211/quic-v1/p2p/12D3KooWR8GQHHEK5w6tcDqTFVrxoC4vbDd6Kexnavb4XUPvno8Q",
        "/ip6/2600:3c08::f03c:94ff:fe22:7532/tcp/1211/p2p/12D3KooWR8GQHHEK5w6tcDqTFVrxoC4vbDd6Kexnavb4XUPvno8Q",
        "/ip6/2600:3c08::f03c:94ff:fe22:7532/udp/1211/quic-v1/p2p/12D3KooWR8GQHHEK5w6tcDqTFVrxoC4vbDd6Kexnavb4XUPvno8Q",
        "/ip6/2400:8904::f03c:94ff:fe22:80ba/tcp/1211/p2p/12D3KooWN9MF7MWSSQLg72DGA5NLMcNJF4mwX9RziwERBkGacRq9",
        "/ip6/2400:8904::f03c:94ff:fe22:80ba/udp/1211/quic-v1/p2p/12D3KooWN9MF7MWSSQLg72DGA5NLMcNJF4mwX9RziwERBkGacRq9",
        "/ip4/172.105.57.249/tcp/1211/p2p/12D3KooWN9MF7MWSSQLg72DGA5NLMcNJF4mwX9RziwERBkGacRq9",
        "/ip4/172.105.57.249/udp/1211/quic-v1/p2p/12D3KooWN9MF7MWSSQLg72DGA5NLMcNJF4mwX9RziwERBkGacRq9",
        "/ip4/172.105.85.114/tcp/1211/p2p/12D3KooWMMX6T2VxHH6Dx6LKRqa9tfnwVpoYwHcKunXtXwWDncLd",
        "/ip4/172.105.85.114/udp/1211/quic-v1/p2p/12D3KooWMMX6T2VxHH6Dx6LKRqa9tfnwVpoYwHcKunXtXwWDncLd",
        "/ip6/2a01:7e01::f03c:94ff:fe22:806b/tcp/1211/p2p/12D3KooWMMX6T2VxHH6Dx6LKRqa9tfnwVpoYwHcKunXtXwWDncLd",
        "/ip6/2a01:7e01::f03c:94ff:fe22:806b/udp/1211/quic-v1/p2p/12D3KooWMMX6T2VxHH6Dx6LKRqa9tfnwVpoYwHcKunXtXwWDncLd",
        "/ip4/139.162.249.234/udp/1211/quic-v1/p2p/12D3KooWBvKSpFMxyPE748jHNqM3Sv8pq78gZ7SDPqpbECYTZefz",
        "/ip6/2a01:7e00::f03c:94ff:fe22:8055/tcp/1211/p2p/12D3KooWBvKSpFMxyPE748jHNqM3Sv8pq78gZ7SDPqpbECYTZefz",
        "/ip6/2a01:7e00::f03c:94ff:fe22:8055/udp/1211/quic-v1/p2p/12D3KooWBvKSpFMxyPE748jHNqM3Sv8pq78gZ7SDPqpbECYTZefz",
        "/ip4/139.162.249.234/tcp/1211/p2p/12D3KooWBvKSpFMxyPE748jHNqM3Sv8pq78gZ7SDPqpbECYTZefz",
        "/ip4/139.162.22.11/udp/1211/quic-v1/p2p/12D3KooWGWny6xpTq5SnjuGoixiYuBQAP2wv9oABSijCFTqaCohc",
        "/ip6/2400:8901::f03c:94ff:fe22:800b/tcp/1211/p2p/12D3KooWGWny6xpTq5SnjuGoixiYuBQAP2wv9oABSijCFTqaCohc",
        "/ip6/2400:8901::f03c:94ff:fe22:800b/udp/1211/quic-v1/p2p/12D3KooWGWny6xpTq5SnjuGoixiYuBQAP2wv9oABSijCFTqaCohc",
        "/ip4/139.162.22.11/tcp/1211/p2p/12D3KooWGWny6xpTq5SnjuGoixiYuBQAP2wv9oABSijCFTqaCohc",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
blockAnnouncementStringFlag: "BlockAnnouncement"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
networkVisualisationStringFlag: "NetworkVisualisation"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
securachainDataPath: ".securachainData/"
blockRegistryPath: "blockRegistry.json"
fileRegistryPath: "fileRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB