windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.102.102/tcp/1211/p2p/12D3KooWLQNTEsbJ6DTwMDmxTBMKoVJupVsZaNscE18LtRc4hWnW",
        "/ip4/172.105.102.102/udp/1211/quic-v1/p2p/12D3KooWLQNTEsbJ6DTwMDmxTBMKoVJupVsZaNscE18LtRc4hWnW",
        "/ip6/2600:3c04::f03c:94ff:fed9:c988/tcp/1211/p2p/12D3KooWLQNTEsbJ6DTwMDmxTBMKoVJupVsZaNscE18LtRc4hWnW",
        "/ip6/2600:3c04::f03c:94ff:fed9:c988/udp/1211/quic-v1/p2p/12D3KooWLQNTEsbJ6DTwMDmxTBMKoVJupVsZaNscE18LtRc4hWnW",
        "/ip4/162.216.16.195/tcp/1211/p2p/12D3KooWRQ7vwPZubf9gLMLqWu8qmeb7EZ1wRgJEQu3XwTABgpcA",
        "/ip4/162.216.16.195/udp/1211/quic-v1/p2p/12D3KooWRQ7vwPZubf9gLMLqWu8qmeb7EZ1wRgJEQu3XwTABgpcA",
        "/ip6/2600:3c03::f03c:94ff:fed9:c9f3/tcp/1211/p2p/12D3KooWRQ7vwPZubf9gLMLqWu8qmeb7EZ1wRgJEQu3XwTABgpcA",
        "/ip6/2600:3c03::f03c:94ff:fed9:c9f3/udp/1211/quic-v1/p2p/12D3KooWRQ7vwPZubf9gLMLqWu8qmeb7EZ1wRgJEQu3XwTABgpcA",
        "/ip4/172.233.40.200/tcp/1211/p2p/12D3KooWQNJZqfT6mJf9rAGS3PaSgEE6AGWkbtgNAiqefN19gXNU",
        "/ip4/172.233.40.200/udp/1211/quic-v1/p2p/12D3KooWQNJZqfT6mJf9rAGS3PaSgEE6AGWkbtgNAiqefN19gXNU",
        "/ip6/2600:3c0e::f03c:94ff:fed9:c958/tcp/1211/p2p/12D3KooWQNJZqfT6mJf9rAGS3PaSgEE6AGWkbtgNAiqefN19gXNU",
        "/ip6/2600:3c0e::f03c:94ff:fed9:c958/udp/1211/quic-v1/p2p/12D3KooWQNJZqfT6mJf9rAGS3PaSgEE6AGWkbtgNAiqefN19gXNU",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB