windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip4/172.105.127.219/tcp/1211/p2p/12D3KooWEqqHDESDpxKdETWYkwVDx3MkWrFs9CnVFXqJkjdirwRe",
        "/ip4/172.105.127.219/udp/1211/quic-v1/p2p/12D3KooWEqqHDESDpxKdETWYkwVDx3MkWrFs9CnVFXqJkjdirwRe",
        "/ip6/2400:8901::f03c:94ff:fe72:258d/tcp/1211/p2p/12D3KooWEqqHDESDpxKdETWYkwVDx3MkWrFs9CnVFXqJkjdirwRe",
        "/ip6/2400:8901::f03c:94ff:fe72:258d/udp/1211/quic-v1/p2p/12D3KooWEqqHDESDpxKdETWYkwVDx3MkWrFs9CnVFXqJkjdirwRe",
        "/ip4/23.92.19.54/tcp/1211/p2p/12D3KooWM3qc1VUe8PR6d84NFQX7seEXbhqHabs4CVhzrvpmDLJq",
        "/ip4/23.92.19.54/udp/1211/quic-v1/p2p/12D3KooWM3qc1VUe8PR6d84NFQX7seEXbhqHabs4CVhzrvpmDLJq",
        "/ip6/2600:3c03::f03c:94ff:fe72:257e/tcp/1211/p2p/12D3KooWM3qc1VUe8PR6d84NFQX7seEXbhqHabs4CVhzrvpmDLJq",
        "/ip6/2600:3c03::f03c:94ff:fe72:257e/udp/1211/quic-v1/p2p/12D3KooWM3qc1VUe8PR6d84NFQX7seEXbhqHabs4CVhzrvpmDLJq",
        "/ip4/172.233.121.225/tcp/1211/p2p/12D3KooWDQBRhA62hzMnDJGWuniuos4c9MMjpnEL7KYLH94gTru8",
        "/ip4/172.233.121.225/udp/1211/quic-v1/p2p/12D3KooWDQBRhA62hzMnDJGWuniuos4c9MMjpnEL7KYLH94gTru8",
        "/ip6/2a01:7e02::f03c:94ff:fe72:2529/tcp/1211/p2p/12D3KooWDQBRhA62hzMnDJGWuniuos4c9MMjpnEL7KYLH94gTru8",
        "/ip6/2a01:7e02::f03c:94ff:fe72:2529/udp/1211/quic-v1/p2p/12D3KooWDQBRhA62hzMnDJGWuniuos4c9MMjpnEL7KYLH94gTru8",
        "/ip4/139.177.199.80/tcp/1211/p2p/12D3KooWSpvtDqN8vbVqdQdixSZQkiBz7TSNjuLmzgGFA9GKkdef",
        "/ip4/139.177.199.80/udp/1211/quic-v1/p2p/12D3KooWSpvtDqN8vbVqdQdixSZQkiBz7TSNjuLmzgGFA9GKkdef",
        "/ip6/2600:3c04::f03c:94ff:fe72:2548/tcp/1211/p2p/12D3KooWSpvtDqN8vbVqdQdixSZQkiBz7TSNjuLmzgGFA9GKkdef",
        "/ip6/2600:3c04::f03c:94ff:fe72:2548/udp/1211/quic-v1/p2p/12D3KooWSpvtDqN8vbVqdQdixSZQkiBz7TSNjuLmzgGFA9GKkdef",
        "/ip6/2600:3c04::f03c:94ff:fe72:254c/udp/1211/quic-v1/p2p/12D3KooWFhFWwnMQcyRZG8u37Jjzo85uKHZ8R14x6taCsFBPLhZL",
        "/ip4/139.177.199.86/tcp/1211/p2p/12D3KooWFhFWwnMQcyRZG8u37Jjzo85uKHZ8R14x6taCsFBPLhZL",
        "/ip4/139.177.199.86/udp/1211/quic-v1/p2p/12D3KooWFhFWwnMQcyRZG8u37Jjzo85uKHZ8R14x6taCsFBPLhZL",
        "/ip6/2600:3c04::f03c:94ff:fe72:254c/tcp/1211/p2p/12D3KooWFhFWwnMQcyRZG8u37Jjzo85uKHZ8R14x6taCsFBPLhZL",
        "/ip4/172.233.16.56/udp/1211/quic-v1/p2p/12D3KooWSV4qvfd7DNg3nD9Vk9t7BkZoeotgYTGgV1xTykhMU5qY",
        "/ip6/2600:3c0d::f03c:94ff:fe72:2544/tcp/1211/p2p/12D3KooWSV4qvfd7DNg3nD9Vk9t7BkZoeotgYTGgV1xTykhMU5qY",
        "/ip6/2600:3c0d::f03c:94ff:fe72:2544/udp/1211/quic-v1/p2p/12D3KooWSV4qvfd7DNg3nD9Vk9t7BkZoeotgYTGgV1xTykhMU5qY",
        "/ip4/172.233.16.56/tcp/1211/p2p/12D3KooWSV4qvfd7DNg3nD9Vk9t7BkZoeotgYTGgV1xTykhMU5qY",
        "/ip4/178.79.130.200/tcp/1211/p2p/12D3KooWSoox2vhrHdoMXWUia2bQQ9stPieWvEKqN83wC17VEvrC",
        "/ip4/178.79.130.200/udp/1211/quic-v1/p2p/12D3KooWSoox2vhrHdoMXWUia2bQQ9stPieWvEKqN83wC17VEvrC",
        "/ip6/2a01:7e00::f03c:94ff:fe72:25dd/tcp/1211/p2p/12D3KooWSoox2vhrHdoMXWUia2bQQ9stPieWvEKqN83wC17VEvrC",
        "/ip6/2a01:7e00::f03c:94ff:fe72:25dd/udp/1211/quic-v1/p2p/12D3KooWSoox2vhrHdoMXWUia2bQQ9stPieWvEKqN83wC17VEvrC",
        "/ip4/172.233.61.180/tcp/1211/p2p/12D3KooWHa5MEUYR37JFxuvvX5oCvjc1sYcnqeetc4zhPWs4nnRj",
        "/ip4/172.233.61.180/udp/1211/quic-v1/p2p/12D3KooWHa5MEUYR37JFxuvvX5oCvjc1sYcnqeetc4zhPWs4nnRj",
        "/ip6/2600:3c0e::f03c:94ff:fe72:25c9/tcp/1211/p2p/12D3KooWHa5MEUYR37JFxuvvX5oCvjc1sYcnqeetc4zhPWs4nnRj",
        "/ip6/2600:3c0e::f03c:94ff:fe72:25c9/udp/1211/quic-v1/p2p/12D3KooWHa5MEUYR37JFxuvvX5oCvjc1sYcnqeetc4zhPWs4nnRj",
        "/ip4/172.235.8.119/tcp/1211/p2p/12D3KooWBoRG7jBwJ98nbVex9hyczUdzbc4JCPUsTj73kRmgU7ND",
        "/ip4/172.235.8.119/udp/1211/quic-v1/p2p/12D3KooWBoRG7jBwJ98nbVex9hyczUdzbc4JCPUsTj73kRmgU7ND",
        "/ip6/2600:3c08::f03c:94ff:fe72:25f0/tcp/1211/p2p/12D3KooWBoRG7jBwJ98nbVex9hyczUdzbc4JCPUsTj73kRmgU7ND",
        "/ip6/2600:3c08::f03c:94ff:fe72:25f0/udp/1211/quic-v1/p2p/12D3KooWBoRG7jBwJ98nbVex9hyczUdzbc4JCPUsTj73kRmgU7ND",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
askingBlockchainStringFlag: "AskingBlockchain"  
receiveBlockchainStringFlag: "ReceiveBlockchain"
askMyFilesStringFlag: "AskMyFiles"
sendFilesStringFlag: "SendFiles"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
blockRegistryPath: "blocksRegistry.json"
indexingRegistryPath: "indexingRegistry.json"
memorySpace: 10 # in GB
fileSizeLimit: 2097152 # 2MB