windowWidth: 800
windowHeight: 600
userAgent: "SecuraChain"
protocolVersion: "0.0.1"
ecdsaKeyPairPath: ""
aesKeyPath: ""
lowWater: 160
highWater: 192
bootstrapPeers: [
        "/ip6/2600:3c03::f03c:94ff:fef5:88b5/tcp/1211/p2p/12D3KooWGFYLqaFuKRpYWa7mZ7zwQjdpfoLQW6CeH1GRzZdGvSKo",
        "/ip6/2600:3c03::f03c:94ff:fef5:88b5/udp/1211/quic-v1/p2p/12D3KooWGFYLqaFuKRpYWa7mZ7zwQjdpfoLQW6CeH1GRzZdGvSKo",
        "/ip4/198.74.62.104/tcp/1211/p2p/12D3KooWGFYLqaFuKRpYWa7mZ7zwQjdpfoLQW6CeH1GRzZdGvSKo",
        "/ip4/198.74.62.104/udp/1211/quic-v1/p2p/12D3KooWGFYLqaFuKRpYWa7mZ7zwQjdpfoLQW6CeH1GRzZdGvSKo",
        "/ip4/139.162.8.73/tcp/1211/p2p/12D3KooWANrHT2QWD8rjGPtzkAZqagihtNXe6bz4k4WhrH1AYioB",
        "/ip4/139.162.8.73/udp/1211/quic-v1/p2p/12D3KooWANrHT2QWD8rjGPtzkAZqagihtNXe6bz4k4WhrH1AYioB",
        "/ip6/2400:8901::f03c:94ff:fef5:88e6/tcp/1211/p2p/12D3KooWANrHT2QWD8rjGPtzkAZqagihtNXe6bz4k4WhrH1AYioB",
        "/ip6/2400:8901::f03c:94ff:fef5:88e6/udp/1211/quic-v1/p2p/12D3KooWANrHT2QWD8rjGPtzkAZqagihtNXe6bz4k4WhrH1AYioB",
        "/ip6/2600:3c0e::f03c:94ff:fef5:8800/tcp/1211/p2p/12D3KooWRWE8qw5Mx9qpi6v5PV3oqUfpZsgRaBT4Bs3uuX1gyEpc",
        "/ip6/2600:3c0e::f03c:94ff:fef5:8800/udp/1211/quic-v1/p2p/12D3KooWRWE8qw5Mx9qpi6v5PV3oqUfpZsgRaBT4Bs3uuX1gyEpc",
        "/ip4/172.233.59.106/tcp/1211/p2p/12D3KooWRWE8qw5Mx9qpi6v5PV3oqUfpZsgRaBT4Bs3uuX1gyEpc",
        "/ip4/172.233.59.106/udp/1211/quic-v1/p2p/12D3KooWRWE8qw5Mx9qpi6v5PV3oqUfpZsgRaBT4Bs3uuX1gyEpc",
        "/ip4/178.79.166.146/tcp/1211/p2p/12D3KooWRjuiCy1zdJy4UDNTWfoetVH3QXAt3131ftTSEDVwzTi5",
        "/ip4/178.79.166.146/udp/1211/quic-v1/p2p/12D3KooWRjuiCy1zdJy4UDNTWfoetVH3QXAt3131ftTSEDVwzTi5",
        "/ip6/2a01:7e00::f03c:94ff:fef5:880a/tcp/1211/p2p/12D3KooWRjuiCy1zdJy4UDNTWfoetVH3QXAt3131ftTSEDVwzTi5",
        "/ip6/2a01:7e00::f03c:94ff:fef5:880a/udp/1211/quic-v1/p2p/12D3KooWRjuiCy1zdJy4UDNTWfoetVH3QXAt3131ftTSEDVwzTi5",
    ]
listeningPort: 0
discoveryRefreshInterval: 10s
autorelayWithBackoffInterval: 10s
autorelayWithMinCallbackInterval: 10s
keepRelayConnectionAliveInterval: 15s
maxRelayedConnectionDuration: 1h
maxDataRelayed: 1073741824 # 1GB
relayReservationTTL: 1h
maxRelayReservations: 128
maxRelayCircuits: 16
maxRelayedConnectionBufferSize: 2048
maxRelayReservationsPerPeer: 4
maxRelayReservationsPerIP: 8
maxRelayReservationsPerASN: 32
ipfsProvidersDiscoveryRefreshInterval: 10s
ip4tcp: "/ip4/0.0.0.0/tcp/0"
ip6tcp: "/ip6/::/tcp/0"
ip4quic: "/ip4/0.0.0.0/udp/0/quic-v1"
ip6quic: "/ip6/::/udp/0/quic-v1"
rendezvousStringFlag: "SecuraChainNetwork"
clientAnnouncementStringFlag: "ClientAnnouncement"
storageNodeResponseStringFlag: "StorageNodeResponse"
keepRelayConnectionAliveStringFlag: "KeepRelayConnectionAlive"
fileRights: 0700
fileMetadataRegistryJson: "fileMetadataRegistry.json"
memorySpace: 10 # in GB